<template><q-page class="page"><section class="head"><div><p class="eyebrow">ASSISTENTE COM EVIDÊNCIAS</p><h1>Consulte seu edital</h1><p>As respostas usam somente as páginas extraídas e mostram suas fontes.</p></div></section><q-banner v-if="error" rounded class="error">{{ error }}</q-banner><q-inner-loading :showing="loading" color="primary"/><div class="layout"><q-card flat class="sidebar"><q-card-section><h2>Nova conversa</h2><q-select v-model="selectedSyllabus" outlined dense label="Edital extraído" :options="syllabi" option-label="name" option-value="id" emit-value map-options/><q-input v-model="title" outlined dense class="q-mt-sm" label="Título (opcional)"/><q-btn unelevated no-caps class="q-mt-sm full-width" color="primary" label="Iniciar consulta" :disable="!selectedSyllabus" @click="start"/></q-card-section><q-separator/><q-list><q-item v-for="conversation in conversations" :key="conversation.id" clickable :active="active?.id===conversation.id" @click="select(conversation)"><q-item-section><q-item-label>{{ conversation.title }}</q-item-label><q-item-label caption>Conversa auditável</q-item-label></q-item-section></q-item></q-list></q-card><q-card flat class="chat"><q-card-section v-if="!active" class="empty"><q-icon name="menu_book" size="42px" color="primary"/><h2>Escolha um edital para começar</h2><p>Nenhuma resposta é criada sem uma fonte recuperada.</p></q-card-section><template v-else><q-card-section class="chat-title"><div><h2>{{ active.title }}</h2><p>Provider local · modelo deterministic-v1</p></div><q-badge color="positive" label="EVIDENCIADO"/></q-card-section><q-separator/><q-card-section class="messages"><article v-for="message in messages" :key="message.id" :class="['message',message.role.toLowerCase()]"><p>{{ message.content }}</p><div v-if="message.evidence.length" class="evidence"><q-chip v-for="item in message.evidence" :key="item.pageNumber" dense color="blue-1" text-color="primary">Página {{ item.pageNumber }}</q-chip><q-expansion-item v-for="item in message.evidence" :key="item.excerpt" dense label="Ver trecho utilizado"><p>{{ item.excerpt }}</p></q-expansion-item></div></article></q-card-section><q-separator/><q-form class="composer" @submit.prevent="ask"><q-input v-model="question" outlined autogrow label="Pergunte sobre o edital" :disable="sending"/><q-btn unelevated round color="primary" icon="send" type="submit" :loading="sending" :disable="question.trim().length<3"/></q-form></template></q-card></div></q-page></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useAssistant } from './useAssistant'
const { active, conversations, create, error, load, loading, messages, select, sending, send, syllabi } = useAssistant()
const selectedSyllabus = ref('')
const title = ref('')
const question = ref('')
async function start(): Promise<void> { await create(selectedSyllabus.value, title.value); title.value = ''; question.value = '' }
async function ask(): Promise<void> { const value = question.value; question.value = ''; await send(value) }
onMounted(load)
</script>
<style scoped>.page{max-width:1240px;margin:auto;padding:42px 34px}.head h1,.sidebar h2,.chat h2{margin:0;color:#142950}.head p:not(.eyebrow),.chat-title p{color:#71819e}.eyebrow{margin:0 0 8px;color:#7187ad;font-size:11px;font-weight:800;letter-spacing:.1em}.layout{display:grid;grid-template-columns:310px 1fr;gap:18px;margin-top:25px}.sidebar,.chat{border:1px solid #e5ecf6;border-radius:18px;box-shadow:0 8px 26px rgba(33,58,105,.045)}.chat{min-height:590px}.chat-title,.composer{display:flex;justify-content:space-between;align-items:center;gap:14px}.messages{min-height:410px;max-height:520px;overflow:auto;background:#f8faff}.message{max-width:82%;margin:12px 0;padding:13px 15px;border-radius:14px;background:#fff;color:#273958}.message p{white-space:pre-line;margin:0}.message.user{margin-left:auto;background:#e7efff}.evidence{margin-top:10px}.evidence p{font-size:13px;color:#697b9a}.composer{padding:16px}.composer .q-field{flex:1}.empty{padding:110px 30px;text-align:center;color:#71819e}.error{margin-top:16px;background:#fff3f2;color:#ae2f25}@media(max-width:750px){.page{padding:28px 16px}.layout{grid-template-columns:1fr}.chat{min-height:460px}}</style>
