<?php
declare(strict_types=1);
namespace App\Interface\Http\QuestionBank\Controller;
use App\Application\Identity\DTO\Request\AccessTokenRequestDto;use App\Application\Identity\Service\AuthService;use App\Application\QuestionBank\Service\QuestionCorrectionRequestService;use App\Domain\Identity\Exception\UnavailableUserException;use App\Infrastructure\Http\ApiResponseFactory;use DomainException;use Psr\Http\Message\ResponseInterface;use Psr\Http\Message\ServerRequestInterface;
final class QuestionCorrectionRequestController { public function __construct(private readonly AuthService $auth,private readonly QuestionCorrectionRequestService $service,private readonly ApiResponseFactory $responses){}
 public function create(ServerRequestInterface $request,ResponseInterface $response,AccessTokenRequestDto $access,string $questionId,callable $input):ResponseInterface{try{$user=$this->auth->currentUser($access);return $this->responses->success($response,$this->service->request($input($user->id)),$this->id($request));}catch(\InvalidArgumentException $e){return $this->responses->problem($response,'VALIDATION_FAILED',$e->getMessage(),422,$this->id($request));}catch(\DomainException $e){return $this->responses->problem($response,'RESOURCE_NOT_FOUND',$e->getMessage(),404,$this->id($request));}catch(UnavailableUserException){return $this->unauth($response,$request);}}
 public function latest(ServerRequestInterface $request,ResponseInterface $response,AccessTokenRequestDto $access,string $questionId):ResponseInterface{try{$user=$this->auth->currentUser($access);$admin=in_array('ADMIN',$user->roles,true);$item=$this->service->latest($questionId,$user->id,$admin);return $item===null?$this->responses->problem($response,'RESOURCE_NOT_FOUND','Nenhuma solicitação encontrada.',404,$this->id($request)):$this->responses->success($response,$item,$this->id($request));}catch(DomainException|UnavailableUserException){return $this->unauth($response,$request);}}
 public function latestMine(ServerRequestInterface $request,ResponseInterface $response,AccessTokenRequestDto $access):ResponseInterface{try{$user=$this->auth->currentUser($access);$item=$this->service->latestCompletedForUser($user->id,in_array('ADMIN',$user->roles,true));return $item===null?$this->responses->problem($response,'RESOURCE_NOT_FOUND','Nenhum resultado de correção encontrado.',404,$this->id($request)):$this->responses->success($response,$item,$this->id($request));}catch(DomainException|UnavailableUserException){return $this->unauth($response,$request);}}
 public function approve(ServerRequestInterface $request,ResponseInterface $response,AccessTokenRequestDto $access,string $id):ResponseInterface{try{$user=$this->auth->currentUser($access);if(!in_array('ADMIN',$user->roles,true))return $this->responses->problem($response,'FORBIDDEN','Permissão insuficiente.',403,$this->id($request));return $this->responses->success($response,$this->service->approve($id,$user->id),$this->id($request));}catch(\DomainException $e){return $this->responses->problem($response,'STATE_CONFLICT',$e->getMessage(),409,$this->id($request));}catch(UnavailableUserException){return $this->unauth($response,$request);}}
 private function id(ServerRequestInterface $r):string{return(string)$r->getAttribute('request_id');}private function unauth(ResponseInterface $p,ServerRequestInterface $r):ResponseInterface{return $this->responses->problem($p,'UNAUTHENTICATED','Credenciais invalidas ou expiradas.',401,$this->id($r));}}
