export type ProblemReportCategory = 'CONTENT' | 'ANSWER_KEY' | 'IMAGE' | 'DUPLICATE' | 'OTHER'
export type ExplanationStatus = 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED'
export interface QuestionNote { readonly questionId: string; readonly content: string; readonly createdAt: string; readonly updatedAt: string }
export interface QuestionInteraction { readonly questionId: string; readonly favorite: boolean; readonly reviewLater: boolean; readonly notMastered: boolean; readonly note: QuestionNote | null; readonly commentCount: number; readonly ownOpenReportCount: number }
export interface QuestionComment { readonly id: string; readonly questionId: string; readonly authorUserId: string; readonly parentId: string | null; readonly content: string; readonly createdAt: string }
export interface QuestionProblemReport { readonly id: string; readonly questionId: string; readonly category: ProblemReportCategory; readonly description: string; readonly status: string; readonly createdAt: string; readonly updatedAt: string }
export interface QuestionExplanation { readonly id: string; readonly questionId: string; readonly attemptId: string | null; readonly status: ExplanationStatus; readonly safetyMode: 'CONCEPTUAL_ONLY' | 'POST_ANSWER'; readonly requestedAt: string; readonly completedAt: string | null; readonly result: Readonly<Record<string, unknown>> | null; readonly errorMessage: string | null }
export interface UpdateQuestionInteractionCommand { readonly favorite?: boolean; readonly reviewLater?: boolean; readonly notMastered?: boolean }
export interface CreateQuestionCommentCommand { readonly content: string; readonly parentId?: string }
export interface CreateQuestionProblemReportCommand { readonly category: ProblemReportCategory; readonly description: string }
export interface QuestionLearningRepository { getInteraction(questionId: string): Promise<QuestionInteraction>; updateInteraction(questionId: string, command: UpdateQuestionInteractionCommand): Promise<QuestionInteraction>; getNote(questionId: string): Promise<QuestionNote | null>; saveNote(questionId: string, content: string): Promise<QuestionNote>; listComments(questionId: string, page?: number, perPage?: number): Promise<readonly QuestionComment[]>; createComment(questionId: string, command: CreateQuestionCommentCommand): Promise<QuestionComment>; createProblemReport(questionId: string, command: CreateQuestionProblemReportCommand): Promise<QuestionProblemReport>; requestExplanation(questionId: string, attemptId?: string): Promise<QuestionExplanation>; latestExplanation(questionId: string): Promise<QuestionExplanation> }
