export interface ImportRow { readonly rowNumber: number; readonly valid: boolean; readonly errors: readonly { readonly field: string; readonly code: string; readonly message: string }[] }
export interface ImportReport { readonly importId: string | null; readonly validRows: number; readonly invalidRows: number; readonly rows: readonly ImportRow[] }
export interface QuestionImportTelemetry { readonly provider: string; readonly model: string | null; readonly schemaVersion: string; readonly durationMilliseconds: number; readonly usageAvailability: 'AVAILABLE' | 'UNAVAILABLE'; readonly inputTokens: number | null; readonly outputTokens: number | null; readonly totalTokens: number | null; readonly costUsd: string | null; readonly analysisCount: number; readonly answerKeyConflictCount: number; readonly imageDiscrepancyCount: number; readonly structuralIssueCount: number }
export interface QuestionImportAnalysisFinding { readonly code: string; readonly severity: string; readonly confidence: number | null; readonly safeSummary: string; readonly evidencePages: readonly number[] }
export interface QuestionImportAnalysisAnchor { readonly target: string; readonly optionPosition: number | null; readonly sourcePage: number; readonly sourceAssetIndex: number | null; readonly status: string }
export interface QuestionImportAnalysis { readonly id: string; readonly questionId: string | null; readonly candidateFingerprint: string; readonly provider: string; readonly model: string | null; readonly evidencePages: readonly number[]; readonly exam: string | null; readonly position: string | null; readonly board: string | null; readonly year: number | null; readonly structureType: string; readonly answerKeyAssessment: string; readonly imageAssessment: string; readonly durationMilliseconds: number; readonly usageAvailability: 'AVAILABLE' | 'UNAVAILABLE'; readonly inputTokens: number | null; readonly outputTokens: number | null; readonly totalTokens: number | null; readonly costUsd: string | null; readonly findings: readonly QuestionImportAnalysisFinding[]; readonly imageAnchors: readonly QuestionImportAnalysisAnchor[]; readonly createdAt: string }
export interface QuestionPdfImportJob { readonly id: string; readonly syllabusId: string | null; readonly documentOriginalName: string; readonly status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'CANCELLED'; readonly progress: number; readonly pageCount: number; readonly candidatePages: number; readonly extractedQuestions: number; readonly classifiedQuestions: number; readonly createdQuestions: number; readonly duplicateQuestions: number; readonly failedQuestions: number; readonly createdTaxonomySubjects: number; readonly errorMessage: string | null; readonly createdAt: string; readonly startedAt: string | null; readonly finishedAt: string | null; readonly analysisTelemetry: QuestionImportTelemetry | null }
export interface QuestionPdfImportJobPage { readonly items: readonly QuestionPdfImportJob[]; readonly page: number; readonly perPage: number; readonly total: number }
export interface ImportRepository { preview(format: 'JSON' | 'CSV', content: string): Promise<ImportReport>; commit(importId: string, syllabusId: string): Promise<{ readonly importId: string; readonly createdQuestions: number }>; queuePdfImports(documents: readonly File[]): Promise<readonly QuestionPdfImportJob[]>; getPdfImportJob(id: string): Promise<QuestionPdfImportJob>; getPdfImportAnalyses(id: string): Promise<readonly QuestionImportAnalysis[]>; cancelPdfImportJob(id: string): Promise<void>; listPdfImportJobs(page?: number, perPage?: number): Promise<QuestionPdfImportJobPage> }
