<template>
  <section class="login-page"><div class="login-panel"><div class="login-copy"><q-img src="/images/concursos-study-mark.png" class="brand-image" fit="contain" /><p class="eyebrow">PLATAFORMA DE ESTUDOS</p><h1>Estude. Evolua.<br>Conquiste.</h1><p>Organize cadernos, pratique com questões reais e acompanhe seu desempenho sem perder o ritmo.</p><div class="login-benefits"><span>Seleções personalizadas</span><span>Histórico de tentativas</span><span>Evolução por desempenho</span></div></div><q-card flat class="login-card"><q-form @submit.prevent="submit"><q-card-section><p class="eyebrow form-eyebrow">ACESSO SEGURO</p><h2>Bem-vindo de volta</h2><p>Entre para continuar sua preparação.</p></q-card-section><q-card-section class="q-gutter-md"><q-input v-model="email" outlined label="E-mail" type="email" autocomplete="email" /><q-input v-model="password" outlined label="Senha" type="password" autocomplete="current-password" @keyup.enter="submit" /><q-banner v-if="error" rounded class="login-error">{{ error }}</q-banner><q-btn type="submit" unelevated no-caps class="login-submit" label="Entrar na plataforma" :loading="submitting" /></q-card-section></q-form></q-card></div></section>
</template>
<script setup lang="ts">
import { ref } from 'vue'
defineProps<{ readonly submitting: boolean; readonly error: string }>()
const emit = defineEmits<{ submit: [email: string, password: string] }>()
const email = ref(''); const password = ref('')
function submit(): void { emit('submit', email.value, password.value) }
</script>
<style scoped>
.login-page{min-height:100vh;background:radial-gradient(circle at 10% 10%,#e2eeff,transparent 34%),linear-gradient(135deg,#f5f8fd,#eef4ff);display:grid;place-items:center;padding:24px}.login-panel{width:min(1030px,100%);display:grid;grid-template-columns:1.13fr .87fr;overflow:hidden;border:1px solid #e2eaf7;border-radius:25px;background:#fff;box-shadow:0 26px 75px rgba(31,67,138,.16)}.login-copy{padding:52px 58px;background:linear-gradient(145deg,#163e88,#2a70dc);color:#fff}.brand-image{width:78px;height:78px}.eyebrow{font-size:11px;letter-spacing:.1em;font-weight:800;color:#d8e8ff;margin:21px 0 8px}.login-copy h1{margin:0 0 18px;font-size:37px;line-height:1.15;letter-spacing:-.03em}.login-copy p{color:#e0edff;line-height:1.65}.login-benefits{display:grid;gap:12px;margin-top:28px;color:#e6f0ff;font-size:14px}.login-benefits span:before{content:'✓';margin-right:9px;font-weight:800}.login-card{padding:28px 19px;align-self:center}.form-eyebrow{color:#6980aa;margin-top:0}.login-card h2{margin:0;color:#18305c;font-size:24px}.login-card p:not(.eyebrow){color:#758198;font-size:14px}.login-submit{width:100%;border-radius:10px;padding:10px}.login-error{background:#fff0f0;color:#b42318}@media(max-width:700px){.login-panel{grid-template-columns:1fr}.login-copy{padding:34px}.login-copy h1{font-size:29px}.login-card{padding:22px 10px}}
</style>
