<?php
declare(strict_types=1);
namespace App\Application\Identity\Service;
use App\Application\Identity\DTO\Request\GoogleLoginRequestDto;use App\Application\Identity\DTO\Response\GoogleAuthenticationResponseDto;use App\Application\Identity\Port\{ClockInterface,GoogleAvatarImporterInterface,GoogleOidcValidatorInterface,TransactionManagerInterface};use App\Domain\Identity\Entity\{GoogleIdentity,User};use App\Domain\Identity\Exception\GoogleIdentityConflictException;use App\Domain\Identity\Repository\{GoogleIdentityRepositoryInterface,UserRepositoryInterface};use App\Domain\Identity\ValueObject\GoogleEmail;
final class GoogleAuthenticationService
{
 public function __construct(private readonly GoogleOidcValidatorInterface $validator,private readonly UserRepositoryInterface $users,private readonly GoogleIdentityRepositoryInterface $identities,private readonly AuthService $auth,private readonly ClockInterface $clock,private readonly TransactionManagerInterface $transactions,private readonly ?GoogleAvatarImporterInterface $avatars=null){}
 public function authenticate(GoogleLoginRequestDto $request):GoogleAuthenticationResponseDto{$identity=$this->validator->validate($request->credential);$email=GoogleEmail::from($identity->email);return $this->transactions->transactional(function()use($identity,$email,$request):GoogleAuthenticationResponseDto{$link=$this->identities->findByEmail($email);if($link===null){if($this->users->findByEmail($email->value)!==null)throw new GoogleIdentityConflictException('Associe a identidade Google pela administração.');$now=$this->clock->now();$id=$this->uuid();$user=new User($id,$email->value,$identity->name,null,'PENDING_APPROVAL',['USER'],$this->avatars?->import($id,$identity->pictureUrl));$this->users->save($user);$this->identities->save(new GoogleIdentity($id,$email,$now,$now));return GoogleAuthenticationResponseDto::pending();}$user=$this->users->findById($link->userId);if($user===null||!$user->isActive())return GoogleAuthenticationResponseDto::pending();return GoogleAuthenticationResponseDto::authenticated($this->auth->issueSessionForActiveUser($user,$request->deviceName));});}
 private function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
