<?php
declare(strict_types=1);namespace App\Application\Identity\Service;
use App\Application\Identity\DTO\Request\ReplaceAvatarRequestDto;use App\Application\Identity\DTO\Response\ProfileAvatarResponseDto;use App\Application\Identity\Port\{AvatarStorageInterface,TransactionManagerInterface};use App\Domain\Identity\Entity\{User,UserAvatar};use App\Domain\Identity\Enum\AvatarSource;use App\Domain\Identity\Repository\UserRepositoryInterface;
final class ProfileAvatarService {
 public function __construct(private readonly UserRepositoryInterface $users,private readonly AvatarStorageInterface $storage,private readonly TransactionManagerInterface $transactions){}
 public function metadata(string $userId):ProfileAvatarResponseDto{$avatar=$this->required($userId)->avatar;return new ProfileAvatarResponseDto($avatar!==null,$avatar?->mimeType,$avatar?->updatedAt->format(DATE_ATOM));}
 public function contents(string $userId):?array{$avatar=$this->required($userId)->avatar;if($avatar===null)return null;$contents=$this->storage->read($avatar->storageKey);return $contents===null?null:['contents'=>$contents,'mimeType'=>$avatar->mimeType];}
 public function replace(ReplaceAvatarRequestDto $request):ProfileAvatarResponseDto{$contents=$this->normalize($request->contents);$stored=$this->storage->store($request->userId,$contents,'image/webp');$old=null;try{$result=$this->transactions->transactional(function()use($request,$stored,&$old){$user=$this->required($request->userId);$old=$user->avatar;$next=new User($user->id,$user->email,$user->name,$user->passwordHash,$user->status,$user->roles,new UserAvatar($stored->storageKey,'image/webp',AvatarSource::MANUAL,new \DateTimeImmutable('now')));$this->users->save($next);return $this->metadataFrom($next);});if($old!==null)$this->storage->remove($old->storageKey);return$result;}catch(\Throwable $exception){$this->storage->remove($stored->storageKey);throw$exception;}}
 private function normalize(string $contents):string{if($contents===''||strlen($contents)>5*1024*1024)throw new \InvalidArgumentException('A imagem deve ter no máximo 5 MB.');$info=@getimagesizefromstring($contents);if(!is_array($info)||$info[0]<32||$info[1]<32||$info[0]>4096||$info[1]>4096)throw new \InvalidArgumentException('Imagem inválida ou fora dos limites permitidos.');$image=@imagecreatefromstring($contents);if($image===false)throw new \InvalidArgumentException('Imagem inválida.');ob_start();$ok=imagewebp($image,null,85);$webp=(string)ob_get_clean();imagedestroy($image);if(!$ok||$webp===''||strlen($webp)>5*1024*1024)throw new \InvalidArgumentException('Não foi possível normalizar a imagem.');return$webp;}
 private function required(string $id):User{return $this->users->findById($id)??throw new \DomainException('Usuário não encontrado.');}private function metadataFrom(User $user):ProfileAvatarResponseDto{$avatar=$user->avatar;return new ProfileAvatarResponseDto($avatar!==null,$avatar?->mimeType,$avatar?->updatedAt->format(DATE_ATOM));}
}
