<?php
declare(strict_types=1);namespace App\Application\Identity\Service;
use App\Application\Identity\DTO\Request\{CreateAdminUserRequestDto,SetGoogleIdentityRequestDto,UpdateUserRolesRequestDto,UpdateUserStatusRequestDto};use App\Application\Identity\DTO\Response\AdminUserResponseDto;use App\Application\Identity\Port\{ClockInterface,PasswordHasherInterface,TransactionManagerInterface};use App\Domain\Identity\Entity\{GoogleIdentity,IdentityAuditEvent,User};use App\Domain\Identity\Repository\{GoogleIdentityRepositoryInterface,IdentityAuditEventRepositoryInterface,UserRepositoryInterface};use App\Domain\Identity\ValueObject\GoogleEmail;
final class UserAdministrationService
{
 public function __construct(private readonly UserRepositoryInterface $users,private readonly GoogleIdentityRepositoryInterface $google,private readonly IdentityAuditEventRepositoryInterface $audit,private readonly PasswordHasherInterface $passwords,private readonly ClockInterface $clock,private readonly TransactionManagerInterface $transactions){}
 /** @return array{items:list<AdminUserResponseDto>,total:int} */public function list(int $page,int $perPage,?string $query,?string $status):array{$status=$this->validatedStatus($status,true);$items=array_map(fn(User $user):AdminUserResponseDto=>$this->dto($user),$this->users->list(($page-1)*$perPage,$perPage,$query,$status));return['items'=>$items,'total'=>$this->users->count($query,$status)];}
 public function create(CreateAdminUserRequestDto $r):AdminUserResponseDto{return $this->transactions->transactional(function()use($r){$email=$this->email($r->email);if($this->users->findByEmail($email)!==null)throw new \DomainException('E-mail já utilizado.');$roles=$this->validatedRoles($r->roles);$status=$this->validatedStatus($r->status);if($r->password!==null&&strlen($r->password)<12)throw new \InvalidArgumentException('Senha deve ter ao menos 12 caracteres.');$id=$this->uuid();$user=new User($id,$email,$this->name($r->name),$r->password===null?null:$this->passwords->hash($r->password),$status,$roles);$this->users->save($user);if($r->googleEmail!==null)$this->persistGoogle($r->actorUserId,$id,$r->googleEmail);$this->event($r->actorUserId,$id,'USER_CREATED',null,['status'=>$status]);return $this->dto($user);});}
 public function setGoogle(string $actor,string $id,string $email):AdminUserResponseDto{return $this->transactions->transactional(function()use($actor,$id,$email){$user=$this->required($id);$this->persistGoogle($actor,$id,$email);return $this->dto($user);});}
 public function removeGoogle(string $actor,string $id):AdminUserResponseDto{return $this->transactions->transactional(function()use($actor,$id){$user=$this->required($id);$old=$this->google->findByUserId($id);$this->google->removeForUserId($id);$this->event($actor,$id,'GOOGLE_IDENTITY_REMOVED',$old===null?null:['google_email'=>$old->email->value],null);return $this->dto($user);});}
 public function roles(UpdateUserRolesRequestDto $r):AdminUserResponseDto{return $this->transactions->transactional(function()use($r){$u=$this->required($r->userId);$roles=$this->validatedRoles($r->roles);$this->protectLastAdmin($u,$roles,$u->status);$next=new User($u->id,$u->email,$u->name,$u->passwordHash,$u->status,$roles,$u->avatar);$this->users->save($next);$this->event($r->actorUserId,$u->id,'USER_ROLES_CHANGED',['roles'=>implode(',',$u->roles)],['roles'=>implode(',',$roles)]);return $this->dto($next);});}
 public function status(UpdateUserStatusRequestDto $r):AdminUserResponseDto{return $this->transactions->transactional(function()use($r){$u=$this->required($r->userId);$status=$this->validatedStatus($r->status);$this->protectLastAdmin($u,$u->roles,$status);$next=new User($u->id,$u->email,$u->name,$u->passwordHash,$status,$u->roles,$u->avatar);$this->users->save($next);$this->event($r->actorUserId,$u->id,'USER_STATUS_CHANGED',['status'=>$u->status],['status'=>$status]);return $this->dto($next);});}
 private function persistGoogle(string $actor,string $id,string $email):void{$value=GoogleEmail::from($email);$existing=$this->google->findByEmail($value);if($existing!==null&&$existing->userId!==$id)throw new \DomainException('E-mail Google já utilizado.');$old=$this->google->findByUserId($id);$now=$this->clock->now();$this->google->save(new GoogleIdentity($id,$value,$old?->createdAt??$now,$now));$this->event($actor,$id,'GOOGLE_IDENTITY_SET',$old===null?null:['google_email'=>$old->email->value],['google_email'=>$value->value]);}
 private function protectLastAdmin(User $u,array $roles,string $status):void{if(in_array('ADMIN',$u->roles,true)&&$u->status==='ACTIVE'&&(!in_array('ADMIN',$roles,true)||$status!=='ACTIVE')&&$this->users->countActiveAdmins()<=1)throw new \DomainException('É necessário manter um administrador ativo.');}
 private function dto(User $u):AdminUserResponseDto{return new AdminUserResponseDto($u->id,$u->name,$u->email,$this->google->findByUserId($u->id)?->email->value,$u->roles,$u->status);}private function required(string $id):User{return $this->users->findById($id)??throw new \DomainException('Usuário não encontrado.');}private function event(string $actor,string $subject,string $event,?array $before,?array $after):void{$this->audit->append(new IdentityAuditEvent($actor,$subject,$event,$before,$after,$this->clock->now()));}private function validatedRoles(array $r):array{$r=array_values(array_unique(array_map(fn($v)=>strtoupper(trim((string)$v)),$r)));if($r===[]||array_diff($r,['ADMIN','USER'])!==[])throw new \InvalidArgumentException('Papéis inválidos.');return$r;}private function validatedStatus(?string $status,bool $nullable=false):?string{if($status===null&&$nullable)return null;if(!in_array($status,['ACTIVE','PENDING_APPROVAL','BLOCKED'],true))throw new \InvalidArgumentException('Status inválido.');return$status;}private function email(string $e):string{$e=mb_strtolower(trim($e));if(filter_var($e,FILTER_VALIDATE_EMAIL)===false)throw new \InvalidArgumentException('E-mail inválido.');return$e;}private function name(string $n):string{$n=trim($n);if($n==='')throw new \InvalidArgumentException('Nome obrigatório.');return mb_substr($n,0,160);}private function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
