CREATE TABLE question_pdf_import_jobs (
  id CHAR(36) PRIMARY KEY,
  syllabus_id CHAR(36) NOT NULL,
  created_by CHAR(36) NOT NULL,
  document_path VARCHAR(1024) NOT NULL,
  document_sha256 CHAR(64) NOT NULL,
  document_original_name VARCHAR(255) NOT NULL,
  status ENUM('PENDING','PROCESSING','COMPLETED','FAILED') NOT NULL DEFAULT 'PENDING',
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  page_count INT UNSIGNED NOT NULL DEFAULT 0,
  candidate_pages INT UNSIGNED NOT NULL DEFAULT 0,
  extracted_questions INT UNSIGNED NOT NULL DEFAULT 0,
  classified_questions INT UNSIGNED NOT NULL DEFAULT 0,
  created_questions INT UNSIGNED NOT NULL DEFAULT 0,
  duplicate_questions INT UNSIGNED NOT NULL DEFAULT 0,
  failed_questions INT UNSIGNED NOT NULL DEFAULT 0,
  created_taxonomy_subjects INT UNSIGNED NOT NULL DEFAULT 0,
  error_message VARCHAR(500) NULL,
  created_at DATETIME NOT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  CONSTRAINT fk_question_pdf_job_syllabus FOREIGN KEY (syllabus_id) REFERENCES syllabi(id),
  CONSTRAINT fk_question_pdf_job_creator FOREIGN KEY (created_by) REFERENCES users(id),
  INDEX idx_question_pdf_job_next (status, created_at),
  INDEX idx_question_pdf_job_owner (created_by, created_at)
);
