<?php
declare(strict_types=1);
namespace App\Application\QuestionBank\Service;
use App\Application\Assistant\Port\AssistantProviderInterface;
use App\Application\Catalog\Port\PdfTextExtractorInterface;
use App\Application\QuestionBank\Port\QuestionPdfQuestionWriterInterface;
use App\Domain\Assistant\ValueObject\SyllabusEvidence;
use App\Domain\QuestionBank\Entity\QuestionPdfImportJob;
use App\Domain\QuestionBank\Repository\QuestionPdfImportJobRepositoryInterface;
use App\Domain\Taxonomy\Repository\TaxonomySubjectRepositoryInterface;
final class ProcessQuestionPdfImportJobService
{
    private const MAX_RETRIES = 5;
    public function __construct(private readonly QuestionPdfImportJobRepositoryInterface $jobs,private readonly PdfTextExtractorInterface $pdf,private readonly AssistantProviderInterface $ai,private readonly TaxonomySubjectRepositoryInterface $taxonomy,private readonly QuestionPdfQuestionWriterInterface $writer) {}
    public function processNext(): bool
    {
        $job=$this->jobs->claimNext(); if($job===null)return false;
        try {
            $pages=$this->pdf->extractPages($job->documentPath); $candidates=[]; foreach($pages as $index=>$text)if($this->hasQuestion($text))$candidates[$index+1]=$text;
            $chunks=array_chunk($candidates,3,true); $job=$this->state($job,12,count($pages),count($candidates)); $this->jobs->save($job);
            for($index=$job->processedChunks;$index<count($chunks);$index++) { if($this->jobs->isCancelled($job->id)) return true; $questions=$this->extract($chunks[$index]); if($this->jobs->isCancelled($job->id)) return true; $result=$this->writer->write($job->createdBy,$questions); if($this->jobs->isCancelled($job->id)) return true; $job=$this->state($job,min(98,12+(int)floor((($index+1)/max(1,count($chunks)))*86)),count($pages),count($candidates),$job->extractedQuestions+count($questions),$job->classifiedQuestions+$result['classified'],$job->createdQuestions+$result['created'],$job->duplicateQuestions+$result['duplicates'],$job->failedQuestions+$result['failed'],$job->createdTaxonomySubjects+$result['createdSubjects'],'PROCESSING',null,$index+1); $this->jobs->save($job); }
            $this->jobs->save($this->state($job,100,count($pages),count($candidates),$job->extractedQuestions,$job->classifiedQuestions,$job->createdQuestions,$job->duplicateQuestions,$job->failedQuestions,$job->createdTaxonomySubjects,'COMPLETED',null,count($chunks)));
        } catch(\DomainException $exception) { $this->rescheduleOrFail($job,$exception); }
          catch(\Throwable $exception) { error_log('Question PDF job '.$job->id.': '.$exception::class.' '.$exception->getMessage()); $this->jobs->save($this->state($job,$job->progress,$job->pageCount,$job->candidatePages,$job->extractedQuestions,$job->classifiedQuestions,$job->createdQuestions,$job->duplicateQuestions,$job->failedQuestions,$job->createdTaxonomySubjects,'FAILED','Nao foi possivel processar este PDF.')); }
        return true;
    }
    private function rescheduleOrFail(QuestionPdfImportJob $job,\DomainException $exception):void { error_log('Question PDF job '.$job->id.': '.$exception::class.' '.$exception->getMessage()); $attempt=$job->retryCount+1; if($attempt>self::MAX_RETRIES){$this->jobs->save($this->state($job,$job->progress,$job->pageCount,$job->candidatePages,$job->extractedQuestions,$job->classifiedQuestions,$job->createdQuestions,$job->duplicateQuestions,$job->failedQuestions,$job->createdTaxonomySubjects,'FAILED','O provedor de IA permaneceu indisponivel apos novas tentativas.'));return;} $wait=min(15,2**($attempt-1));$next=(new \DateTimeImmutable('now'))->modify('+'.$wait.' minutes');$this->jobs->save($this->state($job,$job->progress,$job->pageCount,$job->candidatePages,$job->extractedQuestions,$job->classifiedQuestions,$job->createdQuestions,$job->duplicateQuestions,$job->failedQuestions,$job->createdTaxonomySubjects,'PENDING','Aguardando nova tentativa do provedor de IA.',null,$job->processedChunks,$attempt,$next)); }
    private function extract(array $pages):array { $evidence=[];foreach($pages as $page=>$text)$evidence[]=new SyllabusEvidence((int)$page,mb_substr($text,0,14000));$names=array_map(static fn($s)=>$s->name,$this->taxonomy->list(0,1000));$prompt='Retorne SOMENTE JSON válido, sem markdown: {"questions":[{"statement":"...","options":[{"content":"..."}],"board":"... ou null","exam":"... ou null","year":2024 ou null,"subject":"um assunto canônico da lista ou null","difficulty":"EASY|MEDIUM|HARD"}]}. Extraia exclusivamente questões objetivas completas presentes nas páginas. Preserve enunciado e alternativas, não invente gabarito. Identifique banca, concurso e ano apenas quando estiverem explicitamente impressos no bloco. Classifique pelo assunto mais específico desta lista canônica: '.implode(' | ',array_slice($names,0,700)).'. Ignore comentários, teoria, exercícios sem alternativas e gabaritos.';$raw=$this->ai->answer($prompt,$evidence)->content;$text=trim(preg_replace('/^\x60\x60\x60(?:json)?|\x60\x60\x60$/m','',$raw)??$raw);$data=json_decode($text,true);return is_array($data)&&is_array($data['questions']??null)?array_values(array_filter($data['questions'],static fn($q)=>is_array($q)&&is_string($q['statement']??null)&&is_array($q['options']??null))):[]; }
    private function hasQuestion(string $text):bool{return preg_match('/(?:quest.{0,3}o|\b\d{1,3}\s*[.)-])[^\n]{0,300}/iu',$text)===1&&preg_match_all('/(?:^|\n)\s*(?:\(?[A-Ea-e]\)|[A-Ea-e][.)])/u',$text)>1;}
    private function state(QuestionPdfImportJob $job,int $progress,int $pages,int $candidates,int $extracted=0,int $classified=0,int $created=0,int $duplicates=0,int $failed=0,int $newSubjects=0,string $status='PROCESSING',?string $error=null,?int $processedChunks=null,?int $retryCount=null,?\DateTimeImmutable $nextAttemptAt=null):QuestionPdfImportJob{return new QuestionPdfImportJob($job->id,$job->syllabusId,$job->createdBy,$job->documentPath,$job->documentSha256,$job->documentOriginalName,$status,$progress,$pages,$candidates,$processedChunks??$job->processedChunks,$retryCount??$job->retryCount,$nextAttemptAt,$extracted,$classified,$created,$duplicates,$failed,$newSubjects,$error,$job->createdAt,$job->startedAt,$status==='COMPLETED'||$status==='FAILED'?new \DateTimeImmutable('now'):null);}
}
