<?php
declare(strict_types=1);
namespace App\Infrastructure\Identity;
use App\Application\Identity\Port\GoogleJwksFetcherInterface;use App\Application\Identity\Port\GoogleOidcValidatorInterface;use App\Application\Identity\Port\VerifiedGoogleIdentity;
final class GoogleOidcValidator implements GoogleOidcValidatorInterface
{
    /** @var array{expiresAt:int,keys:array<string,array<string,mixed>>}|null */ private ?array $cache=null;
    private readonly GoogleJwksFetcherInterface $jwksFetcher;
    public function __construct(private readonly string $clientId,private readonly int $clockSkewSeconds=60,?GoogleJwksFetcherInterface $jwksFetcher=null){$this->jwksFetcher=$jwksFetcher??new GoogleJwksHttpFetcher();}
    public function validate(string $credential):VerifiedGoogleIdentity
    {if($this->clientId===''||strlen($credential)>12000)throw new \DomainException('Credencial Google inválida.');$parts=explode('.',$credential);if(count($parts)!==3)throw new \DomainException('Credencial Google inválida.');[$head,$body,$signature]=array_map(fn(string $part):string=>$this->decode($part),$parts);$header=json_decode($head,true);$claims=json_decode($body,true);if(!is_array($header)||!is_array($claims)||($header['alg']??null)!=='RS256'||!is_string($header['kid']??null))throw new \DomainException('Credencial Google inválida.');$key=$this->keys()[$header['kid']]??null;if(!is_array($key)||!$this->verify($parts[0].'.'.$parts[1],$signature,$key))throw new \DomainException('Credencial Google inválida.');$aud=$claims['aud']??null;$exp=$claims['exp']??null;if(!in_array($claims['iss']??null,['https://accounts.google.com','accounts.google.com'],true)||$aud!==$this->clientId||!is_int($exp)||$exp<(time()-$this->clockSkewSeconds)||($claims['email_verified']??false)!==true||!is_string($claims['email']??null))throw new \DomainException('Credencial Google inválida.');$name=is_string($claims['name']??null)?trim($claims['name']):'';$picture=is_string($claims['picture']??null)?$claims['picture']:null;return new VerifiedGoogleIdentity(mb_strtolower(trim($claims['email'])),$name===''?'Usuário Google':mb_substr($name,0,160),$picture);}
    /** @return array<string,array<string,mixed>> */ private function keys():array{if($this->cache!==null&&$this->cache['expiresAt']>time())return $this->cache['keys'];$keys=[];foreach($this->jwksFetcher->fetch() as $key)$keys[$key['kid']]=$key;$this->cache=['expiresAt'=>time()+3600,'keys'=>$keys];return$keys;}
    /** @param array<string,mixed> $key */ private function verify(string $input,string $signature,array $key):bool{$pem=$this->rsaPem((string)$key['n'],(string)$key['e']);return openssl_verify($input,$signature,$pem,OPENSSL_ALGO_SHA256)===1;}
    private function decode(string $value):string{$raw=base64_decode(strtr($value,'-_','+/').str_repeat('=',(4-strlen($value)%4)%4),true);if($raw===false)throw new \DomainException('Credencial Google inválida.');return$raw;}
    private function rsaPem(string $n,string $e):string{$modulus=$this->decode($n);if((ord($modulus[0])&128)!==0)$modulus="\0".$modulus;$rsa=$this->der(0x30,$this->der(0x02,$modulus).$this->der(0x02,$this->decode($e)));$algorithm="\x30\x0d\x06\x09\x2a\x86\x48\x86\xf7\x0d\x01\x01\x01\x05\x00";$sequence=$this->der(0x30,$algorithm.$this->der(0x03,"\0".$rsa));return"-----BEGIN PUBLIC KEY-----\n".chunk_split(base64_encode($sequence),64,"\n")."-----END PUBLIC KEY-----\n";}
    private function der(int $tag,string $value):string{$length=strlen($value);if($length<128)return chr($tag).chr($length).$value;$bytes=ltrim(pack('N',$length),"\0");return chr($tag).chr(128|strlen($bytes)).$bytes.$value;}
}
