<template><q-page class="page"><section class="head"><div><p class="eyebrow">DESCOBERTA CONTROLADA</p><h1>Provas e gabaritos</h1><p>Pesquise somente fontes permitidas e revise a proveniência antes de usar o material.</p></div></section><q-banner v-if="error" rounded class="error">{{error}}</q-banner><q-card flat class="search"><q-form class="form" @submit.prevent="run"><q-input v-model="query" outlined label="Consulta" placeholder="Ex.: concurso analista 2025"/><q-select v-model="type" outlined emit-value map-options label="Tipo" :options="types"/><q-btn unelevated no-caps color="primary" type="submit" label="Pesquisar" :loading="searching"/></q-form><p>Máximo de 10 candidatos; nenhum arquivo é baixado automaticamente.</p></q-card><q-inner-loading :showing="loading" color="primary"/><q-card v-if="resources.length" flat class="list"><q-list separator><q-item v-for="resource in resources" :key="resource.id"><q-item-section avatar><q-icon :name="resource.type==='EXAM'?'description':'fact_check'" color="primary"/></q-item-section><q-item-section><q-item-label>{{resource.title}}</q-item-label><q-item-label caption>{{resource.type==='EXAM'?'Prova':'Gabarito'}} · provider {{resource.provider}} · consulta: {{resource.queryText}}</q-item-label><q-item-label caption class="url">{{resource.sourceUrl}}</q-item-label></q-item-section><q-item-section side><q-btn flat round icon="open_in_new" type="a" :href="resource.sourceUrl" target="_blank" rel="noopener" aria-label="Abrir fonte"/></q-item-section></q-item></q-list></q-card><q-card v-else-if="!loading" flat class="empty"><q-card-section><q-icon name="travel_explore" size="38px" color="primary"/><div><h2>Nenhum candidato catalogado</h2><p>Configure um provider permitido e faça uma pesquisa administrativa.</p></div></q-card-section></q-card></q-page></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import type { DiscoveryResourceType } from '../../../Domain/Discovery/DiscoveryRepository'
import { useDiscovery } from './useDiscovery'
const { error, load, loading, resources, search, searching } = useDiscovery()
const query = ref('')
const type = ref<DiscoveryResourceType>('EXAM')
const types = [{ label: 'Provas', value: 'EXAM' }, { label: 'Gabaritos', value: 'ANSWER_KEY' }]
async function run(): Promise<void> { await search(query.value, type.value) }
onMounted(load)
</script>
<style scoped>.page{max-width:1100px;margin:auto;padding:42px 34px}.head h1,.empty h2{margin:0;color:#142950}.head p:not(.eyebrow),.search p,.empty p{color:#71819e}.eyebrow{margin:0 0 8px;color:#7187ad;font-size:11px;font-weight:800;letter-spacing:.1em}.search,.list,.empty{margin-top:24px;border:1px solid #e5ecf6;border-radius:18px;box-shadow:0 8px 26px rgba(33,58,105,.045)}.form{display:grid;grid-template-columns:1fr 190px auto;gap:12px;padding:20px}.search p{padding:0 20px 16px;margin:0;font-size:13px}.empty :deep(.q-card__section){display:flex;align-items:center;gap:16px;padding:36px}.url{word-break:break-all}.error{margin-top:18px;background:#fff3f2;color:#ae2f25}@media(max-width:650px){.page{padding:28px 16px}.form{grid-template-columns:1fr}.form .q-btn{width:100%}}</style>
