<template>
  <q-btn flat dense no-caps color="primary" icon="psychology" label="Estudar" @click="open" />
  <q-dialog v-model="visible" position="right" full-height>
    <q-card class="learning-panel">
      <q-card-section class="row items-center q-pb-none"><h2>Estudo da questão</h2><q-space/><q-btn flat round icon="close" aria-label="Fechar" @click="visible = false" /></q-card-section>
      <q-inner-loading :showing="loading" color="primary" />
      <q-banner v-if="error" rounded class="error q-ma-md">{{ error }}</q-banner>
      <q-tabs v-model="tab" dense align="justify" active-color="primary"><q-tab name="note" label="Anotação"/><q-tab name="comments" label="Comentários"/><q-tab name="report" label="Relatar"/><q-tab name="explanation" label="Explicação"/></q-tabs>
      <q-separator/>
      <q-tab-panels v-model="tab" animated><q-tab-panel name="note"><q-input v-model="note" outlined autogrow label="Sua anotação privada"/><q-btn class="q-mt-md" unelevated no-caps color="primary" label="Salvar anotação" :loading="saving" @click="saveNote"/></q-tab-panel><q-tab-panel name="comments"><q-list v-if="comments.length" separator><q-item v-for="comment in comments" :key="comment.id"><q-item-section><q-item-label>{{ comment.content }}</q-item-label><q-item-label caption>{{ formatDate(comment.createdAt) }}</q-item-label></q-item-section></q-item></q-list><p v-else class="empty">Ainda não há comentários.</p><q-input v-model="comment" outlined autogrow label="Comentário público" class="q-mt-md"/><q-btn class="q-mt-sm" unelevated no-caps color="primary" label="Publicar comentário" :loading="saving" @click="publishComment"/></q-tab-panel><q-tab-panel name="report"><q-select v-model="category" outlined emit-value map-options :options="categories" label="Tipo de problema"/><q-input v-model="description" outlined autogrow label="Descreva o problema" class="q-mt-md"/><q-btn class="q-mt-md" unelevated no-caps color="negative" label="Enviar relato" :loading="saving" @click="report"/></q-tab-panel><q-tab-panel name="explanation"><q-banner v-if="explanation?.status === 'PENDING' || explanation?.status === 'PROCESSING'" rounded class="pending">A explicação está sendo preparada. Atualize em alguns instantes.</q-banner><q-banner v-else-if="explanation?.status === 'FAILED'" rounded class="error">{{ explanation.errorMessage || 'Não foi possível preparar a explicação.' }}</q-banner><template v-else-if="explanation?.result"><p class="summary">{{ explanationSummary }}</p><pre class="explanation">{{ JSON.stringify(explanation.result, null, 2) }}</pre></template><p v-else class="empty">Solicite uma explicação conceitual, sem revelar a resposta.</p><div class="row q-gutter-sm q-mt-md"><q-btn unelevated no-caps color="primary" label="Solicitar explicação" :loading="saving" @click="requestExplanation"/><q-btn flat no-caps label="Atualizar" :loading="loading" @click="loadExplanation"/></div></q-tab-panel></q-tab-panels>
    </q-card>
  </q-dialog>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
import type { ProblemReportCategory, QuestionComment, QuestionExplanation } from '../../../Domain/QuestionLearning/QuestionLearningRepository'
import { questionLearningUseCases } from '../../../Infrastructure/Container'
const props = defineProps<{ readonly questionId: string }>()
const visible=ref(false), tab=ref('note'), loading=ref(false), saving=ref(false), error=ref(''), note=ref(''), comment=ref(''), comments=ref<readonly QuestionComment[]>([]), explanation=ref<QuestionExplanation|null>(null), category=ref<ProblemReportCategory>('CONTENT'), description=ref('')
const categories: readonly { readonly label:string; readonly value:ProblemReportCategory }[]=[{label:'Conteúdo',value:'CONTENT'},{label:'Gabarito',value:'ANSWER_KEY'},{label:'Imagem',value:'IMAGE'},{label:'Duplicada',value:'DUPLICATE'},{label:'Outro',value:'OTHER'}]
const explanationSummary=computed(()=>typeof explanation.value?.result?.summary==='string'?explanation.value.result.summary:'Explicação segura disponível.')
const formatDate=(value:string):string=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))
async function open():Promise<void>{visible.value=true;loading.value=true;error.value='';try{const [interaction,listed]=await Promise.all([questionLearningUseCases.interaction.execute(props.questionId),questionLearningUseCases.comments.execute(props.questionId)]);note.value=interaction.note?.content??'';comments.value=listed;await loadExplanation()}catch(reason){error.value=reason instanceof Error?reason.message:'Não foi possível carregar o painel de estudo.'}finally{loading.value=false}}
async function saveNote():Promise<void>{saving.value=true;error.value='';try{await questionLearningUseCases.saveNote.execute(props.questionId,note.value)}catch(reason){error.value=reason instanceof Error?reason.message:'Não foi possível salvar a anotação.'}finally{saving.value=false}}
async function publishComment():Promise<void>{saving.value=true;error.value='';try{const created=await questionLearningUseCases.createComment.execute(props.questionId,{content:comment.value});comments.value=[...comments.value,created];comment.value=''}catch(reason){error.value=reason instanceof Error?reason.message:'Não foi possível publicar o comentário.'}finally{saving.value=false}}
async function report():Promise<void>{saving.value=true;error.value='';try{await questionLearningUseCases.reportProblem.execute(props.questionId,{category:category.value,description:description.value});description.value='';tab.value='note'}catch(reason){error.value=reason instanceof Error?reason.message:'Não foi possível enviar o relato.'}finally{saving.value=false}}
async function loadExplanation():Promise<void>{try{explanation.value=await questionLearningUseCases.latestExplanation.execute(props.questionId)}catch(reason){const code=(reason as { code?:string }).code;if(code!=='RESOURCE_NOT_FOUND') error.value=reason instanceof Error?reason.message:'Não foi possível consultar a explicação.'; else explanation.value=null}}
async function requestExplanation():Promise<void>{saving.value=true;error.value='';try{explanation.value=await questionLearningUseCases.requestExplanation.execute(props.questionId)}catch(reason){error.value=reason instanceof Error?reason.message:'Não foi possível solicitar a explicação.'}finally{saving.value=false}}
</script>
<style scoped>
.learning-panel{width:min(520px,100vw);height:100%;border-radius:20px 0 0 20px}.learning-panel h2{margin:0;color:#142950;font-size:20px}.empty{color:#71819e}.error{background:#fff2f1;color:#a7332c}.pending{background:#edf5ff;color:#245aab}.summary{font-weight:700;color:#193a6a}.explanation{white-space:pre-wrap;overflow:auto;border-radius:12px;background:#f5f8fd;padding:12px;font-size:12px}@media(max-width:599px){.learning-panel{width:100vw;border-radius:0}.learning-panel :deep(.q-tab){font-size:10px;padding:0 5px}}
</style>
