<template><q-page class="page"><p class="eyebrow">ADMINISTRAÇÃO</p><div class="heading"><div><h1>Auditoria de questões</h1><p>Última execução determinística. Nenhuma correção é aplicada nesta tela.</p></div><q-btn outline no-caps color="primary" icon="refresh" label="Atualizar" :loading="loading" @click="() => load()"/></div><q-banner v-if="error" rounded class="error">{{ error }}</q-banner><q-inner-loading :showing="loading" color="primary"/><q-card v-if="report" flat class="report"><q-card-section><div class="meta"><q-badge color="primary" :label="statusLabel(report.status)"/><span>Algoritmo {{ report.algorithmVersion }}</span><span>Concluída: {{ format(report.finishedAt ?? report.createdAt) }}</span></div><h2>{{ report.scope === 'PUBLISHED' ? 'Questões publicadas' : report.scope }}</h2><div class="summary"><div v-for="(count, status) in report.summary" :key="status" class="metric"><strong>{{ count }}</strong><span>{{ label(status) }}</span></div></div><p v-if="report.errorMessage" class="failure">{{ report.errorMessage }}</p></q-card-section></q-card><q-card v-if="findings" flat class="findings"><q-card-section><div class="findings-head"><h2>Achados ({{ findings.total }})</h2><span>Página {{ findings.page }} de {{ findings.totalPages }}</span></div><q-list bordered separator><q-item v-for="finding in findings.items" :key="finding.id"><q-item-section><q-item-label><q-badge color="primary" :label="label(finding.code)"/> <q-badge outline color="grey-7" :label="finding.confidence"/></q-item-label><q-item-label caption>{{ finding.message }}</q-item-label><q-item-label v-if="finding.structureAfter?.rendering" caption>Proposta de apresentação: {{ finding.structureAfter.rendering }}</q-item-label><q-item-label caption>Questão {{ finding.questionId }} · PDF {{ finding.sourcePdfJobId ?? "não informado" }} · página {{ finding.sourcePage ?? "não informada" }} · {{ label(finding.status) }}</q-item-label></q-item-section></q-item></q-list><q-pagination v-if="findings.totalPages > 1" class="pagination" :model-value="findings.page" :max="findings.totalPages" direction-links boundary-links @update:model-value="goTo"/></q-card-section></q-card><q-card v-else-if="!loading" flat class="empty"><q-card-section>Nenhum relatório de auditoria disponível.</q-card-section></q-card></q-page></template>
<script setup lang="ts">
import { onMounted } from 'vue'
import { useQuestionAudit } from './useQuestionAudit'
const { error, findings, goTo, load, loading, report } = useQuestionAudit(); const format = (value:string):string => new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)); const label=(value:string):string=>value.toLowerCase().replace(/_/g,' '); const statusLabel=(value:string):string=>value==='COMPLETED'?'Concluída':value==='FAILED'?'Falhou':'Em processamento'; onMounted(load)
</script>
<style scoped>
.page{max-width:1080px;margin:auto;padding:42px 34px}.eyebrow{margin:0 0 7px;color:#7187ad;font-size:11px;font-weight:800;letter-spacing:.1em}.heading{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:22px}.heading h1{margin:0;color:#142950;font-size:32px}.heading p{margin:8px 0 0;color:#71819e}.report,.empty{border:1px solid #e5ecf6;border-radius:17px;background:#fff;box-shadow:0 8px 26px rgba(33,58,105,.04)}.meta{display:flex;flex-wrap:wrap;gap:10px;align-items:center;color:#71819e;font-size:13px}.report h2{margin:24px 0 14px;color:#1b315a;font-size:19px}.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.metric{padding:16px;border-radius:13px;background:#f5f8fe}.metric strong,.metric span{display:block}.metric strong{color:#1d62bf;font-size:28px}.metric span{margin-top:5px;color:#5b7092;font-size:12px;text-transform:capitalize}.findings{margin-top:18px;border:1px solid #e5ecf6;border-radius:17px}.findings h2{margin:0;color:#1b315a;font-size:19px}.findings-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px;color:#71819e;font-size:13px}.findings .q-item{padding:12px 0}.pagination{display:flex;justify-content:center;margin-top:16px}.failure,.error{color:#ae2f25}.error{margin-bottom:16px;background:#fff3f2}@media(max-width:660px){.page{padding:28px 16px}.heading{flex-direction:column}.heading h1{font-size:27px}}
</style>
