<template>
  <q-page class="page">
    <section class="top"><div><p class="eyebrow">BANCO PUBLICADO</p><h1 class="page-title">Questões</h1><p>Explore itens disponíveis para seus próximos cadernos.</p></div><q-btn flat no-caps color="primary" label="Limpar filtros" @click="clear" /></section>
    <q-card flat class="filters"><q-card-section class="filter-grid"><q-input v-model="filters.content" outlined dense clearable label="Pesquisar no conteúdo" placeholder="Enunciado ou alternativa" @keyup.enter="search"><template #prepend><q-icon name="search" /></template></q-input><q-input v-model="filters.board" outlined dense label="Banca" @keyup.enter="search" /><q-input v-model.number="filters.year" outlined dense type="number" label="Ano" @keyup.enter="search" /><q-select v-model="filters.difficulty" clearable outlined dense label="Dificuldade" :options="difficultyOptions" emit-value map-options /><q-btn unelevated no-caps color="primary" label="Filtrar" :loading="loading" @click="search" /></q-card-section></q-card>
    <q-banner v-if="error" rounded class="error">{{ error }}</q-banner>
    <p class="results">{{ total }} {{ total === 1 ? 'questão encontrada' : 'questões encontradas' }}</p>
    <q-inner-loading :showing="loading" color="primary" />
    <section v-if="questions.length" class="question-results"><q-card v-for="(question, index) in questions" :key="question.id" flat class="question-workspace"><q-card-section><div class="question-meta"><strong>Questão {{ (page - 1) * perPage + index + 1 }}</strong><q-badge rounded color="amber-2" text-color="amber-10">{{ difficulty(question.difficulty) }}</q-badge><q-chip v-if="question.board" dense color="blue-1" text-color="primary">{{ question.board }}{{ question.year ? " · " + question.year : "" }}</q-chip><q-badge v-if="question.answerKeySource === 'AI_ESTIMATED'" color="warning" text-color="dark" label="Gabarito estimado por IA"/></div><div v-if="question.assetUrls?.length" class="question-assets"><QuestionAssetImage v-for="url in question.assetUrls" :key="url" :url="url"/></div><div class="question-statement"><QuestionContent :value="question.statement"/></div><div class="question-options" role="list" aria-label="Alternativas"><div v-for="option in question.options" :key="option.id" class="option-card" role="listitem"><q-icon name="radio_button_unchecked"/><strong>{{ option.label }}.</strong><QuestionContent :value="option.content"/><div v-if="option.assetUrls?.length" class="option-assets"><QuestionAssetImage v-for="url in option.assetUrls" :key="url" :url="url"/></div></div></div></q-card-section></q-card></section>
    <div v-if="total > perPage" class="pagination"><q-pagination :model-value="page" :max="Math.ceil(total / perPage)" :max-pages="7" color="primary" boundary-numbers @update:model-value="goTo" /></div>
    <q-card v-if="!loading && !questions.length" flat class="empty"><q-card-section><q-img src="/images/concursos-study-mark.png" width="84px" height="84px" fit="contain" /><div><h2>Nenhuma questão para estes filtros</h2><p>Tente remover filtros ou peça a inclusão de questões publicadas.</p></div></q-card-section></q-card>
  </q-page>
</template>
<script setup lang="ts">
import { onMounted, reactive } from 'vue'
import QuestionAssetImage from './QuestionAssetImage.vue'
import QuestionContent from './QuestionContent.vue'
import type { QuestionDifficulty } from '../../../Domain/QuestionBank/QuestionRepository'
import { useQuestions } from './useQuestions'
const { error, goTo, load, loading, page, perPage, questions, total } = useQuestions()
const filters = reactive<{ content: string; board: string; year: number | null; difficulty: QuestionDifficulty | null }>({ content: '', board: '', year: null, difficulty: null })
const difficultyOptions = [{ label: 'Fácil', value: 'EASY' }, { label: 'Média', value: 'MEDIUM' }, { label: 'Difícil', value: 'HARD' }]
function search(): Promise<void> { return load({ ...(filters.content.trim() ? { content: filters.content.trim() } : {}), ...(filters.board.trim() ? { board: filters.board.trim() } : {}), ...(filters.year ? { year: filters.year } : {}), ...(filters.difficulty ? { difficulty: filters.difficulty } : {}) }) }
function clear(): void { filters.content = ''; filters.board = ''; filters.year = null; filters.difficulty = null; void search() }
function difficulty(value: QuestionDifficulty): string { return ({ EASY: 'Fácil', MEDIUM: 'Média', HARD: 'Difícil' })[value] }
onMounted(search)
</script>
<style scoped>
.page{max-width:1050px;margin:auto;padding:42px 34px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:23px}.eyebrow{margin:0 0 7px;color:#7187ad;font-size:11px;font-weight:800;letter-spacing:.1em}.top h1{margin:0;color:#142950;font-size:32px}.top p:not(.eyebrow){margin:8px 0 0;color:#71819e}.filters,.questions,.empty{border:1px solid #e5ecf6;border-radius:17px;background:#fff;box-shadow:0 8px 26px rgba(33,58,105,.04)}.filter-grid{display:grid;grid-template-columns:1.7fr 1.2fr .7fr 1fr auto;gap:12px}.filters .q-btn{border-radius:9px}.results{color:#72829d;font-size:13px;margin:20px 0 10px}.questions{overflow:hidden}.question-results{display:grid;gap:16px}.question-workspace{border:0!important;border-radius:26px!important;background:rgba(255,255,255,.94)!important;box-shadow:0 18px 45px rgba(35,70,128,.12)!important}.question-workspace :deep(.q-card__section){padding:18px}.question-meta{display:flex;align-items:center;gap:9px;padding-bottom:12px;border-bottom:1px solid #e1eaf7;color:#10275b;font-size:13px}.question-meta :deep(.q-chip){margin:0;font-size:10px}.question-assets{display:grid;gap:12px;margin:16px 0}.question-assets :deep(img),.option-assets :deep(img){max-width:100%;max-height:520px;object-fit:contain;border:1px solid #dce6f3;border-radius:10px}.question-statement{margin:17px 0 14px;color:#10275b;font-size:15px;font-weight:600;line-height:1.48}.question-options{display:grid;gap:7px}.option-card{display:flex;align-items:flex-start;gap:10px;width:100%;min-height:42px;padding:10px 12px;border:1px solid #dce6f3;border-radius:13px;background:#f6f9fd;color:#344e77;text-align:left}.option-card :deep(.content){flex:1;font-size:12px;line-height:1.36}.option-assets{width:100%}.number{color:#2b6ed2;font-size:10px;font-weight:800;letter-spacing:.1em}.statement{margin:8px 0;color:#1b315a;font-size:16px;line-height:1.5}.question-content{margin:12px 0;color:#1b315a}.assets{display:grid;gap:12px;margin:12px 0}.assets :deep(img),.option-assets :deep(img){max-width:100%;max-height:430px;object-fit:contain;border:1px solid #dce6f4;border-radius:10px}.option{display:flex;align-items:flex-start;gap:9px;padding:10px 13px;margin:8px 0;border-radius:10px;background:#f7f9fd;color:#405174}.option :deep(.content){flex:1}.option-assets{width:100%}.empty :deep(.q-card__section){display:flex;align-items:center;gap:22px;padding:32px}.empty h2{margin:0;color:#1a315a;font-size:19px}.empty p{color:#71819e}.pagination{display:flex;justify-content:center;margin:22px 0}.error{margin-top:15px;background:#fff3f2;color:#ae2f25}@media(max-width:660px){.page{padding:28px 16px}.top{align-items:flex-start;flex-direction:column}.filter-grid{grid-template-columns:1fr}.filters .q-btn{height:42px}.empty :deep(.q-card__section){align-items:flex-start;flex-direction:column}}

/* Banco: leitura de questões em página fluida, com filtros em uma faixa discreta. */
.page{max-width:1240px!important}.top{padding:9px 0 23px;border-bottom:1px solid #dce7f6}.filters{border-radius:18px!important;background:rgba(255,255,255,.72)!important}.question-card{border-radius:22px!important;background:rgba(255,255,255,.84)!important}.question-card:hover{transform:translateY(-2px);box-shadow:0 15px 34px rgba(37,71,126,.10)!important}.empty{border-radius:24px!important;background:linear-gradient(145deg,#fff,#eef6ff)!important}
</style>
