<?php
declare(strict_types=1);
namespace App\Application\Arena\Service;
use App\Application\Performance\Port\TransactionManagerInterface;
use App\Domain\Arena\Entity\Duel;
use App\Domain\Arena\Enum\DuelVisibility;
use App\Domain\Arena\Repository\DuelQuestionSelectorInterface;
use App\Domain\Arena\Repository\DuelRepositoryInterface;
final class DuelLifecycleService {
 public function __construct(private readonly DuelRepositoryInterface $duels,private readonly DuelQuestionSelectorInterface $questions,private readonly TransactionManagerInterface $transactions,private readonly \DateTimeZone $utc=new \DateTimeZone('UTC')){}
 public function create(string $userId,int $max,int $subjects,int $count,int $seconds,string $visibility="PRIVATE"):Duel{$visibility=DuelVisibility::tryFrom($visibility)??throw new DomainException("Visibilidade inválida.");return $this->transactions->transactional(function()use($userId,$max,$subjects,$count,$seconds,$visibility){$d=new Duel($this->uuid(),$this->code(),$userId,$max,$subjects,$count,$seconds,$this->now(),visibility:$visibility);$this->duels->save($d);$this->duels->addParticipant($d->id,$userId,$d->createdAt);return$d;});}
 public function join(string $code,string $userId):Duel{return $this->transactions->transactional(function()use($code,$userId){$d=$this->duels->findByCode($code);if(!$d)throw new \DomainException('Sala não encontrada.');if($d->status->value!=='WAITING'||$this->duels->participantCount($d->id)>=$d->maxPlayers)throw new \DomainException('Sala indisponível.');$this->duels->addParticipant($d->id,$userId,$this->now());return $this->duels->findForParticipant($d->id,$userId)??throw new \LogicException();});}
 public function joinPublic(string $id,string $userId):Duel{return $this->transactions->transactional(function()use($id,$userId){$d=$this->duels->findPublicWaiting($id);if(!$d||$this->duels->participantCount($d->id)>=$d->maxPlayers)throw new DomainException("Sala indisponível.");$this->duels->addParticipant($d->id,$userId,$this->now());return $this->duels->findForParticipant($d->id,$userId)??throw new ogicexception();});}
 public function ready(string $id,string $userId,array $subjects):Duel{return $this->transactions->transactional(function()use($id,$userId,$subjects){$d=$this->duels->findForParticipant($id,$userId);if(!$d||$d->status->value!=='WAITING')throw new \DomainException('Sala não aceita escolhas.');$subjects=array_values(array_unique($subjects));if(count($subjects)!==$d->subjectsPerPlayer)throw new \DomainException('Quantidade de assuntos inválida.');$this->duels->replaceParticipantSubjects($id,$userId,$subjects,$this->now());if($this->duels->participantCount($id)===$this->duels->readyParticipantCount($id)){$ids=$this->questions->selectPublishedBalanced($this->duels->participantSubjectIds($id),$this->duels->recentQuestionIdsForParticipants($id),$d->questionCount);if(count($ids)!==$d->questionCount)throw new \DomainException('Não há questões publicadas suficientes.');$this->duels->freezeQuestions($id,$ids);}return $this->duels->findForParticipant($id,$userId)??throw new \LogicException();});}
 public function start(string $id,string $userId):Duel{return $this->transactions->transactional(function()use($id,$userId){$d=$this->duels->findForParticipant($id,$userId);if(!$d||$d->creatorUserId!==$userId||$this->duels->participantCount($id)!==$this->duels->readyParticipantCount($id))throw new \DomainException('Duelo não pode iniciar.');$d->openQuestion($this->now());$this->duels->save($d);return$d;});}
 private function now():\DateTimeImmutable{return new \DateTimeImmutable('now',$this->utc);} private function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));} private function code():string{return strtoupper(substr(bin2hex(random_bytes(4)),0,6));}
}
