<template>
  <q-page class="page">
    <section class="top"><div><p class="eyebrow">ADMINISTRAÇÃO</p><h1 class="page-title">Catálogo</h1><p>Organize concursos, cargos, editais, assuntos e tags.</p></div><q-btn unelevated no-caps color="primary" icon="add" label="Novo concurso" @click="openCreate" /></section>
    <q-banner v-if="error" rounded class="error">{{ error }}</q-banner>
    <q-card flat class="catalog-card">
      <q-tabs v-model="tab" dense align="left" active-color="primary" indicator-color="primary" class="catalog-tabs"><q-tab name="contests" icon="workspace_premium" label="Concursos" /><q-tab name="positions" icon="badge" label="Cargos" /><q-tab name="notices" icon="description" label="Editais" /><q-tab name="subjects" icon="category" label="Assuntos" /><q-tab name="tags" icon="sell" label="Tags" /></q-tabs><q-separator />
      <q-card-section>
        <template v-if="tab === 'contests'"><div class="filters"><q-input v-model="filter" dense outlined placeholder="Buscar concursos..." clearable><template #prepend><q-icon name="search" /></template></q-input></div><q-table flat :rows="filteredExams" :columns="columns" row-key="id" :loading="loading" hide-bottom :pagination="{ rowsPerPage: 25 }" no-data-label="Nenhum concurso cadastrado."><template #body-cell-name="props"><q-td :props="props"><div class="contest-cell"><div class="brand-tile institution-brand"><q-img v-if="props.row.institutionLogoUrl" :src="props.row.institutionLogoUrl" :alt="'Logo da instituição ' + props.row.name" fit="contain" no-spinner /><q-icon v-else name="workspace_premium" size="22px" color="primary" /></div><div><div class="contest-name">{{ props.row.name }}</div><div class="brand-caption">Instituição</div></div></div></q-td></template><template #body-cell-organizer="props"><q-td :props="props"><div class="contest-cell"><div class="brand-tile board-brand"><q-img v-if="props.row.organizerLogoUrl" :src="props.row.organizerLogoUrl" :alt="'Logo da banca ' + (props.row.organizer || 'organizadora')" fit="contain" no-spinner /><q-icon v-else name="account_balance" size="20px" color="primary" /></div><div><div class="board-name">{{ props.row.organizer || 'Organizadora não informada' }}</div><div class="brand-caption">{{ props.row.year ? 'Ano ' + props.row.year : 'Ano não informado' }}</div></div></div></q-td></template><template #body-cell-actions="props"><q-td :props="props"><q-btn flat round dense color="primary" icon="visibility" @click="manage(props.row)"><q-tooltip>Gerenciar concurso</q-tooltip></q-btn><q-btn flat round dense color="primary" icon="edit" @click="openEdit(props.row)"><q-tooltip>Editar concurso</q-tooltip></q-btn></q-td></template></q-table></template>
        <template v-else-if="tab === 'tags'"><section class="section-head"><div><h2>Tags</h2><p>Classificações globais reutilizáveis.</p></div></section><div class="inline-create"><q-input v-model="tagName" dense outlined label="Nova tag" @keyup.enter="saveTag" /><q-btn unelevated no-caps color="primary" label="Adicionar" :loading="saving" @click="saveTag" /></div><div v-if="tags.length" class="chips"><q-chip v-for="tag in tags" :key="tag.id" color="blue-1" text-color="primary">{{ tag.name }}</q-chip></div><EmptyState v-else icon="sell" text="Nenhuma tag cadastrada." /></template>
        <template v-else><div class="context"><q-select v-model="selectedExamId" dense outlined emit-value map-options option-value="value" option-label="label" :options="examOptions" label="Concurso selecionado" @update:model-value="loadContext" /><q-banner v-if="selectedExam" rounded class="context-note"><q-icon name="workspace_premium" color="primary" /> Você está gerenciando: <strong>{{ selectedExam.name }}</strong><span v-if="selectedExam.organizer"> · {{ selectedExam.organizer }}</span></q-banner></div>
          <EmptyState v-if="!selectedExamId" icon="touch_app" text="Selecione um concurso para ver somente os dados relacionados a ele." />
          <template v-else-if="tab === 'positions'"><section class="section-head"><div><h2>Cargos</h2><p>Cargos vinculados exclusivamente ao concurso selecionado.</p></div></section><div class="inline-create"><q-input v-model="positionName" dense outlined label="Novo cargo" @keyup.enter="savePosition" /><q-btn unelevated no-caps color="primary" label="Adicionar cargo" :loading="saving" @click="savePosition" /></div><q-list v-if="positions.length" bordered separator class="resource-list"><q-item v-for="position in positions" :key="position.id"><q-item-section avatar><q-icon name="badge" color="primary" /></q-item-section><q-item-section><q-item-label>{{ position.name }}</q-item-label><q-item-label caption>{{ position.emphasis || 'Sem ênfase informada' }}</q-item-label></q-item-section><q-item-section side><q-btn flat dense no-caps color="primary" icon="account_tree" label="Assuntos" @click="openPositionSubjects(position.id)" /></q-item-section></q-item></q-list><EmptyState v-else icon="badge" text="Nenhum cargo neste concurso." /></template>
          <template v-else-if="tab === 'notices'"><section class="section-head"><div><h2>Editais</h2><p>Crie um edital e anexe o PDF quando ele estiver disponível. O envio não inicia análise automaticamente.</p></div></section><div class="inline-create"><q-input v-model="syllabusName" dense outlined label="Nome do edital" @keyup.enter="saveSyllabus" /><q-btn unelevated no-caps color="primary" label="Novo edital" :loading="saving" @click="saveSyllabus" /></div><q-list v-if="syllabi.length" bordered separator class="resource-list"><q-item v-for="item in syllabi" :key="item.id"><q-item-section avatar><q-icon name="picture_as_pdf" :color="item.documentSha256 ? 'negative' : 'primary'" /></q-item-section><q-item-section><q-item-label>{{ item.name }}</q-item-label><q-item-label caption>{{ item.documentOriginalName || 'Nenhum PDF anexado' }}</q-item-label></q-item-section><q-item-section side class="notice-actions"><q-file v-model="noticeFiles[item.id]" dense outlined accept="application/pdf,.pdf" label="PDF" style="min-width:190px" /><q-btn unelevated no-caps color="primary" label="Enviar" :disable="!noticeFiles[item.id]" :loading="saving" @click="sendNotice(item.id)" /></q-item-section></q-item></q-list><EmptyState v-else icon="description" text="Nenhum edital neste concurso." /></template>
          <template v-else><section class="section-head"><div><h2>Assuntos</h2><p>Assuntos pertencem a um edital. Selecione-o antes de consultar ou incluir.</p></div></section><q-select v-model="selectedSyllabusId" dense outlined emit-value map-options option-value="value" option-label="label" :options="syllabusOptions" label="Edital" @update:model-value="loadSubjects" /><template v-if="selectedSyllabusId"><div class="inline-create subject-create"><q-input v-model="subjectName" dense outlined label="Novo assunto" @keyup.enter="saveSubject" /><q-btn unelevated no-caps color="primary" label="Adicionar assunto" :loading="saving" @click="saveSubject" /></div><q-list v-if="subjects.length" bordered separator class="resource-list"><q-item v-for="subject in subjects" :key="subject.id"><q-item-section avatar><q-icon name="category" color="primary" /></q-item-section><q-item-section><q-item-label>{{ subject.name }}</q-item-label><q-item-label caption>{{ subject.sourcePage ? 'Página ' + subject.sourcePage + ' do edital' : 'Assunto cadastrado manualmente' }}</q-item-label><div class="weight-meta"><q-chip dense square color="blue-1" text-color="primary">Peso {{ Number(subject.selectionWeight).toFixed(2) }}</q-chip><q-chip dense square :color="subject.weightSource === 'EDITAL' ? 'positive' : subject.weightSource === 'HISTORICAL' ? 'amber-2' : 'grey-3'" :text-color="subject.weightSource === 'EDITAL' ? 'white' : 'dark'">{{ weightSourceLabel(subject.weightSource) }} · {{ Math.round(subject.weightConfidence * 100) }}%</q-chip></div></q-item-section></q-item></q-list><EmptyState v-else icon="category" text="Nenhum assunto neste edital." /></template><EmptyState v-else icon="description" text="Selecione um edital para ver seus assuntos." /></template>
        </template>
      </q-card-section>
    </q-card>
    <q-dialog v-model="positionSubjectsDialog" persistent><q-card class="form-dialog"><q-card-section><div class="dialog-title">Assuntos do cargo</div><p>Somente estes assuntos poderão compor cadernos e simulados deste cargo.</p></q-card-section><q-card-section><q-select v-model="selectedPositionSubjectIds" outlined multiple use-chips emit-value map-options :options="taxonomyOptions" label="Assuntos canônicos" /></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup /><q-btn unelevated no-caps color="primary" label="Salvar assuntos" :loading="saving" @click="savePositionSubjects" /></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="dialog" persistent><q-card class="form-dialog"><q-card-section><div class="dialog-title">{{ editing ? 'Editar concurso' : 'Novo concurso' }}</div><p>{{ editing ? 'Atualize os dados do concurso.' : 'Cadastre o concurso e anexe o edital agora ou posteriormente.' }}</p></q-card-section><q-card-section class="form"><q-input v-model="name" dense outlined label="Nome do concurso *" autofocus /><div class="form-row"><q-input v-model="organizer" dense outlined label="Organizadora" /><q-input v-model.number="year" dense outlined type="number" label="Ano" /></div><q-file v-if="!editing" v-model="document" dense outlined accept="application/pdf,.pdf" label="PDF do edital (opcional)" clearable><template #prepend><q-icon name="picture_as_pdf" /></template></q-file></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup /><q-btn unelevated no-caps color="primary" :label="editing ? 'Salvar alterações' : 'Cadastrar concurso'" :loading="saving" @click="submit" /></q-card-actions></q-card></q-dialog>
  </q-page>
</template>
<script setup lang="ts">
import { computed, defineComponent, h, onMounted, ref } from 'vue'
import type { QTableColumn } from 'quasar'
import type { Exam } from '../../../Domain/Catalog/CatalogRepository'
import { useCatalog } from './useCatalog'
const EmptyState = defineComponent({ props: { icon: { type: String, required: true }, text: { type: String, required: true } }, setup: (props) => () => h('div', { class: 'empty-state' }, [h('q-icon', { name: props.icon, size: '30px', color: 'primary' }), h('p', props.text)]) })
const { assignPositionTaxonomySubjects, createExamWithNotice, createPosition, createSubject, createSyllabus, createTag, error, exams, loadExams, chooseExam, choosePosition, chooseSyllabus, loading, loadTaxonomyOptions, positionTaxonomySubjectIds, positions, saving, subjects, syllabi, tags, taxonomyOptions, updateExam, uploadSyllabusDocument } = useCatalog()
const positionSubjectsDialog = ref(false); const selectedPositionId = ref(''); const selectedPositionSubjectIds = ref<string[]>([]);
const tab = ref('contests'); const filter = ref(''); const dialog = ref(false); const editing = ref(false); const selectedExamId = ref(''); const selectedSyllabusId = ref(''); const name = ref(''); const organizer = ref(''); const year = ref<number | null>(null); const document = ref<File | null>(null); const positionName = ref(''); const syllabusName = ref(''); const subjectName = ref(''); const tagName = ref(''); const noticeFiles = ref<Record<string, File | null>>({})
const columns: QTableColumn[] = [{ name: 'name', label: 'Concurso', field: 'name', align: 'left', sortable: true }, { name: 'organizer', label: 'Banca organizadora', field: 'organizer', align: 'left' }, { name: 'actions', label: 'Ações', field: () => '', align: 'right' }]
const filteredExams = computed(() => { const term = filter.value.trim().toLocaleLowerCase(); return term ? exams.value.filter((item) => [item.name, item.organizer || '', String(item.year || '')].join(' ').toLocaleLowerCase().includes(term)) : exams.value })
const examOptions = computed(() => exams.value.map((item) => ({ value: item.id, label: item.name + (item.year ? ' · ' + item.year : '') })))
const syllabusOptions = computed(() => syllabi.value.map((item) => ({ value: item.id, label: item.name })))
const selectedExam = computed(() => exams.value.find((item) => item.id === selectedExamId.value) || null)
function resetForm(): void { name.value = ''; organizer.value = ''; year.value = null; document.value = null; editing.value = false }
function openCreate(): void { resetForm(); dialog.value = true }
function openEdit(exam: Exam): void { editing.value = true; name.value = exam.name; organizer.value = exam.organizer || ''; year.value = exam.year; selectedExamId.value = exam.id; dialog.value = true }
async function manage(exam: Exam): Promise<void> { selectedExamId.value = exam.id; selectedSyllabusId.value = ''; await loadContext(); tab.value = 'notices' }
async function loadContext(): Promise<void> { selectedSyllabusId.value = ''; await chooseExam(selectedExamId.value) }
async function loadSubjects(): Promise<void> { if (selectedSyllabusId.value) await chooseSyllabus(selectedSyllabusId.value) }
async function submit(): Promise<void> { if (editing.value && selectedExamId.value) { if (!await updateExam(selectedExamId.value, name.value, organizer.value, year.value)) return } else { const created = await createExamWithNotice(name.value, organizer.value, year.value, document.value); if (!created) return; selectedExamId.value = created.id } dialog.value = false; resetForm(); await loadContext() }
async function openPositionSubjects(positionId:string): Promise<void> { await Promise.all([choosePosition(positionId), loadTaxonomyOptions()]); selectedPositionId.value = positionId; selectedPositionSubjectIds.value = [...positionTaxonomySubjectIds.value]; positionSubjectsDialog.value = true }
async function savePositionSubjects(): Promise<void> { if (selectedPositionId.value && await assignPositionTaxonomySubjects(selectedPositionId.value, selectedPositionSubjectIds.value)) positionSubjectsDialog.value = false }
async function savePosition(): Promise<void> { if (selectedExamId.value && await createPosition(selectedExamId.value, positionName.value)) positionName.value = '' }
async function saveSyllabus(): Promise<void> { if (selectedExamId.value && await createSyllabus(selectedExamId.value, syllabusName.value)) syllabusName.value = '' }
async function sendNotice(id: string): Promise<void> { const file = noticeFiles.value[id]; if (file && selectedExamId.value && await uploadSyllabusDocument(id, selectedExamId.value, file)) noticeFiles.value[id] = null }
function weightSourceLabel(source:string):string { return ({ EDITAL:'Edital', HISTORICAL:'Histórico', AI_ESTIMATED:'IA estimada', DEFAULT:'Padrão' } as Record<string,string>)[source] ?? source }
async function saveSubject(): Promise<void> { if (selectedSyllabusId.value && await createSubject(selectedSyllabusId.value, subjectName.value, {})) subjectName.value = '' }
async function saveTag(): Promise<void> { if (await createTag(tagName.value)) tagName.value = '' }
onMounted(loadExams)
</script>
<style scoped>
.page{max-width:1080px;margin:auto;padding:40px 34px}.top{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:24px}.eyebrow{margin:0 0 6px;color:#7187ad;font-size:11px;font-weight:800;letter-spacing:.1em}.top h1{margin:0;color:#142950;font-size:32px}.top p:not(.eyebrow){margin:7px 0 0;color:#71819e}.catalog-card{overflow:hidden;border:1px solid #e5ecf6;border-radius:15px;background:#fff;box-shadow:0 8px 26px rgba(33,58,105,.04)}.catalog-tabs{min-height:52px}.filters,.inline-create{display:flex;gap:10px;margin-bottom:16px}.filters .q-field,.inline-create .q-field{flex:1}.contest-cell{display:flex;align-items:center;gap:12px;min-height:52px}.brand-tile{display:grid;place-items:center;flex:0 0 44px;width:44px;height:44px;padding:6px;border:1px solid #dbe7f8;border-radius:12px;background:#fff;box-shadow:0 3px 10px rgba(35,74,129,.08);overflow:hidden}.board-brand{flex-basis:38px;width:38px;height:38px;padding:5px;border-radius:10px;background:#f8fbff}.brand-tile .q-img{width:100%;height:100%}.contest-name,.board-name{font-size:14px;line-height:20px;font-weight:750;color:#18325c}.brand-caption{margin-top:2px;color:#7586a4;font-size:11px;line-height:15px}.error{margin-bottom:14px;background:#fff3f2;color:#ae2f25}.context{display:grid;grid-template-columns:minmax(240px,420px) 1fr;gap:14px;align-items:center;margin-bottom:18px}.context-note{background:#eef6ff;color:#38547b}.section-head{margin-bottom:16px}.section-head h2{margin:0;color:#18325c;font-size:20px}.section-head p{margin:5px 0 0;color:#71819e;font-size:13px}.resource-list{border-radius:10px}.notice-actions{display:flex;flex-direction:row;align-items:center;gap:8px}.chips{display:flex;flex-wrap:wrap;gap:8px}.empty-state{min-height:180px;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#71819e;text-align:center}.empty-state p{margin:9px 0 0}.form-dialog{width:min(520px,calc(100vw - 32px));border-radius:16px}.dialog-title{color:#142950;font-size:21px;font-weight:800}.form-dialog p{margin:7px 0 0;color:#71819e;font-size:13px}.form{display:grid;gap:14px}.form-row{display:grid;grid-template-columns:1fr 120px;gap:12px}@media(max-width:600px){.page{padding:28px 16px}.top{align-items:stretch;flex-direction:column}.top .q-btn{width:100%}.catalog-tabs{overflow-x:auto}.context,.form-row{grid-template-columns:1fr}.notice-actions{width:100%;flex-wrap:wrap}.notice-actions .q-field{flex:1}.inline-create{align-items:stretch;flex-direction:column}}
.weight-meta{display:flex;gap:6px;margin-top:7px;flex-wrap:wrap}</style>