<template>
  <q-page class="page">
    <section class="top"><div><p class="eyebrow">ADMINISTRAÇÃO</p><h1 class="page-title">Importar questões</h1><p>Envie PDFs para o banco global; concurso, banca e ano são identificados como metadados de origem.</p></div></section>
    <q-banner v-if="error" rounded class="error">{{ error }}</q-banner><q-banner v-if="success" rounded class="success">{{ success }}</q-banner>
    <q-card flat class="card"><q-card-section><div class="section-title"><div><h2>Importar PDFs de questões</h2><p>Os arquivos entram na fila. O worker extrai questões objetivas, identifica origem e classifica na taxonomia.</p></div><q-chip color="blue-1" text-color="primary" icon="schedule">Processamento assíncrono</q-chip></div><div class="upload-grid"><q-file v-model="pdfDocuments" outlined dense multiple accept="application/pdf,.pdf" label="PDFs com questões" use-chips clearable><template #prepend><q-icon name="upload_file"/></template></q-file></div><div class="upload-action"><span>{{ pdfDocuments.length ? pdfDocuments.length + ' arquivo(s) selecionado(s)' : 'Selecione um ou mais PDFs.' }}</span><q-btn unelevated no-caps color="primary" icon="queue" label="Enviar para a fila" :disable="!pdfDocuments.length" :loading="loading" @click="queuePdfBatch"/></div></q-card-section></q-card>
    <q-card v-if="pdfJobs.length" flat class="card"><q-card-section><div class="section-title"><div><h2>Resumo da importação</h2><p>Atualização automática enquanto houver arquivos na fila.</p></div><q-btn flat dense no-caps icon="refresh" label="Atualizar" @click="refreshPdfJobs"/></div><q-list separator><q-item v-for="job in pdfJobs" :key="job.id" class="job"><q-item-section><div class="job-head"><div><q-item-label class="file">{{ job.documentOriginalName }}</q-item-label><q-item-label caption>{{ statusLabel(job.status) }} · {{ job.pageCount || '—' }} páginas analisadas</q-item-label></div><q-badge rounded :color="statusColor(job.status)">{{ job.progress }}%</q-badge></div><q-linear-progress rounded size="8px" :value="job.progress / 100" :color="statusColor(job.status)" track-color="blue-1" class="q-mt-sm"/><div class="metrics"><div><strong>{{ job.extractedQuestions }}</strong><span>extraídas</span></div><div><strong>{{ job.createdQuestions }}</strong><span>criadas</span></div><div><strong>{{ job.duplicateQuestions }}</strong><span>duplicadas</span></div><div><strong>{{ job.failedQuestions }}</strong><span>com erro</span></div><div><strong>{{ job.classifiedQuestions }}</strong><span>classificadas</span></div><div><strong>{{ job.createdTaxonomySubjects }}</strong><span>assuntos novos</span></div><div><strong>{{ job.candidatePages }}</strong><span>páginas candidatas</span></div></div><q-banner v-if="job.errorMessage" dense rounded class="job-error">{{ job.errorMessage }}</q-banner><q-item-label caption class="q-mt-sm">Assuntos novos são criados somente quando a IA não encontra um equivalente canônico ativo; duplicidades são preservadas para revisão.</q-item-label></q-item-section></q-item></q-list></q-card-section></q-card>
    <q-expansion-item class="card legacy" icon="data_object" label="Importação estruturada (JSON/CSV)" caption="Valide e crie rascunhos a partir de dados estruturados."><q-card-section class="q-gutter-md"><q-select v-model="format" outlined label="Formato" :options="['JSON','CSV']"/><q-input v-model="content" outlined type="textarea" autogrow label="Conteúdo da importação"/><q-btn unelevated no-caps color="primary" label="Validar importação" :loading="loading" @click="previewImport"/></q-card-section><q-card-section v-if="report"><h2>Relatório de validação</h2><p>{{ report.validRows }} linhas válidas · {{ report.invalidRows }} bloqueadas para revisão</p><q-list bordered separator><q-item v-for="row in report.rows" :key="row.rowNumber"><q-item-section><q-item-label>Linha {{ row.rowNumber }} — {{ row.valid ? 'pronta para rascunho' : 'revisão necessária' }}</q-item-label><q-item-label v-if="row.errors.length" caption>{{ row.errors.map(item => item.message).join(' · ') }}</q-item-label></q-item-section></q-item></q-list><q-btn class="q-mt-md" unelevated no-caps color="primary" label="Confirmar linhas válidas" :disable="!syllabusId || !report.validRows" :loading="loading" @click="commitImport"/></q-card-section></q-expansion-item>
  </q-page>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useImport } from './useImport';
const format=ref<'JSON'|'CSV'>('JSON'); const content=ref(''); const syllabusId=ref(''); const examId=ref(''); const positionId=ref(''); const pdfDocuments=ref<File[]>([]);
const { commit,error,exams,loadExams,loadPositions: loadCatalogPositions,loadSyllabi: loadCatalogSyllabi,loading,pdfJobs,positions,preview,queuePdfs,refreshPdfJobs,report,success,syllabi }=useImport();
async function loadPositions(){positionId.value='';syllabusId.value='';await loadCatalogPositions(examId.value)} async function loadSyllabi(){syllabusId.value='';await loadCatalogSyllabi(positionId.value)} async function previewImport(){await preview(format.value,content.value)} async function commitImport(){await commit(syllabusId.value)} async function queuePdfBatch(){await queuePdfs(pdfDocuments.value);pdfDocuments.value=[]} function statusLabel(status:string){return ({PENDING:'Na fila',PROCESSING:'Processando',COMPLETED:'Concluído',FAILED:'Falhou'} as Record<string,string>)[status]??status} function statusColor(status:string){return ({PENDING:'orange',PROCESSING:'primary',COMPLETED:'positive',FAILED:'negative'} as Record<string,string>)[status]??'grey'} onMounted(loadExams);
</script>
<style scoped>.page{max-width:1100px;margin:auto;padding:42px 34px}.top{margin-bottom:20px}.eyebrow{color:#7187ad;font-size:11px;font-weight:800;letter-spacing:.1em}.card{background:#fff;border:1px solid #e5ecf6;border-radius:16px;margin-top:16px}.section-title{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.section-title h2{margin:0;color:#102a5c;font-size:18px}.section-title p{margin:5px 0 0;color:#637797}.upload-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.upload-action{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-top:16px;color:#637797;font-size:13px}.error{margin-top:16px;background:#fff3f2;color:#ae2f25}.success{margin-top:16px;background:#edf9f1;color:#22764a}.job{padding:18px 0}.job-head{display:flex;justify-content:space-between;gap:12px}.file{font-weight:700;color:#102a5c}.metrics{display:grid;grid-template-columns:repeat(7,1fr);gap:8px;margin-top:15px}.metrics div{padding:9px;border-radius:10px;background:#f5f8fd}.metrics strong,.metrics span{display:block}.metrics strong{color:#0d55d7;font-size:17px}.metrics span{color:#6b7e9d;font-size:11px}.job-error{margin-top:12px;background:#fff1f0;color:#b42318}.legacy{padding:4px 12px}@media(max-width:700px){.page{padding:28px 16px}.upload-grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.upload-action,.section-title{align-items:stretch;flex-direction:column}}</style>
