<template>
  <q-page class="user-management-page q-pa-md">
    <div class="page-heading"><div><p class="eyebrow">ADMINISTRAÇÃO</p><h1>Usuários e acessos</h1><p>Gerencie aprovações, papéis e vínculos explícitos do Google.</p></div><q-btn unelevated no-caps color="primary" icon="person_add" label="Cadastrar usuário" @click="openCreate" /></div>
    <q-card flat class="surface-card q-mt-md"><q-card-section class="filters"><q-input v-model="query" outlined dense clearable label="Buscar por nome ou e-mail" debounce="350" @update:model-value="load(1)"><template #prepend><q-icon name="search" /></template></q-input><q-select v-model="status" outlined dense clearable label="Status" :options="statusOptions" emit-value map-options @update:model-value="load(1)" /></q-card-section></q-card>
    <q-banner v-if="error" rounded class="error-banner q-mt-md">{{ error }}</q-banner>
    <q-card flat class="surface-card q-mt-md"><q-inner-loading :showing="loading" label="Carregando usuários..." /><q-list v-if="!loading && users.length" separator><q-item v-for="user in users" :key="user.id" class="user-row"><q-item-section avatar><q-avatar color="blue-1" text-color="primary">{{ initials(user.name) }}</q-avatar></q-item-section><q-item-section><q-item-label>{{ user.name }}</q-item-label><q-item-label caption>{{ user.email }}<span v-if="user.googleEmail"> · Google: {{ user.googleEmail }}</span></q-item-label><div class="chips"><q-chip v-for="role in user.roles" :key="role" dense color="indigo-1" text-color="indigo-9">{{ role }}</q-chip><q-chip dense :color="statusColor(user.status)" text-color="dark">{{ statusLabel(user.status) }}</q-chip></div></q-item-section><q-item-section side top><q-btn flat round icon="more_vert" aria-label="Gerenciar usuário"><q-menu><q-list style="min-width:220px"><q-item clickable v-close-popup @click="openEdit(user)"><q-item-section avatar><q-icon name="manage_accounts" /></q-item-section><q-item-section>Editar acesso</q-item-section></q-item><q-item v-if="user.googleEmail" clickable v-close-popup @click="removeGoogleIdentity(user.id)"><q-item-section avatar><q-icon name="link_off" /></q-item-section><q-item-section>Remover vínculo Google</q-item-section></q-item></q-list></q-menu></q-btn></q-item-section></q-item></q-list><q-card-section v-else-if="!loading" class="empty-state"><q-icon name="group_off" size="42px" /><p>Nenhum usuário foi encontrado para estes filtros.</p></q-card-section><q-separator /><q-card-actions align="between"><span class="caption">{{ total }} usuário(s)</span><q-pagination :model-value="page" :max="Math.max(1, Math.ceil(total / perPage))" direction-links @update:model-value="load" /></q-card-actions></q-card>
    <q-dialog v-model="dialog"><q-card class="dialog-card"><q-card-section><div class="text-h6">{{ editing ? 'Editar acesso' : 'Cadastrar usuário' }}</div></q-card-section><q-card-section class="q-gutter-md"><q-input v-if="!editing" v-model="form.name" outlined label="Nome" /><q-input v-if="!editing" v-model="form.email" outlined label="E-mail local" type="email" /><q-input v-if="!editing" v-model="form.password" outlined label="Senha local (opcional)" type="password" /><q-input v-model="form.googleEmail" outlined clearable label="E-mail Google (opcional)" type="email" /><q-select v-model="form.roles" outlined multiple use-chips label="Papéis" :options="roleOptions" emit-value map-options /><q-select v-model="form.status" outlined label="Status" :options="statusOptions" emit-value map-options /></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup /><q-btn unelevated no-caps color="primary" :loading="saving" :label="editing ? 'Salvar alterações' : 'Cadastrar'" @click="submit" /></q-card-actions></q-card></q-dialog>
  </q-page>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import type { ManagedUser, ManagedUserRole, ManagedUserStatus } from '../../../Domain/UserManagement/UserManagementRepository'
import { useUserManagement } from './useUserManagement'
const { users, total, page, perPage, query, status, loading, saving, error, load, create, setGoogleIdentity, removeGoogleIdentity: unlink, updateRoles, updateStatus } = useUserManagement()
const statusOptions: readonly { label: string; value: ManagedUserStatus }[] = [{ label: 'Ativo', value: 'ACTIVE' }, { label: 'Aguardando aprovação', value: 'PENDING_APPROVAL' }, { label: 'Bloqueado', value: 'BLOCKED' }]
const roleOptions: readonly { label: string; value: ManagedUserRole }[] = [{ label: 'Usuário', value: 'USER' }, { label: 'Administrador', value: 'ADMIN' }]
const dialog = ref(false); const editing = ref<ManagedUser | null>(null)
const form = reactive<{ name: string; email: string; password: string; googleEmail: string; roles: ManagedUserRole[]; status: ManagedUserStatus }>({ name: '', email: '', password: '', googleEmail: '', roles: ['USER'], status: 'ACTIVE' })
function initials(name: string): string { return name.split(' ').filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase() }
function statusLabel(value: ManagedUserStatus): string { return statusOptions.find((item) => item.value === value)?.label ?? value }
function statusColor(value: ManagedUserStatus): string { return value === 'ACTIVE' ? 'green-1' : value === 'BLOCKED' ? 'red-1' : 'amber-1' }
function openCreate(): void { editing.value = null; Object.assign(form, { name: '', email: '', password: '', googleEmail: '', roles: ['USER'], status: 'ACTIVE' }); dialog.value = true }
function openEdit(user: ManagedUser): void { editing.value = user; Object.assign(form, { name: user.name, email: user.email, password: '', googleEmail: user.googleEmail ?? '', roles: [...user.roles], status: user.status }); dialog.value = true }
async function submit(): Promise<void> { if (!editing.value) { if (await create({ name: form.name, email: form.email, password: form.password || undefined, googleEmail: form.googleEmail || undefined, roles: form.roles, status: form.status })) dialog.value = false; return } const user = editing.value; const rolesChanged = user.roles.join(',') !== form.roles.join(','); if (rolesChanged && !await updateRoles(user.id, form.roles)) return; if (user.status !== form.status && !await updateStatus(user.id, form.status)) return; if ((user.googleEmail ?? '') !== form.googleEmail) { if (form.googleEmail ? !await setGoogleIdentity(user.id, form.googleEmail) : !await unlink(user.id)) return } dialog.value = false }
async function removeGoogleIdentity(userId: string): Promise<void> { await unlink(userId) }
onMounted(() => { void load() })
</script>
<style scoped>
.user-management-page{max-width:1280px;margin:0 auto}.page-heading{display:flex;justify-content:space-between;align-items:flex-end;gap:20px}.page-heading h1{margin:0;color:#18305c;font-size:28px}.page-heading p:not(.eyebrow){margin:7px 0 0;color:#74849d}.eyebrow{margin:0 0 6px;color:#5577ad;font-size:11px;font-weight:800;letter-spacing:.1em}.surface-card{border:1px solid #e2eaf6;border-radius:18px;background:rgba(255,255,255,.82)}.filters{display:grid;grid-template-columns:minmax(0,1fr) 230px;gap:12px}.user-row{padding:16px}.chips{display:flex;gap:4px;flex-wrap:wrap;margin-top:7px}.empty-state{text-align:center;color:#7285a3;padding:52px}.error-banner{background:#fff0f0;color:#a31f2f}.dialog-card{width:min(510px,94vw)}.caption{color:#71829d;font-size:13px}@media(max-width:599px){.page-heading{align-items:stretch;flex-direction:column}.filters{grid-template-columns:1fr}.user-row{padding:13px 8px}}
</style>
