<?php
declare(strict_types=1);
namespace App\Infrastructure\Persistence\Doctrine\QuestionBank;
use App\Domain\QuestionBank\Entity\QuestionPdfImportJob;
use App\Domain\QuestionBank\Enum\QuestionImportUsageAvailability;use App\Domain\QuestionBank\ValueObject\QuestionImportJobTelemetry;use App\Domain\QuestionBank\ValueObject\QuestionImportTokenUsage;
use App\Domain\QuestionBank\Repository\QuestionPdfImportJobRepositoryInterface;
use App\Infrastructure\Persistence\Doctrine\QuestionBank\Entity\QuestionPdfImportJobRecord;
use Doctrine\DBAL\LockMode;
use Doctrine\ORM\EntityManagerInterface;
final class DoctrineQuestionPdfImportJobRepository implements QuestionPdfImportJobRepositoryInterface
{
    public function __construct(private readonly EntityManagerInterface $em) {}
    public function save(QuestionPdfImportJob $job): void { $record=$this->em->find(QuestionPdfImportJobRecord::class,$job->id); if(!$record instanceof QuestionPdfImportJobRecord){$record=new QuestionPdfImportJobRecord();$record->id=$job->id;$this->em->persist($record);} foreach(['syllabusId','createdBy','documentPath','documentSha256','documentOriginalName','status','progress','pageCount','candidatePages','processedChunks','retryCount','nextAttemptAt','extractedQuestions','classifiedQuestions','createdQuestions','duplicateQuestions','failedQuestions','createdTaxonomySubjects','errorMessage','createdAt','startedAt','finishedAt'] as $property)$record->$property=$job->$property; $this->syncTelemetry($record,$job); }
    public function findById(string $id): ?QuestionPdfImportJob { $record=$this->em->find(QuestionPdfImportJobRecord::class,$id); return $record instanceof QuestionPdfImportJobRecord?$this->map($record):null; }
    public function findByIdForUser(string $id,string $userId): ?QuestionPdfImportJob { $record=$this->em->createQueryBuilder()->select('job')->from(QuestionPdfImportJobRecord::class,'job')->where('job.id=:id')->andWhere('job.createdBy=:user')->setParameter('id',$id)->setParameter('user',$userId)->getQuery()->getOneOrNullResult(); return $record instanceof QuestionPdfImportJobRecord?$this->map($record):null; }
    public function listForUser(string $userId,int $offset,int $limit): array { $records=$this->em->createQueryBuilder()->select('job')->from(QuestionPdfImportJobRecord::class,'job')->where('job.createdBy=:user')->setParameter('user',$userId)->orderBy('job.createdAt','DESC')->setFirstResult($offset)->setMaxResults($limit)->getQuery()->getResult(); return array_values(array_map(fn(QuestionPdfImportJobRecord $record):QuestionPdfImportJob=>$this->map($record),$records)); }
    public function countForUser(string $userId): int { return (int)$this->em->createQueryBuilder()->select('COUNT(job.id)')->from(QuestionPdfImportJobRecord::class,'job')->where('job.createdBy=:user')->setParameter('user',$userId)->getQuery()->getSingleScalarResult(); }
    public function cancelForUser(string $id,string $userId):bool { return $this->em->createQueryBuilder()->update(QuestionPdfImportJobRecord::class,'job')->set('job.status', ':cancelled')->set('job.errorMessage', ':message')->set('job.nextAttemptAt', 'NULL')->set('job.finishedAt', ':now')->where('job.id=:id')->andWhere('job.createdBy=:user')->andWhere('job.status IN (:active)')->setParameter('cancelled','CANCELLED')->setParameter('message','Interrompido pelo administrador.')->setParameter('now',new \DateTimeImmutable('now'))->setParameter('id',$id)->setParameter('user',$userId)->setParameter('active',['PENDING','PROCESSING'])->getQuery()->execute()===1; }
    public function isCancelled(string $id):bool { return (int)$this->em->createQueryBuilder()->select('COUNT(job.id)')->from(QuestionPdfImportJobRecord::class,'job')->where('job.id=:id')->andWhere('job.status=:status')->setParameter('id',$id)->setParameter('status','CANCELLED')->getQuery()->getSingleScalarResult() > 0; }
    public function listProcessing(): array { $records=$this->em->createQueryBuilder()->select("job")->from(QuestionPdfImportJobRecord::class,"job")->where("job.status = :status")->setParameter("status","PROCESSING")->orderBy("job.createdAt","ASC")->getQuery()->getResult(); return array_values(array_map(fn(QuestionPdfImportJobRecord $record): QuestionPdfImportJob => $this->map($record), $records)); }
    public function claimNext(): ?QuestionPdfImportJob
    {
        return $this->em->wrapInTransaction(function () {
            $now = new \DateTimeImmutable("now");
            $stale = $now->modify("-10 minutes");
            $record = $this->em->createQueryBuilder()->select("job")->from(QuestionPdfImportJobRecord::class, "job")
                ->where("(job.status = :pending AND (job.nextAttemptAt IS NULL OR job.nextAttemptAt <= :now)) OR (job.status = :processing AND job.startedAt <= :stale)")
                ->setParameter("pending", "PENDING")->setParameter("processing", "PROCESSING")->setParameter("now", $now)->setParameter("stale", $stale)
                ->orderBy("job.createdAt", "ASC")->setMaxResults(1)->getQuery()->setLockMode(LockMode::PESSIMISTIC_WRITE)->getOneOrNullResult();
            if (!$record instanceof QuestionPdfImportJobRecord) return null;
            $record->status = "PROCESSING"; $record->progress = max(1, $record->progress); $record->nextAttemptAt = null; $record->errorMessage = null; $record->startedAt ??= $now;
            $this->em->flush();
            return $this->map($record);
        });
    }
    private function syncTelemetry(QuestionPdfImportJobRecord $record, QuestionPdfImportJob $job): void { $telemetry=$job->analysisTelemetry; if ($telemetry===null) return; $record->analysisProvider=$telemetry->provider; $record->analysisModel=$telemetry->model; $record->analysisSchemaVersion=$telemetry->schemaVersion; $record->analysisDurationMilliseconds=$telemetry->durationMilliseconds; $record->analysisInputTokens=$telemetry->tokenUsage->inputTokens; $record->analysisOutputTokens=$telemetry->tokenUsage->outputTokens; $record->analysisTotalTokens=$telemetry->tokenUsage->totalTokens; $record->analysisCostUsd=$telemetry->tokenUsage->costUsd; $record->analysisUsageAvailability=$telemetry->tokenUsage->availability->value; $record->analysisCount=$telemetry->analysisCount; $record->answerKeyConflictCount=$telemetry->answerKeyConflictCount; $record->imageDiscrepancyCount=$telemetry->imageDiscrepancyCount; $record->structuralIssueCount=$telemetry->structuralIssueCount; }    private function telemetry(QuestionPdfImportJobRecord $record): ?QuestionImportJobTelemetry { if ($record->analysisCount===0) return null; return new QuestionImportJobTelemetry($record->analysisProvider,$record->analysisModel,$record->analysisSchemaVersion,$record->analysisDurationMilliseconds??0,new QuestionImportTokenUsage(QuestionImportUsageAvailability::from($record->analysisUsageAvailability),$record->analysisInputTokens,$record->analysisOutputTokens,$record->analysisTotalTokens,$record->analysisCostUsd),$record->analysisCount,$record->answerKeyConflictCount,$record->imageDiscrepancyCount,$record->structuralIssueCount); }
    private function map(QuestionPdfImportJobRecord $record):QuestionPdfImportJob { return new QuestionPdfImportJob($record->id,$record->syllabusId,$record->createdBy,$record->documentPath,$record->documentSha256,$record->documentOriginalName,$record->status,$record->progress,$record->pageCount,$record->candidatePages,$record->processedChunks,$record->retryCount,$record->nextAttemptAt,$record->extractedQuestions,$record->classifiedQuestions,$record->createdQuestions,$record->duplicateQuestions,$record->failedQuestions,$record->createdTaxonomySubjects,$record->errorMessage,$record->createdAt,$record->startedAt,$record->finishedAt,$this->telemetry($record)); }
}
