import type { CreateQuestionCommentCommand, CreateQuestionProblemReportCommand, QuestionComment, QuestionExplanation, QuestionInteraction, QuestionLearningRepository, QuestionNote, QuestionProblemReport, UpdateQuestionInteractionCommand } from '../../Domain/QuestionLearning/QuestionLearningRepository'

export class GetQuestionInteractionUseCase { public constructor(private readonly repository: QuestionLearningRepository) {} public execute(questionId: string): Promise<QuestionInteraction> { return this.repository.getInteraction(questionId) } }
export class UpdateQuestionInteractionUseCase { public constructor(private readonly repository: QuestionLearningRepository) {} public execute(questionId: string, command: UpdateQuestionInteractionCommand): Promise<QuestionInteraction> { return this.repository.updateInteraction(questionId, command) } }
export class GetQuestionNoteUseCase { public constructor(private readonly repository: QuestionLearningRepository) {} public execute(questionId: string): Promise<QuestionNote | null> { return this.repository.getNote(questionId) } }
export class SaveQuestionNoteUseCase { public constructor(private readonly repository: QuestionLearningRepository) {} public execute(questionId: string, content: string): Promise<QuestionNote> { const normalized = content.trim(); if (!normalized) return Promise.reject(new Error('Escreva uma anotação antes de salvar.')); return this.repository.saveNote(questionId, normalized) } }
export class ListQuestionCommentsUseCase { public constructor(private readonly repository: QuestionLearningRepository) {} public execute(questionId: string, page?: number, perPage?: number): Promise<readonly QuestionComment[]> { return this.repository.listComments(questionId, page, perPage) } }
export class CreateQuestionCommentUseCase { public constructor(private readonly repository: QuestionLearningRepository) {} public execute(questionId: string, command: CreateQuestionCommentCommand): Promise<QuestionComment> { if (!command.content.trim()) return Promise.reject(new Error('Escreva um comentário antes de enviar.')); return this.repository.createComment(questionId, { ...command, content: command.content.trim() }) } }
export class CreateQuestionProblemReportUseCase { public constructor(private readonly repository: QuestionLearningRepository) {} public execute(questionId: string, command: CreateQuestionProblemReportCommand): Promise<QuestionProblemReport> { if (!command.description.trim()) return Promise.reject(new Error('Descreva o problema encontrado.')); return this.repository.createProblemReport(questionId, { ...command, description: command.description.trim() }) } }
export class RequestQuestionExplanationUseCase { public constructor(private readonly repository: QuestionLearningRepository) {} public execute(questionId: string, attemptId?: string): Promise<QuestionExplanation> { return this.repository.requestExplanation(questionId, attemptId) } }
export class GetLatestQuestionExplanationUseCase { public constructor(private readonly repository: QuestionLearningRepository) {} public execute(questionId: string): Promise<QuestionExplanation> { return this.repository.latestExplanation(questionId) } }
