<?php
declare(strict_types=1);
namespace App\Application\Review\Service;
use App\Application\Review\Port\TransactionManagerInterface;
use App\Domain\Review\Entity\ReviewSession;use App\Domain\Review\Enum\ReviewSessionKind;use App\Domain\Review\Enum\ReviewSessionStatus;use App\Domain\Review\Repository\FlashcardRepositoryInterface;use App\Domain\Review\Repository\FlashcardReviewRepositoryInterface;use App\Domain\Review\Repository\ReviewSessionRepositoryInterface;use App\Domain\Review\Repository\UserConceptMasteryRepositoryInterface;use App\Domain\Review\Repository\UserFlashcardProgressRepositoryInterface;use App\Domain\Review\Service\ReviewPriorityCalculatorInterface;
final readonly class BuildReviewSessionService {
 public function __construct(private ReviewSessionRepositoryInterface $sessions,private UserFlashcardProgressRepositoryInterface $progresses,private UserConceptMasteryRepositoryInterface $mastery,private FlashcardRepositoryInterface $cards,private FlashcardReviewRepositoryInterface $reviews,private ReviewPriorityCalculatorInterface $priorities,private TransactionManagerInterface $transactions){}
 public function execute(string $userId,ReviewSessionKind $kind,int $limit,\DateTimeImmutable $now):ReviewSession{return $this->transactions->transactional(fn():ReviewSession=>$this->build($userId,$kind,$limit,$now));}
 private function build(string $userId,ReviewSessionKind $kind,int $limit,\DateTimeImmutable $now):ReviewSession {
  if($limit<1||$limit>100)throw new \InvalidArgumentException('Limite de revisão inválido.');
  if($kind===ReviewSessionKind::ADVANCE&&$this->progresses->countDueForUser($userId,$now)>0)throw new \DomainException('Há cards vencidos para revisar.');
  $session=$this->sessions->findActive($userId,$kind)??new ReviewSession($this->uuid(),$userId,$kind,ReviewSessionStatus::ACTIVE,$limit,$now);
  $current=$session->currentId();
  if($current!==null&&!$this->reviews->hasSessionReview($session->id,$current)){$session->cards=$this->resolve([$current]);return $this->withNavigation($session,$userId,$now);}
  $pendingPosition=$this->pendingPosition($session,$session->currentPosition+1,1)??$this->pendingPosition($session,1,1);
  if($pendingPosition!==null){$session->currentPosition=$pendingPosition;$this->sessions->save($session);$session->cards=$this->resolve([$session->currentId()]);return $this->withNavigation($session,$userId,$now);}
  if(count($session->flashcardIds)>=$session->requestedLimit){$session->complete($now);$this->sessions->save($session);return $this->withNavigation($session,$userId,$now);}
  $next=$this->next($userId,$kind,$now,$session->flashcardIds);$this->sessions->save($session);if($next!==null){$this->sessions->serveCard($session,$next);$session->cards=$this->resolve([$next]);}return $this->withNavigation($session,$userId,$now);
 }
 public function navigate(string $userId,string $sessionId,string $direction,\DateTimeImmutable $now):ReviewSession{$session=$this->sessions->findForUser($sessionId,$userId);if($session===null)throw new \DomainException('Sessão não encontrada.');if($direction==='PREVIOUS'){$position=$this->pendingPosition($session,$session->currentPosition-1,-1);if($position!==null){$session->currentPosition=$position;$this->sessions->save($session);}}elseif($direction==='NEXT'){$position=$this->pendingPosition($session,$session->currentPosition+1,1);if($position!==null){$session->currentPosition=$position;$this->sessions->save($session);}elseif(count($session->flashcardIds)<$session->requestedLimit){$next=$this->next($userId,$session->kind,$now,$session->flashcardIds);if($next!==null)$this->sessions->serveCard($session,$next);}}else throw new \InvalidArgumentException('Direção inválida.');$id=$session->currentId();$session->cards=$id===null?[]:$this->resolve([$id]);return $this->withNavigation($session,$userId,$now);}
 private function withNavigation(ReviewSession $session,string $userId,\DateTimeImmutable $now):ReviewSession{$session->canGoPrevious=$this->pendingPosition($session,$session->currentPosition-1,-1)!==null;$session->canGoNext=$this->pendingPosition($session,$session->currentPosition+1,1)!==null;if(!$session->canGoNext&&count($session->flashcardIds)<$session->requestedLimit)$session->canGoNext=$this->next($userId,$session->kind,$now,$session->flashcardIds)!==null;return $session;}
 private function pendingPosition(ReviewSession $session,int $position,int $step):?int{for($last=count($session->flashcardIds);$position>=1&&$position<=$last;$position+=$step){if(!$this->reviews->hasSessionReview($session->id,$session->flashcardIds[$position-1]))return $position;}return null;}
 private function next(string $userId,ReviewSessionKind $kind,\DateTimeImmutable $now,array $excluded):?string{$progresses=$kind===ReviewSessionKind::ADVANCE?$this->progresses->upcomingForUser($userId,$now,100,$excluded):$this->progresses->dueForUser($userId,$now,100,$excluded);$candidates=[];foreach($progresses as $progress){$card=$this->cards->findById($progress->flashcardId);if($card===null)continue;$mastery=$this->mastery->find($userId,$card->primaryTaxonomySubjectId);$candidates[]=['id'=>$card->id,'score'=>$this->priorities->calculate($progress,$mastery?->masteryScore,0,0,$now),'dueAt'=>$progress->state()->dueAt];}if($kind===ReviewSessionKind::ADVANCE)usort($candidates,static fn(array $a,array $b):int=>$a['dueAt']<=>$b['dueAt']);else usort($candidates,static fn(array $a,array $b):int=>$b['score']<=>$a['score']);return $candidates[0]['id']??null;}
 private function resolve(array $ids):array{return array_values(array_filter(array_map(fn(string $id)=>$this->cards->findById($id),$ids)));}
 private function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
