<template><q-page class="page"><section class="hero"><q-badge color="primary" outline>MINIJOGO DE REVISÃO</q-badge><h1>{{ game?.title || 'COBIT 4.1' }}</h1><p>{{ game?.instruction || 'Carregando exercício…' }}</p></section><q-banner v-if="error" rounded class="error">{{ error }}</q-banner><q-card v-if="game" flat class="game-card"><q-card-section><div class="domains"><q-chip v-for="domain in game.domains" :key="domain.id" outline color="primary"><strong>{{ domain.code }}</strong>&nbsp; {{ domain.name }}</q-chip></div><q-linear-progress :value="answered / game.processes.length" rounded size="9px" color="primary" class="q-my-lg"/><p class="progress">{{ answered }} de {{ game.processes.length }} processos associados</p><q-list separator><q-item v-for="process in game.processes" :key="process.id" class="process"><q-item-section><q-item-label>{{ process.name }}</q-item-label><q-item-label v-if="feedback(process.id)" caption :class="feedback(process.id)?.correct ? 'right' : 'wrong'">{{ feedback(process.id)?.correct ? 'Correto!' : 'O domínio correto é ' + feedback(process.id)?.expectedDomainId + '.' }}</q-item-label></q-item-section><q-item-section side><q-select v-model="selections[process.id]" dense outlined emit-value map-options :options="domainOptions" label="Domínio" :disable="!!result" class="domain-select"/></q-item-section></q-item></q-list></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Recomeçar" icon="refresh" @click="restart"/><q-btn unelevated no-caps color="primary" label="Conferir respostas" icon="task_alt" :disable="answered !== game.processes.length" :loading="submitting" @click="submit"/></q-card-actions></q-card><q-card v-if="result" flat class="result" :class="result.percentage === 100 ? 'perfect' : ''"><q-card-section><q-icon :name="result.percentage === 100 ? 'emoji_events' : 'school'" size="30px" color="primary"/><h2>{{ result.correctCount }} de {{ result.total }} acertos</h2><p>{{ result.percentage }}% — {{ result.percentage === 100 ? 'Excelente domínio dos processos!' : 'Revise os itens indicados e tente novamente.' }}</p></q-card-section></q-card></q-page></template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { reviewUseCases } from '../../../Infrastructure/Container'
import type { CobitGame, CobitGameResult } from '../../../Domain/Review/ReviewRepository'

const game = ref<CobitGame | null>(null)
const result = ref<CobitGameResult | null>(null)
const selections = ref<Record<string, string>>({})
const error = ref('')
const submitting = ref(false)
const answered = computed(() => Object.keys(selections.value).filter((key) => selections.value[key]).length)
const domainOptions = computed(() => game.value?.domains.map((domain) => ({ label: domain.code + ' — ' + domain.name, value: domain.id })) ?? [])
function feedback(id: string) { return result.value?.answers.find((answer) => answer.processId === id) }
function restart(): void { result.value = null; selections.value = {} }
async function submit(): Promise<void> { if (!game.value) return; submitting.value = true; error.value = ''; try { result.value = await reviewUseCases.evaluateCobitGame(game.value.processes.map((process) => ({ processId: process.id, domainId: selections.value[process.id] }))) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Não foi possível corrigir o jogo.' } finally { submitting.value = false } }
onMounted(async () => { try { game.value = await reviewUseCases.cobitGame() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Não foi possível carregar o jogo.' } })
</script>
<style scoped>.page{max-width:980px;margin:auto;padding:42px 30px}.hero h1{margin:10px 0 6px;color:#17345d}.hero p,.progress{color:#69809e}.game-card,.result{margin-top:18px;border:1px solid #dce7f5;border-radius:20px;background:#fff}.domains{display:flex;gap:8px;flex-wrap:wrap}.process{min-height:72px}.domain-select{width:245px}.right{color:#177449;font-weight:700}.wrong{color:#b34436;font-weight:700}.result{text-align:center}.result h2{margin:8px 0;color:#17345d}.result p{margin:0;color:#69809e}.perfect{border-color:#79d6a5;background:#f1fff7}.error{margin-top:16px;background:#fff2f0;color:#a33327}@media(max-width:600px){.page{padding:28px 16px}.process{align-items:stretch;flex-direction:column;gap:10px}.process :deep(.q-item__section--side){padding-left:0}.domain-select{width:100%}}</style>
