<?php
declare(strict_types=1);
namespace Tests\Unit\Identity;
use App\Application\Identity\DTO\Request\GoogleLoginRequestDto;use App\Application\Identity\Mapper\IdentityResponseMapper;use App\Application\Identity\Port\{AccessTokenClaims,AccessTokenIssuerInterface,AccessTokenVerifierInterface,ClockInterface,GoogleOidcValidatorInterface,IpAddressHasherInterface,PasswordHasherInterface,RefreshTokenGeneratorInterface,TransactionManagerInterface,VerifiedGoogleIdentity};use App\Application\Identity\Service\{AuthService,GoogleAuthenticationService};use App\Domain\Identity\Entity\{AuthEvent,AuthSession,GoogleIdentity,User};use App\Domain\Identity\Exception\GoogleIdentityConflictException;use App\Domain\Identity\Repository\{AuthEventRepositoryInterface,AuthSessionRepositoryInterface,GoogleIdentityRepositoryInterface,UserRepositoryInterface};use App\Domain\Identity\ValueObject\GoogleEmail;use PHPUnit\Framework\TestCase;
final class GoogleAuthenticationServiceTest extends TestCase {
 public function testFirstGoogleLoginCreatesOnlyOnePendingAccount():void{$users=new GoogleTestUsers();$links=new GoogleTestLinks();$s=$this->service($users,$links);$first=$s->authenticate(new GoogleLoginRequestDto('credential',null));$second=$s->authenticate(new GoogleLoginRequestDto('credential',null));self::assertSame('PENDING_APPROVAL',$first->status);self::assertNull($first->authentication);self::assertSame(1,count($users->all));self::assertSame('PENDING_APPROVAL',$second->status);}
 public function testGoogleEmailMatchingLocalUserIsAConflict():void{$users=new GoogleTestUsers([new User('local','person@example.test','Pessoa','hash','ACTIVE',['USER'])]);$this->expectException(GoogleIdentityConflictException::class);$this->service($users,new GoogleTestLinks())->authenticate(new GoogleLoginRequestDto('credential',null));}
 public function testActiveLinkedUserReceivesSession():void{$user=new User('active','person@example.test','Pessoa','hash','ACTIVE',['USER']);$users=new GoogleTestUsers([$user]);$links=new GoogleTestLinks([new GoogleIdentity('active',GoogleEmail::from('person@example.test'),new \DateTimeImmutable(),new \DateTimeImmutable())]);$result=$this->service($users,$links)->authenticate(new GoogleLoginRequestDto('credential','browser'));self::assertNotNull($result->authentication);self::assertSame('access',$result->authentication->accessToken);}
 private function service(GoogleTestUsers $users,GoogleTestLinks $links):GoogleAuthenticationService{$clock=new GoogleTestClock();$auth=new AuthService($users,new GoogleTestSessions(),new GoogleTestEvents(),new GoogleTestPassword(),new GoogleTestTokens(),new GoogleTestTokens(),new GoogleTestRefresh(),new GoogleTestIp(),$clock,new GoogleTestTransaction(),new IdentityResponseMapper(),3600);return new GoogleAuthenticationService(new GoogleTestValidator(),$users,$links,$auth,$clock,new GoogleTestTransaction());}
}
final class GoogleTestUsers implements UserRepositoryInterface {/** @var array<string,User> */public array $all=[];public function __construct(array $items=[]){foreach($items as $item)$this->all[$item->id]=$item;}public function findByEmail(string $email):?User{foreach($this->all as $u)if($u->email===$email)return$u;return null;}public function findById(string $id):?User{return$this->all[$id]??null;}public function save(User $u):void{$this->all[$u->id]=$u;}public function list(int $offset,int $limit,?string $query,?string $status):array{return array_slice(array_values($this->all),$offset,$limit);}public function count(?string $query,?string $status):int{return count($this->all);}public function countActiveAdmins():int{return count(array_filter($this->all,fn(User $u)=>$u->status==="ACTIVE"&&in_array("ADMIN",$u->roles,true)));}}
final class GoogleTestLinks implements GoogleIdentityRepositoryInterface {/** @var array<string,GoogleIdentity> */private array $links=[];public function __construct(array $items=[]){foreach($items as $i)$this->links[$i->email->value]=$i;}public function findByEmail(GoogleEmail $e):?GoogleIdentity{return$this->links[$e->value]??null;}public function findByUserId(string $id):?GoogleIdentity{foreach($this->links as $i)if($i->userId===$id)return$i;return null;}public function save(GoogleIdentity $i):void{$this->links[$i->email->value]=$i;}public function removeForUserId(string $id):void{}}
final class GoogleTestValidator implements GoogleOidcValidatorInterface {public function validate(string $c):VerifiedGoogleIdentity{return new VerifiedGoogleIdentity('person@example.test','Pessoa',null);}}
final class GoogleTestSessions implements AuthSessionRepositoryInterface {public function findByRefreshTokenHashForUpdate(string $h):?AuthSession{return null;}public function save(AuthSession $s):void{}public function revoke(string $id,\DateTimeImmutable $at):void{}public function revokeFamily(string $id,\DateTimeImmutable $at):void{}}
final class GoogleTestEvents implements AuthEventRepositoryInterface {public function append(AuthEvent $e):void{}}
final class GoogleTestPassword implements PasswordHasherInterface {public function hash(string $p):string{return$p;}public function verify(string $p,string $h):bool{return true;}}
final class GoogleTestTokens implements AccessTokenIssuerInterface,AccessTokenVerifierInterface {public function issue(User $u):string{return'access';}public function verify(string $t):AccessTokenClaims{return new AccessTokenClaims('active');}}
final class GoogleTestRefresh implements RefreshTokenGeneratorInterface {public function generate():string{return'refresh';}}
final class GoogleTestIp implements IpAddressHasherInterface {public function hash(string $ip):string{return'ip';}}
final class GoogleTestClock implements ClockInterface {public function now():\DateTimeImmutable{return new \DateTimeImmutable('2026-01-01T00:00:00+00:00');}}
final class GoogleTestTransaction implements TransactionManagerInterface {public function transactional(callable $c):mixed{return$c();}}
