<template>
  <q-page class="page">
    <section class="top"><div><p class="eyebrow">ANÁLISE REAL</p><h1>Seu desempenho</h1><p>Resultados calculados a partir das suas tentativas concluídas.</p></div><q-btn flat no-caps color="primary" label="Atualizar" :loading="loading" @click="load" /></section>
    <q-banner v-if="error" rounded class="error">{{ error }}</q-banner>
    <q-inner-loading :showing="loading" color="primary" />
    <template v-if="statistics && !loading">
      <section class="metrics"><q-card flat><q-card-section><span>Respostas concluídas</span><strong>{{ statistics.total }}</strong></q-card-section></q-card><q-card flat class="positive"><q-card-section><span>Acertos</span><strong>{{ statistics.correct }}</strong></q-card-section></q-card><q-card flat class="negative"><q-card-section><span>Erros</span><strong>{{ statistics.incorrect }}</strong></q-card-section></q-card><q-card flat class="time"><q-card-section><span>Tempo médio</span><strong>{{ duration }}</strong></q-card-section></q-card></section>
      <q-card flat class="summary"><q-card-section><div><p class="eyebrow">TAXA GERAL</p><h2>{{ percentage }}% de acerto</h2><p>Uma leitura objetiva das respostas finais das suas tentativas.</p></div><div class="circle">{{ percentage }}%</div></q-card-section></q-card>
      <section class="heading"><div><h2>Desempenho por assunto</h2><p>Os assuntos aparecem quando há tentativas concluídas.</p></div></section>
      <q-card v-if="entries.length" flat class="subjects"><q-list separator><q-item v-for="[name, subject] in entries" :key="name"><q-item-section><q-item-label>{{ name }}</q-item-label><q-item-label caption>{{ subject.correct }} acertos em {{ subject.total }} respostas</q-item-label></q-item-section><q-item-section side class="subject-score"><q-linear-progress rounded size="8px" :value="subject.percentage / 100" color="primary" track-color="blue-1" /><strong>{{ Math.round(subject.percentage) }}%</strong></q-item-section></q-item></q-list></q-card>
      <q-card v-else flat class="empty"><q-card-section><q-img src="/images/concursos-study-mark.png" width="78px" height="78px" fit="contain" /><div><h2>Você ainda não tem resultados por assunto</h2><p>Resolva questões de um caderno e conclua as tentativas para acompanhar sua evolução.</p></div></q-card-section></q-card>
    </template>
  </q-page>
</template>
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { usePerformance } from './usePerformance'
const { error, load, loading, statistics } = usePerformance()
const percentage = computed(() => Math.round(statistics.value?.percentage ?? 0))
const duration = computed(() => { const seconds = Math.round(statistics.value?.averageElapsedSeconds ?? 0); return seconds > 59 ? String(Math.floor(seconds / 60)) + ' min' : String(seconds) + ' s' })
const entries = computed(() => Object.entries(statistics.value?.subjects ?? {}))
onMounted(load)
</script>
<style scoped>
.page{max-width:1050px;margin:auto;padding:42px 34px}.top{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:26px}.eyebrow{margin:0 0 7px;color:#7187ad;font-size:11px;font-weight:800;letter-spacing:.1em}.top h1{margin:0;color:#142950;font-size:32px}.top p:not(.eyebrow){margin:9px 0 0;color:#71819e}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.metrics .q-card,.summary,.subjects,.empty{border:1px solid #e5ecf6;border-radius:17px;background:#fff;box-shadow:0 8px 26px rgba(33,58,105,.04)}.metrics .q-card{border-top:3px solid #4a7af0}.metrics .positive{border-top-color:#25a66e}.metrics .negative{border-top-color:#e85f62}.metrics .time{border-top-color:#8461e5}.metrics span{display:block;color:#7888a4;font-size:12px}.metrics strong{display:block;margin-top:8px;color:#172e59;font-size:27px}.summary{margin-top:18px;background:linear-gradient(135deg,#fff,#f0f6ff)}.summary :deep(.q-card__section){display:flex;align-items:center;justify-content:space-between;padding:26px 30px}.summary h2{margin:0;color:#18305b;font-size:24px}.summary p:not(.eyebrow){color:#71819e}.circle{display:grid;place-items:center;width:100px;height:100px;border:10px solid #dbeaff;border-top-color:#2877d6;border-right-color:#2877d6;border-radius:50%;color:#215ba9;font-size:22px;font-weight:800}.heading{margin:34px 0 14px}.heading h2{margin:0;color:#172e59;font-size:20px}.heading p{margin:5px 0;color:#71819e;font-size:13px}.subjects{overflow:hidden}.subject-score{width:46%;display:flex;align-items:center;gap:12px}.subject-score :deep(.q-linear-progress){flex:1}.subject-score strong{color:#1d3765;font-size:13px}.empty :deep(.q-card__section){display:flex;align-items:center;gap:20px;padding:30px}.empty h2{margin:0;color:#1a315a;font-size:19px}.empty p{color:#71819e}.error{margin-bottom:14px;background:#fff3f2;color:#ae2f25}@media(max-width:700px){.page{padding:28px 16px}.metrics{grid-template-columns:1fr 1fr}.summary :deep(.q-card__section){align-items:flex-start;gap:18px}.circle{flex:0 0 88px;width:88px;height:88px;font-size:19px}.subject-score{width:48%}.empty :deep(.q-card__section){align-items:flex-start;flex-direction:column}}@media(max-width:430px){.metrics{grid-template-columns:1fr}.summary :deep(.q-card__section){flex-direction:column}.subject-score{width:42%}}
</style>
