<template>
  <section class="study-map" aria-label="Mapa de estudo">
    <header class="map-header"><div><p class="eyebrow">MAPA DE ESTUDO</p><h2>Seu cronograma por assunto</h2><p>Planejamento, dependências e desempenho das suas práticas.</p></div><div class="map-actions"><div class="period-controls"><q-input v-model="period.from" dense outlined type="date" label="De" @update:model-value="emitPeriod" /><q-input v-model="period.to" dense outlined type="date" label="Até" @update:model-value="emitPeriod" /></div><q-btn unelevated no-caps color="primary" icon="add" label="Planejar assunto" @click="openPlanner()" /></div></header>
    <section class="map-summary"><q-card flat><q-card-section><span>Práticas no período</span><strong>{{ map.answered }}</strong></q-card-section></q-card><q-card flat><q-card-section><span>Taxa de acerto</span><strong>{{ map.accuracy === null ? '—' : Math.round(map.accuracy) + '%' }}</strong></q-card-section></q-card><q-card flat><q-card-section><span>Assuntos planejados</span><strong>{{ map.schedule.length }}</strong></q-card-section></q-card><q-card flat><q-card-section><span>Concluídos</span><strong>{{ completedCount }}</strong></q-card-section></q-card></section>
    <q-card flat class="gantt-card"><q-card-section class="gantt-scroll"><div class="gantt"><div class="gantt-head"><div class="subject-col">Assunto / Subassunto</div><div class="metric-col">Práticas</div><div class="timeline"><span v-for="day in timeline" :key="day" class="date-label">{{ shortDate(day) }}</span></div></div><template v-for="row in rows" :key="row.subject.id"><div class="gantt-row" :class="{ parent: row.subject.children.length > 0 }"><div class="subject-col subject-name" :style="{ paddingLeft: (16 + row.subject.depth * 22) + 'px' }"><q-btn v-if="row.subject.children.length" flat round dense size="sm" :icon="expanded[row.subject.id] === false ? 'chevron_right' : 'expand_more'" @click="toggle(row.subject.id)" /><span v-else class="tree-spacer"></span><span class="subject-dot" :class="evidenceClass(row.subject.evidenceStatus)"></span><div><strong>{{ row.subject.name }}</strong><small>{{ row.subject.evidenceStatus === 'NO_DATA' ? 'Sem práticas' : row.subject.correct + '/' + row.subject.answered + ' acertos' }}</small></div></div><div class="metric-col"><q-linear-progress rounded size="7px" :value="(row.subject.accuracy ?? 0) / 100" :color="row.subject.accuracy === null ? 'blue-grey-4' : row.subject.accuracy >= 70 ? 'positive' : 'warning'" /><small>{{ row.subject.accuracy === null ? '—' : Math.round(row.subject.accuracy) + '%' }}</small></div><div class="timeline row-timeline"><span v-for="day in timeline" :key="day" class="grid-day"></span><button v-if="scheduleBySubject[row.subject.id]" class="gantt-bar" :class="scheduleBySubject[row.subject.id].status.toLowerCase()" :style="barStyle(scheduleBySubject[row.subject.id])" :title="barTitle(scheduleBySubject[row.subject.id])" @click="openPlanner(row.subject.id)"><q-icon v-if="scheduleBySubject[row.subject.id].status !== 'PLANNED'" name="check" size="13px" />{{ scheduleBySubject[row.subject.id].status === 'COMPLETED' ? ' Concluído' : '' }}</button><q-btn v-else flat round dense size="sm" icon="add" class="schedule-add" :aria-label="'Planejar ' + row.subject.name" @click="openPlanner(row.subject.id)" /></div></div></template></div></q-card-section></q-card>
    <q-dialog v-model="planner"><q-card class="planner"><q-card-section><div class="text-h6">Planejar assunto</div><div class="text-caption">O item permanece no Gantt mesmo depois de estudado ou concluído.</div></q-card-section><q-card-section class="planner-form"><q-select v-model="form.subjectId" outlined dense emit-value map-options label="Assunto" :options="subjectOptions" /><q-input v-model="form.startDate" outlined dense type="date" label="Início" /><q-input v-model="form.endDate" outlined dense type="date" label="Fim" /><q-select v-model="form.status" outlined dense emit-value map-options label="Estado" :options="statusOptions" /><q-select v-model="form.predecessorSubjectIds" outlined dense multiple emit-value map-options label="Depende de" :options="predecessorOptions" /></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup /><q-btn unelevated no-caps color="primary" label="Salvar cronograma" @click="save" /></q-card-actions></q-card></q-dialog>
  </section>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import type { SaveStudyMapSchedule, StudyMap, StudyMapScheduleItem, StudyMapSubject } from '../../../Domain/Performance/PerformanceRepository'
const props = defineProps<{ map: StudyMap }>()
const emit = defineEmits<{ save: [input: SaveStudyMapSchedule]; periodChange: [from: string | null, to: string | null] }>()
const period = reactive({ from: '', to: '' })
const expanded = reactive<Record<string, boolean>>({})
const planner = ref(false)
const form = reactive<{ subjectId:string; startDate:string; endDate:string; status:'PLANNED'|'STUDIED'|'COMPLETED'; predecessorSubjectIds:string[] }>({ subjectId:'', startDate:new Date().toISOString().slice(0,10), endDate:new Date(Date.now()+6*86400000).toISOString().slice(0,10), status:'PLANNED', predecessorSubjectIds:[] })
const scheduleBySubject = computed<Record<string, StudyMapScheduleItem>>(() => Object.fromEntries(props.map.schedule.map(item => [item.subjectId, item])))
const timeline = computed(() => Array.from({ length: 8 }, (_, index) => { const start = props.map.schedule.map(item => item.startDate).sort()[0] ?? new Date().toISOString().slice(0,10); const date = new Date(start + 'T12:00:00'); date.setDate(date.getDate() + index * 7); return date.toISOString().slice(0,10) }))
function collect(subjects:readonly StudyMapSubject[], output:{subject:StudyMapSubject}[]=[]):{subject:StudyMapSubject}[]{ for(const subject of subjects){ output.push({subject}); if(expanded[subject.id] !== false) collect(subject.children,output) } return output }
const rows = computed(() => collect(props.map.subjects))
const allSubjects = computed(() => collect(props.map.subjects).map(row=>row.subject))
const subjectOptions = computed(() => allSubjects.value.map(subject=>({label:'  '.repeat(subject.depth)+subject.name,value:subject.id})))
const predecessorOptions = computed(() => allSubjects.value.filter(subject=>subject.id!==form.subjectId && scheduleBySubject.value[subject.id]).map(subject=>({label:subject.name,value:subject.id})))
const completedCount = computed(() => props.map.schedule.filter(item=>item.status==='COMPLETED').length)
const statusOptions = [{label:'Planejado',value:'PLANNED'},{label:'Estudado',value:'STUDIED'},{label:'Concluído',value:'COMPLETED'}] as const
function toggle(id:string):void{ expanded[id]=expanded[id]===false }
function openPlanner(subjectId?:string):void{ const current=subjectId?scheduleBySubject.value[subjectId]:undefined; form.subjectId=subjectId??form.subjectId??''; form.startDate=current?.startDate??form.startDate; form.endDate=current?.endDate??form.endDate; form.status=current?.status??'PLANNED'; form.predecessorSubjectIds=[...(current?.predecessorSubjectIds??[])]; planner.value=true }
function emitPeriod():void{ emit('periodChange', period.from || null, period.to || null) }
function save():void{ if(!form.subjectId)return; emit('save',{examId:props.map.examId,subjectId:form.subjectId,startDate:form.startDate,endDate:form.endDate,status:form.status,predecessorSubjectIds:form.predecessorSubjectIds}); planner.value=false }
function shortDate(date:string):string{return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit'}).format(new Date(date+'T12:00:00'))}
function evidenceClass(status:string):string{return status==='SUFFICIENT'?'evidence-good':status==='INSUFFICIENT'?'evidence-mid':'evidence-none'}
function barStyle(item:StudyMapScheduleItem):Record<string,string>{ const start=new Date(timeline.value[0]+'T12:00:00').getTime(); const day=86400000; const offset=Math.max(0,(new Date(item.startDate+'T12:00:00').getTime()-start)/day); const length=Math.max(1,(new Date(item.endDate+'T12:00:00').getTime()-new Date(item.startDate+'T12:00:00').getTime())/day+1); return {left:(offset/56*100)+'%',width:Math.min(100-offset/56*100,length/56*100)+'%'} }
function barTitle(item:StudyMapScheduleItem):string{return item.status+' · '+item.startDate+' a '+item.endDate+(item.predecessorSubjectIds.length?' · '+item.predecessorSubjectIds.length+' dependência(s)':'')}
</script>

<style scoped>
.study-map{margin-top:34px}.map-header{display:flex;align-items:start;justify-content:space-between;gap:20px;margin-bottom:16px}.map-actions{display:flex;align-items:center;gap:10px}.period-controls{display:flex;gap:8px}.period-controls :deep(.q-field){width:142px}.eyebrow{margin:0 0 6px;color:#5d7fae;font-size:11px;font-weight:800;letter-spacing:.1em}.map-header h2{margin:0;color:#142950}.map-header p{margin:7px 0 0;color:#71819e}.map-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.map-summary .q-card,.gantt-card{border:1px solid #dce7f6;border-radius:18px;background:rgba(255,255,255,.88);box-shadow:0 9px 25px rgba(33,58,105,.05)}.map-summary span{display:block;color:#71819e;font-size:12px}.map-summary strong{display:block;margin-top:7px;color:#17305b;font-size:23px}.gantt-scroll{padding:0;overflow:auto}.gantt{min-width:900px}.gantt-head,.gantt-row{display:grid;grid-template-columns:330px 100px minmax(420px,1fr)}.gantt-head{background:#f1f7ff;color:#52729d;font-size:11px;font-weight:800}.gantt-head>div{padding:12px;border-bottom:1px solid #dce7f6}.timeline{display:grid;grid-template-columns:repeat(8,1fr)}.date-label{text-align:center;border-left:1px solid #e0ebf8}.gantt-row{min-height:55px;border-bottom:1px solid #edf2f9}.gantt-row.parent{background:rgba(237,246,255,.64)}.subject-col{display:flex;align-items:center;gap:7px}.subject-name{color:#17305b}.subject-name strong{display:block;font-size:13px}.subject-name small{display:block;margin-top:2px;color:#7890ad;font-size:10px}.tree-spacer{width:30px}.subject-dot{width:8px;height:8px;border-radius:50%}.evidence-good{background:#16a26d}.evidence-mid{background:#e6a524}.evidence-none{background:#bccbdf}.metric-col{display:grid;align-content:center;gap:4px;padding:0 12px}.metric-col small{color:#607d9f;font-size:10px;text-align:right}.row-timeline{position:relative;min-height:55px}.grid-day{border-left:1px solid #edf2f9}.gantt-bar{position:absolute;top:16px;height:23px;border:0;border-radius:6px;background:#3388dc;color:white;font-size:10px;font-weight:700;white-space:nowrap;overflow:hidden;cursor:pointer}.gantt-bar.studied{background:#2aa37c}.gantt-bar.completed{background:#6d8cb3;text-decoration:line-through}.schedule-add{position:absolute;right:6px;top:12px;color:#6b91bc}.planner{width:min(550px,96vw);border-radius:18px}.planner-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.planner-form :first-child,.planner-form :last-child{grid-column:1/-1}@media(max-width:599px){.map-header{display:grid}.map-actions{display:grid}.period-controls{display:grid;grid-template-columns:1fr 1fr}.period-controls :deep(.q-field){width:auto}.map-summary{grid-template-columns:1fr 1fr}.planner-form{grid-template-columns:1fr}.planner-form :first-child,.planner-form :last-child{grid-column:auto}}
</style>
