<template>
  <q-page class="page">
    <section class="top"><div><p class="eyebrow">SEUS ESTUDOS</p><h1 class="page-title">Cadernos e plano</h1><p>Priorize práticas reais e congele a seleção somente quando decidir criar um caderno.</p></div><q-btn unelevated no-caps color="primary" label="Novo caderno" @click="dialog = true" /></section>
    <q-banner v-if="error" rounded class="error">{{ error }}</q-banner><q-inner-loading :showing="loading" color="primary" />
    <q-card v-if="goal" flat class="goal-card"><q-card-section><div><p class="eyebrow">META DA SEMANA</p><h2>{{ goal.completedQuestions }} de {{ goal.weeklyQuestionGoal }} questões</h2><q-linear-progress rounded size="9px" color="primary" track-color="blue-1" :value="goal.percentage / 100" class="q-mt-sm" /><p>{{ Math.round(goal.percentage) }}% concluído desde segunda-feira.</p></div><q-form class="goal-form" @submit.prevent="saveGoal"><q-input v-model.number="weeklyGoal" outlined dense type="number" min="1" max="500" label="Meta semanal" /><q-btn unelevated no-caps color="primary" type="submit" label="Salvar" :loading="goalSaving" /></q-form></q-card-section></q-card>
    <section class="plan-section"><div class="section-heading"><div><p class="eyebrow">PLANO EXPLICÁVEL</p><h2>Prioridades de estudo</h2><p>Baseado apenas em tentativas finais; recomendações não criam cadernos automaticamente.</p></div><q-btn flat no-caps color="primary" label="Atualizar plano" :loading="planning" @click="loadPlan" /></div><q-card v-if="plan?.priorities.length" flat class="plan-card"><q-list separator><q-item v-for="priority in plan.priorities" :key="priority.subjectId"><q-item-section avatar><q-icon :name="priority.sufficientData ? 'insights' : 'hourglass_top'" :color="priority.sufficientData ? 'primary' : 'amber-8'" /></q-item-section><q-item-section><q-item-label>{{ priority.sufficientData ? Math.round(priority.percentage) + '% de acerto' : 'Dados insuficientes' }}</q-item-label><q-item-label caption>{{ priority.reason }}</q-item-label></q-item-section><q-item-section side><q-btn unelevated no-caps color="primary" label="Criar prática" @click="applyPriority(priority.subjectId, priority.sufficientData)" /></q-item-section></q-item></q-list></q-card><q-card v-else-if="!planning" flat class="plan-empty"><q-card-section><q-icon name="auto_graph" size="30px" color="primary" /><div><h2>Seu plano aparece com as primeiras tentativas</h2><p>Conclua questões para receber prioridades acompanhadas de evidências.</p></div></q-card-section></q-card></section>
    <section v-if="!loading && notebooks.length" class="grid"><q-card v-for="book in notebooks" :key="book.id" flat class="book"><q-card-section><div class="book-heading"><div class="mode">{{ book.mode === 'STUDY' ? 'ESTUDO GUIADO' : 'SIMULADO' }}</div><q-badge :color="statusColor(book.status)" :label="statusLabel(book.status)" /></div><h2>{{ book.name }}</h2><p>{{ book.questionIds.length }} questões congeladas para esta sessão.</p><div class="book-footer"><span>{{ formatted(book.createdAt) }}</span><q-btn flat no-caps color="primary" :label="book.status === 'IN_PROGRESS' ? 'Retomar' : book.status === 'FINISHED' ? 'Finalizado' : 'Iniciar'" :disable="book.status === 'FINISHED'" @click="emit('open', book.id)" /></div></q-card-section></q-card></section>
    <q-card v-else-if="!loading" flat class="empty"><q-card-section><q-img src="/images/concursos-study-mark.png" width="86px" height="86px" fit="contain" /><div><h2>Organize sua prática</h2><p>Crie um caderno usando as questões publicadas no banco.</p><q-btn unelevated no-caps color="primary" label="Criar caderno" @click="dialog = true" /></div></q-card-section></q-card>
    <q-dialog v-model="dialog" persistent><q-card class="dialog-card"><q-card-section><div class="dialog-title"><div><p class="eyebrow">NOVA SELEÇÃO</p><h2>Criar caderno</h2></div><q-btn flat round icon="close" aria-label="Fechar" @click="dialog = false" /></div><q-banner v-if="form.subjectId" rounded class="recommendation">Esta prática usará o assunto recomendado. A seleção será congelada após a confirmação.</q-banner></q-card-section><q-form @submit.prevent="save"><q-card-section class="q-gutter-md"><q-input v-model="form.name" outlined label="Nome do caderno" :rules="[(value) => !!value || 'Informe um nome']" /><q-select v-model="form.mode" outlined label="Modo" :options="modeOptions" emit-value map-options /><q-input v-model.number="form.quantity" outlined type="number" min="1" max="100" label="Quantidade de questões" /><q-input v-model="form.board" outlined label="Banca (opcional)" /><q-input v-model.number="form.year" outlined type="number" label="Ano (opcional)" /><q-select v-model="form.difficulty" clearable outlined label="Dificuldade (opcional)" :options="difficultyOptions" emit-value map-options /><p class="hint">A API seleciona somente questões publicadas e preserva a composição do caderno.</p></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" @click="dialog = false" /><q-btn unelevated no-caps color="primary" type="submit" label="Criar caderno" :loading="saving" /></q-card-actions></q-form></q-card></q-dialog>
  </q-page>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import type { NotebookMode, NotebookStatus } from '../../../Domain/Study/StudyRepository'
import { useNotebooks } from './useNotebooks'
const emit = defineEmits<{ open: [id: string] }>()
const { create, error, goal, goalSaving, load, loadGoal, loadPlan, loading, notebooks, plan, planning, saving, updateGoal } = useNotebooks()
const weeklyGoal = ref(20)
const dialog = ref(false)
const form = reactive<{ name:string; mode:NotebookMode; quantity:number; board:string; year:number|null; difficulty:''|'EASY'|'MEDIUM'|'HARD'; subjectId:string|null }>({ name:'', mode:'STUDY', quantity:10, board:'', year:null, difficulty:'', subjectId:null })
const modeOptions = [{ label:'Estudo guiado', value:'STUDY' }, { label:'Simulado', value:'EXAM' }]
const difficultyOptions = [{ label:'Fácil', value:'EASY' }, { label:'Média', value:'MEDIUM' }, { label:'Difícil', value:'HARD' }]
async function saveGoal(): Promise<void> { if (await updateGoal(weeklyGoal.value) && goal.value) weeklyGoal.value = goal.value.weeklyQuestionGoal }
async function save(): Promise<void> { const created = await create({ name:form.name, mode:form.mode, quantity:form.quantity, filters:{ ...(form.subjectId ? { subjectId:form.subjectId } : {}), ...(form.board.trim() ? { board:form.board.trim() } : {}), ...(form.year ? { year:form.year } : {}), ...(form.difficulty ? { difficulty:form.difficulty } : {}) } }); if (!created) return; dialog.value=false; form.name=''; form.board=''; form.year=null; form.difficulty=''; form.subjectId=null }
function applyPriority(subjectId:string, sufficient:boolean): void { form.subjectId=subjectId; form.name=sufficient?'Prática recomendada':'Prática para ampliar amostra'; form.mode='STUDY'; form.quantity=10; dialog.value=true }
function statusLabel(status:NotebookStatus):string { return status==='IN_PROGRESS'?'EM ANDAMENTO':status==='FINISHED'?'FINALIZADO':'PRONTO PARA INICIAR' }
onMounted(async()=>{ await load(); await Promise.all([loadPlan(), loadGoal()]); if (goal.value) weeklyGoal.value=goal.value.weeklyQuestionGoal })
function statusColor(status:NotebookStatus):string { return status==='IN_PROGRESS'?'positive':status==='FINISHED'?'grey-6':'primary' }
function formatted(value:string):string { return new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium'}).format(new Date(value)) }
</script>
<style scoped>
.page{max-width:1240px;margin:auto;padding:42px 34px}.top,.section-heading{display:flex;justify-content:space-between;align-items:center;gap:20px}.top{margin-bottom:29px}.eyebrow{margin:0 0 7px;color:#7187ad;font-size:11px;font-weight:800;letter-spacing:.1em}.top h1,.dialog-card h2,.section-heading h2,.plan-empty h2{margin:0;color:#142950}.top p:not(.eyebrow),.section-heading p{margin:9px 0 0;color:#71819e}.plan-section{margin-bottom:28px}.section-heading{margin-bottom:14px}.plan-card,.plan-empty,.book,.empty{border:1px solid #e5ecf6;border-radius:18px;background:#fff;box-shadow:0 8px 26px rgba(33,58,105,.045)}.plan-empty :deep(.q-card__section),.empty :deep(.q-card__section){display:flex;align-items:center;gap:20px;padding:30px}.plan-empty h2{font-size:17px}.plan-empty p,.empty p,.hint{color:#71819e}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.book{min-height:214px;border-top:3px solid #4b7cf0}.book-heading,.book-footer,.dialog-title{display:flex;justify-content:space-between;gap:8px}.mode{color:#2b6ed2;font-size:10px;font-weight:800;letter-spacing:.1em}.book h2{margin:18px 0 7px;color:#19315b;font-size:19px}.book p{color:#71819e}.book-footer{align-items:center;margin-top:22px;color:#8290a9;font-size:12px}.dialog-card{width:min(520px,calc(100vw - 32px));border-radius:18px}.recommendation{margin-top:16px;background:#edf5ff;color:#285b9f}.error{margin-bottom:14px;background:#fff3f2;color:#ae2f25}@media(max-width:850px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.page{padding:28px 16px}.top,.section-heading{align-items:flex-start;flex-direction:column}.top .q-btn,.section-heading .q-btn{width:100%}.grid{grid-template-columns:1fr}.empty :deep(.q-card__section){align-items:flex-start;flex-direction:column}}
</style>
