<template>
  <q-page class="page">
    <section class="top"><div><p class="eyebrow">SEUS ESTUDOS</p><h1 class="page-title">Cadernos e plano</h1><p>Priorize práticas reais e congele a seleção somente quando decidir criar um caderno.</p></div><q-btn unelevated no-caps color="primary" icon="add" label="Novo plano" @click="planDialog = true" /></section>
    <q-banner v-if="error" rounded class="error">{{ error }}</q-banner><q-inner-loading :showing="loading" color="primary" />
    <q-card v-if="goal" flat class="goal-card weekly-card"><q-card-section class="weekly-title"><div class="section-label"><q-icon name="event" color="primary" /><strong>Meta da semana</strong></div><q-chip dense square color="blue-1" text-color="primary" icon="date_range">{{ weekLabel }}</q-chip></q-card-section><q-card-section class="weekly-body"><div class="goal-ring" :style="{ '--progress': goal.percentage + '%' }"><strong>{{ goal.completedQuestions }} / {{ goal.weeklyQuestionGoal }}</strong><span>questões</span></div><div class="weekly-summary"><h2>{{ Math.round(goal.percentage) }}% concluído</h2><p>Você já respondeu {{ goal.completedQuestions }} de {{ goal.weeklyQuestionGoal }} questões esta semana.</p><q-linear-progress rounded size="10px" color="primary" track-color="blue-1" :value="goal.percentage / 100" /><div class="goal-metrics"><span><q-icon name="check_circle" color="positive" />{{ goal.completedQuestions }} respondidas</span><span><q-icon name="flag" color="primary" />{{ remainingQuestions }} restantes</span><span><q-icon name="menu_book" color="primary" />{{ activeCount }} em andamento</span></div></div></q-card-section></q-card><q-card v-if="goal" flat class="goal-editor"><q-card-section><div><div class="section-label"><q-icon name="assignment" color="primary" /><strong>Meta semanal</strong></div><p>Defina quantas questões deseja resolver nesta semana.</p></div><q-form class="goal-form" @submit.prevent="saveGoal"><q-input v-model.number="weeklyGoal" outlined dense type="number" min="1" max="500" aria-label="Meta semanal" :disable="!goal" /><q-btn unelevated no-caps color="primary" type="submit" label="Salvar meta" :loading="goalSaving" /></q-form></q-card-section></q-card>
    <section class="plan-section"><div class="section-heading"><div><p class="eyebrow">PLANO EXPLICÁVEL</p><h2>Prioridades de estudo</h2><p>Baseado apenas em tentativas finais; recomendações não criam cadernos automaticamente.</p></div><q-btn flat no-caps color="primary" label="Atualizar plano" :loading="planning" @click="loadPlan" /></div><q-card v-if="plan?.priorities.length" flat class="plan-card"><q-list separator><q-item v-for="priority in plan.priorities" :key="priority.subjectId"><q-item-section avatar><q-icon :name="priority.sufficientData ? 'insights' : 'hourglass_top'" :color="priority.sufficientData ? 'primary' : 'amber-8'" /></q-item-section><q-item-section><q-item-label>{{ priority.sufficientData ? Math.round(priority.percentage) + '% de acerto' : 'Dados insuficientes' }}</q-item-label><q-item-label caption>{{ priority.reason }}</q-item-label></q-item-section><q-item-section side><q-btn unelevated no-caps color="primary" label="Criar prática" @click="applyPriority(priority.subjectId, priority.sufficientData)" /></q-item-section></q-item></q-list></q-card><q-card v-else-if="!planning" flat class="plan-empty"><q-card-section><q-icon name="auto_graph" size="30px" color="primary" /><div><h2>Seu plano aparece com as primeiras tentativas</h2><p>Conclua questões para receber prioridades acompanhadas de evidências.</p></div></q-card-section></q-card></section>
    <section class="directed-section"><div class="section-heading"><div><p class="eyebrow">ESTUDO DIRECIONADO</p><h2>Planos por concurso</h2><p>Seu concurso e cargo ficam definidos. Ao criar um caderno, escolha somente todos os assuntos ou uma seleção.</p></div><q-btn flat no-caps color="primary" icon="add" label="Novo plano" @click="planDialog = true" /></div><q-card v-if="directedPlans.length" flat class="plan-card"><q-list separator><q-item v-for="item in directedPlans" :key="item.id"><q-item-section avatar><q-icon name="track_changes" color="primary" /></q-item-section><q-item-section><q-item-label>{{ item.name }}</q-item-label><q-item-label caption>{{ planCaption(item) }}</q-item-label></q-item-section><q-item-section side><q-btn flat no-caps color="primary" label="Ver painel" @click="emit('performance', item.examId)" /><q-btn unelevated no-caps color="primary" label="Criar caderno" @click="openPlan(item)" /></q-item-section></q-item></q-list></q-card><q-card v-else flat class="plan-empty"><q-card-section><q-icon name="track_changes" size="30px" color="primary"/><div><h2>Direcione seu estudo</h2><p>Crie um plano para um concurso e cargo pretendidos.</p></div></q-card-section></q-card></section>
    <div class="notebook-toolbar"><q-tabs :model-value="notebookFilter" dense no-caps active-color="primary" indicator-color="primary" align="left"><q-tab name="ALL" :label="'Todos (' + total + ')'" @click="selectNotebookFilter('ALL')" /><q-tab name="ACTIVE" :label="'Em andamento (' + activeCount + ')'" @click="selectNotebookFilter('ACTIVE')" /><q-tab name="FINISHED" :label="'Finalizados (' + finishedCount + ')'" @click="selectNotebookFilter('FINISHED')" /></q-tabs><q-input v-model="notebookSearch" dense outlined placeholder="Buscar cadernos..." aria-label="Buscar cadernos"><template #prepend><q-icon name="search" /></template></q-input></div><section v-if="!loading && visibleNotebooks.length" class="grid"><q-card v-for="book in visibleNotebooks" :key="book.id" flat class="book"><q-card-section><div class="book-heading"><div class="mode">{{ book.mode === 'STUDY' ? 'ESTUDO GUIADO' : 'SIMULADO' }}</div><q-badge :color="statusColor(book.status)" :label="statusLabel(book.status)" /></div><h2>{{ book.name }}</h2><p>{{ book.questionIds.length }} questões congeladas para esta sessão.</p><div class="book-footer"><span>{{ formatted(book.createdAt) }}</span><q-btn flat no-caps color="primary" :label="book.status === 'IN_PROGRESS' ? 'Retomar' : book.status === 'FINISHED' ? 'Finalizado' : 'Iniciar'" :disable="book.status === 'FINISHED'" @click="emit('open', book.id)" /></div></q-card-section></q-card></section>
    <q-card v-else-if="!loading" flat class="empty"><q-card-section><q-img src="/images/concursos-study-mark.png" width="86px" height="86px" fit="contain" /><div><h2>Organize sua prática</h2><p>Crie um caderno usando as questões publicadas no banco.</p><q-btn unelevated no-caps color="primary" label="Criar caderno" @click="dialog = true" /></div></q-card-section></q-card>
    <q-dialog v-model="dialog" persistent><q-card class="dialog-card"><q-card-section><div class="dialog-title"><div><p class="eyebrow">NOVA SELEÇÃO</p><h2>Criar caderno</h2></div><q-btn flat round icon="close" aria-label="Fechar" @click="dialog = false" /></div><q-banner v-if="form.subjectId" rounded class="recommendation">Esta prática usará o assunto recomendado. A seleção será congelada após a confirmação.</q-banner></q-card-section><q-form @submit.prevent="save"><q-card-section class="q-gutter-md"><q-input v-if="!activePlan" v-model="form.name" outlined label="Nome do caderno" :rules="[(value) => !!value || 'Informe um nome']" /><template v-if="!activePlan"><q-select v-model="form.examId" outlined label="Concurso pretendido *" :options="contestOptions" emit-value map-options @update:model-value="onContestChange" /><q-select v-model="form.positionId" outlined label="Cargo pretendido *" :disable="!form.examId" :options="positionOptions" emit-value map-options @update:model-value="onPositionChange" /></template><q-banner v-else rounded class="recommendation">Plano: <strong>{{ activePlan.name }}</strong>. Concurso e cargo já estão definidos.</q-banner><q-option-group v-model="form.subjectScope" inline type="radio" color="primary" :disable="!form.positionId" :options="subjectScopeOptions" /><q-select v-if="form.subjectScope === 'SPECIFIC'" v-model="form.subjectIds" outlined multiple use-chips label="Assuntos específicos" :disable="!form.positionId" :options="subjectOptions" emit-value map-options /><q-banner v-else rounded class="recommendation">Todos os assuntos do cargo serão considerados. A distribuição respeitará os pesos do concurso.</q-banner><template v-if="!activePlan"><q-select v-model="form.mode" outlined label="Modo" :options="modeOptions" emit-value map-options /><q-input v-model.number="form.quantity" outlined type="number" min="1" max="100" label="Quantidade de questões" /><q-input v-model="form.board" outlined label="Banca (opcional)" /><q-input v-model.number="form.year" outlined type="number" label="Ano (opcional)" /><q-select v-model="form.difficulty" clearable outlined label="Dificuldade (opcional)" :options="difficultyOptions" emit-value map-options /></template><p class="hint">A API seleciona somente questões publicadas e preserva a composição do caderno.</p></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" @click="dialog = false" /><q-btn unelevated no-caps color="primary" type="submit" label="Criar caderno" :loading="saving" /></q-card-actions></q-form></q-card></q-dialog>
    <q-dialog v-model="planDialog" persistent><q-card class="dialog-card"><q-card-section><div class="dialog-title"><div><p class="eyebrow">ESTUDO DIRECIONADO</p><h2>Novo plano</h2><p>Escolha o concurso e o cargo que deseja conquistar.</p></div><q-btn flat round icon="close" aria-label="Fechar" @click="planDialog = false" /></div></q-card-section><q-form @submit.prevent="saveDirectedPlan"><q-card-section class="q-gutter-md"><q-input v-model="planForm.name" outlined label="Nome do plano" /><q-select v-model="planForm.examId" outlined label="Concurso *" :options="contestOptions" emit-value map-options @update:model-value="onPlanContestChange" /><q-select v-model="planForm.positionId" outlined label="Cargo *" :disable="!planForm.examId" :options="positionOptions" emit-value map-options /></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" @click="planDialog=false"/><q-btn unelevated no-caps color="primary" type="submit" label="Criar plano"/></q-card-actions></q-form></q-card></q-dialog>
  </q-page>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import type { NotebookMode, NotebookStatus } from '../../../Domain/Study/StudyRepository'
import { useNotebooks } from './useNotebooks'
const emit = defineEmits<{ open: [id: string]; performance: [examId: string] }>()
const { activeCount, directedPlans, loadDirectedPlans, createDirectedPlan, contests, positions, contestSubjects, loadStudyContests, loadPositionSubjects, loadPositions, create, error, finishedCount, goal, goalSaving, load, loadGoal, loadPlan, loading, notebookFilter, notebookSearch, notebooks, plan, planning, saving, selectNotebookFilter, total, updateGoal, visibleNotebooks } = useNotebooks()
const weeklyGoal = ref<number | null>(null)
const dialog = ref(false)
const planDialog = ref(false)
const activePlan = ref<{ id:string; examId:string; positionId:string; name:string } | null>(null)
const planForm = reactive<{ name:string; examId:string|null; positionId:string|null }>({ name:'', examId:null, positionId:null })
const form = reactive<{ name:string; mode:NotebookMode; quantity:number; board:string; year:number|null; difficulty:''|'EASY'|'MEDIUM'|'HARD'; subjectId:string|null; subjectIds:string[]; subjectScope:'ALL'|'SPECIFIC'; examId:string|null; positionId:string|null }>({ name:'', mode:'STUDY', quantity:10, board:'', year:null, difficulty:'', subjectId:null, subjectIds:[], subjectScope:'ALL', examId:null, positionId:null })
const modeOptions = [{ label:'Estudo guiado', value:'STUDY' }, { label:'Simulado', value:'EXAM' }]
const difficultyOptions = [{ label:'Fácil', value:'EASY' }, { label:'Média', value:'MEDIUM' }, { label:'Difícil', value:'HARD' }]
const subjectScopeOptions = [{ label:'Todos os assuntos do cargo', value:'ALL' }, { label:'Escolher assuntos', value:'SPECIFIC' }]
async function saveGoal(): Promise<void> { if (weeklyGoal.value !== null && await updateGoal(weeklyGoal.value) && goal.value) weeklyGoal.value = goal.value.weeklyQuestionGoal }
const contestOptions = computed(() => contests.value.map(item => ({ label: item.name + (item.year ? ' · ' + item.year : ''), value: item.id })))
const positionOptions = computed(() => positions.value.map(item => ({ label: item.name + (item.emphasis ? ' · ' + item.emphasis : ''), value: item.id })))
const subjectOptions = computed(() => contestSubjects.value.map(item => ({ label: '· '.repeat(item.level) + item.name + ' · peso ' + Number(item.selectionWeight).toFixed(2), value: item.id })))
async function onPlanContestChange(): Promise<void> { planForm.positionId=null; await loadPositions(planForm.examId || '') }
async function saveDirectedPlan(): Promise<void> { if(!planForm.name.trim()||!planForm.examId||!planForm.positionId)return; const item=await createDirectedPlan({name:planForm.name,examId:planForm.examId,positionId:planForm.positionId});if(!item)return;planDialog.value=false;planForm.name='';planForm.examId=null;planForm.positionId=null }
async function openPlan(item:{id:string;examId:string;positionId:string;name:string}): Promise<void> { activePlan.value=item;form.name='Prática · '+item.name;form.mode='STUDY';form.quantity=20;form.board='';form.year=null;form.difficulty='';form.examId=item.examId;form.positionId=item.positionId;form.subjectIds=[];form.subjectScope='ALL';await loadPositionSubjects(item.positionId);dialog.value=true }
function planCaption(item:{examId:string;positionId:string}):string { const exam=contests.value.find(value=>value.id===item.examId); const position=positions.value.find(value=>value.id===item.positionId); return (exam?.name??'Concurso')+' · '+(position?.name??'Cargo') }
async function onContestChange(): Promise<void> { form.positionId = null; form.subjectIds = []; await loadPositions(form.examId || '') }
async function onPositionChange(): Promise<void> { form.subjectIds = []; await loadPositionSubjects(form.positionId || '') }
async function save(): Promise<void> { if (!form.examId || !form.positionId || (form.subjectScope === 'SPECIFIC' && form.subjectIds.length === 0)) return; const created = await create({ name:form.name, mode:form.mode, quantity:form.quantity, filters:{ examId:form.examId, positionId:form.positionId, ...(form.subjectScope === 'SPECIFIC' ? { subjectIds:form.subjectIds } : {}), ...(form.subjectId ? { subjectId:form.subjectId } : {}), ...(form.board.trim() ? { board:form.board.trim() } : {}), ...(form.year ? { year:form.year } : {}), ...(form.difficulty ? { difficulty:form.difficulty } : {}) } }); if (!created) return; dialog.value=false; form.name=''; form.board=''; form.year=null; form.difficulty=''; form.subjectId=null; form.subjectIds=[]; form.subjectScope='ALL'; form.examId=null; form.positionId=null }
function applyPriority(subjectId:string, sufficient:boolean): void { form.subjectId=subjectId; form.name=sufficient?'Prática recomendada':'Prática para ampliar amostra'; form.mode='STUDY'; form.quantity=10; dialog.value=true }
function statusLabel(status:NotebookStatus):string { return status==='IN_PROGRESS'?'EM ANDAMENTO':status==='FINISHED'?'FINALIZADO':'PRONTO PARA INICIAR' }
onMounted(async()=>{ await load(); await loadStudyContests(); await loadDirectedPlans(); await Promise.all([loadPlan(), loadGoal()]); if (goal.value) weeklyGoal.value=goal.value.weeklyQuestionGoal })
function statusColor(status:NotebookStatus):string { return status==='IN_PROGRESS'?'positive':status==='FINISHED'?'grey-6':'primary' }
function formatted(value:string):string { return new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium'}).format(new Date(value)) }
const remainingQuestions = computed(() => Math.max(0, (goal.value?.weeklyQuestionGoal ?? 0) - (goal.value?.completedQuestions ?? 0)))
const weekLabel = computed(() => { if (!goal.value) return ''; const start = new Date(goal.value.periodStartsAt); const end = new Date(start); end.setDate(start.getDate() + 6); const format = new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }); return format.format(start) + ' – ' + format.format(end) })
</script>
<style scoped>
.page{max-width:1240px;margin:auto;padding:42px 34px}.top,.section-heading{display:flex;justify-content:space-between;align-items:center;gap:20px}.top{margin-bottom:29px}.eyebrow{margin:0 0 7px;color:#7187ad;font-size:11px;font-weight:800;letter-spacing:.1em}.top h1,.dialog-card h2,.section-heading h2,.plan-empty h2{margin:0;color:#142950}.top p:not(.eyebrow),.section-heading p{margin:9px 0 0;color:#71819e}.plan-section{margin-bottom:28px}.section-heading{margin-bottom:14px}.plan-card,.plan-empty,.book,.empty{border:1px solid #e5ecf6;border-radius:18px;background:#fff;box-shadow:0 8px 26px rgba(33,58,105,.045)}.plan-empty :deep(.q-card__section),.empty :deep(.q-card__section){display:flex;align-items:center;gap:20px;padding:30px}.plan-empty h2{font-size:17px}.plan-empty p,.empty p,.hint{color:#71819e}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.book{min-height:214px;border-top:3px solid #4b7cf0}.book-heading,.book-footer,.dialog-title{display:flex;justify-content:space-between;gap:8px}.mode{color:#2b6ed2;font-size:10px;font-weight:800;letter-spacing:.1em}.book h2{margin:18px 0 7px;color:#19315b;font-size:19px}.book p{color:#71819e}.book-footer{align-items:center;margin-top:22px;color:#8290a9;font-size:12px}.dialog-card{width:min(520px,calc(100vw - 32px));border-radius:18px}.recommendation{margin-top:16px;background:#edf5ff;color:#285b9f}.error{margin-bottom:14px;background:#fff3f2;color:#ae2f25}@media(max-width:850px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.page{padding:28px 16px}.top,.section-heading{align-items:flex-start;flex-direction:column}.top .q-btn,.section-heading .q-btn{width:100%}.grid{grid-template-columns:1fr}.empty :deep(.q-card__section){align-items:flex-start;flex-direction:column}}
.goal-editor{margin:12px 0 28px}.goal-editor :deep(.q-card__section){display:flex;align-items:center;justify-content:space-between;gap:20px;padding:16px 20px}.goal-editor p{margin:5px 0 0;color:#71819e;font-size:12px}.goal-form{display:flex;align-items:center;gap:9px}.goal-form .q-field{width:150px}.weekly-card{overflow:hidden}.weekly-title{display:flex;align-items:center;justify-content:space-between;padding:17px 20px 8px}.section-label{display:flex;align-items:center;gap:8px;color:#142950;font-size:15px}.weekly-body{display:flex;align-items:center;gap:28px;padding:9px 20px 20px}.goal-ring{display:grid;place-content:center;flex:0 0 150px;width:150px;height:150px;border-radius:50%;background:radial-gradient(closest-side,#fff 77%,transparent 78%),conic-gradient(#1469f5 var(--progress),#e7f0fb 0);color:#142950;text-align:center}.goal-ring strong{font-size:23px}.goal-ring span{color:#617ba6;font-size:11px}.weekly-summary{flex:1}.weekly-summary h2{margin:0;color:#142950;font-size:22px}.weekly-summary>p{margin:7px 0 13px;color:#637da8;font-size:13px}.goal-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:14px}.goal-metrics span{padding:10px;border:1px solid #e5edf8;border-radius:9px;background:#fbfdff;color:#49668f;font-size:11px}.goal-metrics .q-icon{margin-right:5px}.notebook-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:27px 0 14px}.notebook-toolbar .q-field{width:220px}.book{border-top:3px solid #2d75f4}.book :deep(.q-card__section){padding:19px}.book h2{font-size:18px}.book-footer .q-btn{border:1px solid #cfe0fa;border-radius:8px}.plan-card{border-radius:14px}.plan-empty{border-radius:14px}@media(max-width:700px){.weekly-body{align-items:flex-start;flex-direction:column}.goal-metrics{width:100%}.notebook-toolbar{align-items:flex-start;flex-direction:column}.notebook-toolbar .q-field{width:100%}}@media(max-width:560px){.goal-ring{flex-basis:118px;width:118px;height:118px}.goal-metrics{grid-template-columns:1fr}.notebook-toolbar :deep(.q-tabs){width:100%;overflow:auto}.notebook-toolbar :deep(.q-tab){min-width:auto;padding:0 8px;font-size:10px}}</style>
