import { computed, onBeforeUnmount, readonly, ref } from 'vue'
import type { PublishedQuestion } from '../../../Domain/QuestionBank/QuestionRepository'
import type { Notebook, NotebookStatistics } from '../../../Domain/Study/StudyRepository'
import { performanceUseCases, studyUseCases } from '../../../Infrastructure/Container'
const zero: NotebookStatistics={total:0,answered:0,correct:0,incorrect:0,percentage:0,averageElapsedSeconds:0,elapsedSeconds:0,answeredQuestionIds:[]}
const clock=(s:number):string=>[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(v=>String(v).padStart(2,'0')).join(':')
export function useNotebookExecution(){
 const loading=ref(false),savingAnswer=ref(false),finishing=ref(false),pausing=ref(false),error=ref(''),notice=ref(''),notebook=ref<Notebook|null>(null),questions=ref<readonly PublishedQuestion[]>([]),currentIndex=ref(0),selectedOptions=ref<Record<string,string>>({}),statistics=ref<NotebookStatistics>(zero),now=ref(Date.now());let timer:ReturnType<typeof setInterval>|undefined
 const currentQuestion=computed(()=>questions.value[currentIndex.value]??null),totalQuestions=computed(()=>questions.value.length)
 const elapsedSeconds=computed(()=>{const n=notebook.value;if(!n)return 0;return (n.durationSeconds??0)+(n.status==='IN_PROGRESS'&&n.startedAt?Math.max(0,Math.floor((now.value-new Date(n.startedAt).getTime())/1000)):0)})
 const elapsed=computed(()=>clock(elapsedSeconds.value)),progress=computed(()=>totalQuestions.value?statistics.value.answered/totalQuestions.value:0),isCurrentAnswered=computed(()=>!!currentQuestion.value&&statistics.value.answeredQuestionIds.includes(currentQuestion.value.id))
 const stop=()=>{if(timer)clearInterval(timer);timer=undefined};const tick=()=>{now.value=Date.now()};const run=()=>{stop();tick();timer=setInterval(tick,1000)}
 async function refresh(id:string){statistics.value=await studyUseCases.statistics.execute(id)}
 async function load(id:string){loading.value=true;error.value='';try{let book=await studyUseCases.get.execute(id);if(book.status==='DRAFT')book=await studyUseCases.start.execute(id);const [page]=await Promise.all([studyUseCases.listQuestions.execute(id,{page:1,perPage:100}),refresh(id)]);notebook.value=book;questions.value=page.items;if(book.status==='IN_PROGRESS')run()}catch(e){error.value=e instanceof Error?e.message:'Não foi possível abrir este caderno.'}finally{loading.value=false}}
 const previous=()=>{currentIndex.value=Math.max(0,currentIndex.value-1);notice.value=''};const next=()=>{currentIndex.value=Math.min(totalQuestions.value-1,currentIndex.value+1);notice.value=''}
 const selectOption=(id:string)=>{if(currentQuestion.value&&!isCurrentAnswered.value)selectedOptions.value={...selectedOptions.value,[currentQuestion.value.id]:id}}
 async function submitCurrent(){if(!notebook.value||!currentQuestion.value)return false;const option=selectedOptions.value[currentQuestion.value.id];if(!option){error.value='Escolha uma alternativa antes de confirmar.';return false}savingAnswer.value=true;error.value='';try{await performanceUseCases.submitAnswer.execute(notebook.value.id,currentQuestion.value.id,option,elapsedSeconds.value);await refresh(notebook.value.id);notice.value='Resposta registrada.';return true}catch(e){error.value=e instanceof Error?e.message:'Não foi possível registrar a resposta.';return false}finally{savingAnswer.value=false}}
 async function togglePause(){if(!notebook.value)return;pausing.value=true;try{notebook.value=notebook.value.status==='IN_PROGRESS'?await studyUseCases.pause.execute(notebook.value.id):await studyUseCases.start.execute(notebook.value.id);if(notebook.value.status==='IN_PROGRESS')run();else stop();await refresh(notebook.value.id)}catch(e){error.value=e instanceof Error?e.message:'Não foi possível alterar o contador.'}finally{pausing.value=false}}
 async function finish(){if(!notebook.value)return false;finishing.value=true;try{notebook.value=await studyUseCases.finish.execute(notebook.value.id);stop();return true}catch(e){error.value=e instanceof Error?e.message:'Não foi possível finalizar este caderno.';return false}finally{finishing.value=false}}
 onBeforeUnmount(stop);return{currentIndex:readonly(currentIndex),currentQuestion:readonly(currentQuestion),elapsed:readonly(elapsed),error:readonly(error),finish,finishing:readonly(finishing),isCurrentAnswered:readonly(isCurrentAnswered),load,loading:readonly(loading),next,notebook:readonly(notebook),notice:readonly(notice),pausing:readonly(pausing),previous,progress:readonly(progress),savingAnswer:readonly(savingAnswer),selectOption,selectedOptions:readonly(selectedOptions),statistics:readonly(statistics),submitCurrent,togglePause,totalQuestions:readonly(totalQuestions)}
}
