import { computed, onBeforeUnmount, readonly, ref } from 'vue'
import type { PublishedQuestion } from '../../../Domain/QuestionBank/QuestionRepository'
import type { Notebook, NotebookStatistics } from '../../../Domain/Study/StudyRepository'
import { performanceUseCases, studyUseCases } from '../../../Infrastructure/Container'
const zero: NotebookStatistics={total:0,answered:0,correct:0,incorrect:0,percentage:0,averageElapsedSeconds:0,elapsedSeconds:0,answeredQuestionIds:[]}
const clock=(s:number):string=>[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(v=>String(v).padStart(2,'0')).join(':')
export function useNotebookExecution(){
 const loading=ref(false),savingAnswer=ref(false),finishing=ref(false),pausing=ref(false),error=ref(''),notice=ref(''),notebook=ref<Notebook|null>(null),questions=ref<readonly PublishedQuestion[]>([]),currentIndex=ref(0),selectedOptions=ref<Record<string,string>>({}),statistics=ref<NotebookStatistics>(zero),now=ref(Date.now());let timer:ReturnType<typeof setInterval>|undefined
 const currentQuestion=computed(()=>questions.value[currentIndex.value]??null),totalQuestions=computed(()=>questions.value.length)
 const elapsedSeconds=computed(()=>{const n=notebook.value;if(!n)return 0;return (n.durationSeconds??0)+(n.status==='IN_PROGRESS'&&n.startedAt?Math.max(0,Math.floor((now.value-new Date(n.startedAt).getTime())/1000)):0)})
 const elapsed=computed(()=>clock(elapsedSeconds.value)),progress=computed(()=>totalQuestions.value?statistics.value.answered/totalQuestions.value:0),isCurrentAnswered=computed(()=>!!currentQuestion.value&&statistics.value.answeredQuestionIds.includes(currentQuestion.value.id))
 const stop=()=>{if(timer)clearInterval(timer);timer=undefined};const tick=()=>{now.value=Date.now()};const run=()=>{stop();tick();timer=setInterval(tick,1000)}
 async function refresh(id:string){statistics.value=await studyUseCases.statistics.execute(id)}
 async function load(id:string){loading.value=true;error.value='';try{let book=await studyUseCases.get.execute(id);if(book.status==='DRAFT')book=await studyUseCases.start.execute(id);const [page]=await Promise.all([studyUseCases.listQuestions.execute(id,{page:1,perPage:100}),refresh(id)]);notebook.value=book;questions.value=page.items;const restoredIndex=book.activeQuestionId?questions.value.findIndex(question=>question.id===book.activeQuestionId):-1;if(restoredIndex>=0)currentIndex.value=restoredIndex;if(book.status==='IN_PROGRESS')run()}catch(e){error.value=e instanceof Error?e.message:'Não foi possível abrir este caderno.'}finally{loading.value=false}}
 async function refreshQuestions(id:string):Promise<void>{const currentQuestionId=currentQuestion.value?.id;try{const page=await studyUseCases.listQuestions.execute(id,{page:1,perPage:100});questions.value=page.items;const preservedIndex=currentQuestionId?questions.value.findIndex(question=>question.id===currentQuestionId):-1;currentIndex.value=preservedIndex>=0?preservedIndex:Math.min(currentIndex.value,Math.max(0,questions.value.length-1))}catch(e){error.value=e instanceof Error?e.message:'Não foi possível atualizar o conteúdo editorial deste caderno.'}}
 const previous=()=>goTo(currentIndex.value-1);const next=()=>goTo(currentIndex.value+1);const subjectAt=(index:number):string|null=>questions.value[index]?.taxonomySubjectIds?.[0]??null;const hasNextSubject=computed(()=>{const current=subjectAt(currentIndex.value);return questions.value.slice(currentIndex.value+1).some(question=>(question.taxonomySubjectIds?.[0]??null)!==current)});const hasPreviousSubject=computed(()=>{const current=subjectAt(currentIndex.value);return questions.value.slice(0,currentIndex.value).some(question=>(question.taxonomySubjectIds?.[0]??null)!==current)});const nextSubject=()=>{const current=subjectAt(currentIndex.value);const index=questions.value.findIndex((question,i)=>i>currentIndex.value&&(question.taxonomySubjectIds?.[0]??null)!==current);if(index>=0)goTo(index)};const previousSubject=()=>{const current=subjectAt(currentIndex.value);for(let index=currentIndex.value-1;index>=0;index-=1){if(subjectAt(index)!==current){goTo(index);return}}};const goTo=(index:number)=>{currentIndex.value=Math.max(0,Math.min(totalQuestions.value-1,index));notice.value="";if(notebook.value&&currentQuestion.value)void studyUseCases.setActiveQuestion.execute(notebook.value.id,currentQuestion.value.id).then(book=>{notebook.value=book}).catch(()=>undefined)}
 const selectOption=(id:string)=>{if(currentQuestion.value&&!isCurrentAnswered.value&&notebook.value?.status==='IN_PROGRESS')selectedOptions.value={...selectedOptions.value,[currentQuestion.value.id]:id}}
 async function submitCurrent(){if(!notebook.value||!currentQuestion.value)return false;if(notebook.value.status!=='IN_PROGRESS'){error.value='Retome o caderno para responder questões.';return false;}const option=selectedOptions.value[currentQuestion.value.id];if(!option){error.value='Escolha uma alternativa antes de confirmar.';return false}savingAnswer.value=true;error.value='';try{await performanceUseCases.submitAnswer.execute(notebook.value.id,currentQuestion.value.id,option,elapsedSeconds.value);await refresh(notebook.value.id);notice.value='Resposta registrada.';return true}catch(e){error.value=e instanceof Error?e.message:'Não foi possível registrar a resposta.';return false}finally{savingAnswer.value=false}}
 async function togglePause(){if(!notebook.value)return;pausing.value=true;try{notebook.value=notebook.value.status==='IN_PROGRESS'?await studyUseCases.pause.execute(notebook.value.id):await studyUseCases.start.execute(notebook.value.id);if(notebook.value.status==='IN_PROGRESS')run();else stop();await refresh(notebook.value.id)}catch(e){error.value=e instanceof Error?e.message:'Não foi possível alterar o contador.'}finally{pausing.value=false}}
 async function finish(){if(!notebook.value)return false;finishing.value=true;try{notebook.value=await studyUseCases.finish.execute(notebook.value.id);stop();return true}catch(e){error.value=e instanceof Error?e.message:'Não foi possível finalizar este caderno.';return false}finally{finishing.value=false}}
 onBeforeUnmount(stop);return{currentIndex:readonly(currentIndex),currentQuestion:readonly(currentQuestion),elapsed:readonly(elapsed),error:readonly(error),finish,finishing:readonly(finishing),isCurrentAnswered:readonly(isCurrentAnswered),load,refreshQuestions,loading:readonly(loading),next,goTo,notebook:readonly(notebook),notice:readonly(notice),pausing:readonly(pausing),previous,progress:readonly(progress),questions:readonly(questions),savingAnswer:readonly(savingAnswer),selectOption,selectedOptions:readonly(selectedOptions),statistics:readonly(statistics),submitCurrent,togglePause,totalQuestions:readonly(totalQuestions),nextSubject,hasNextSubject,previousSubject,hasPreviousSubject}
}
