<?php
declare(strict_types=1);
namespace App\Application\Catalog\Service;
use App\Application\Assistant\Port\AssistantProviderInterface;use App\Domain\Assistant\ValueObject\SyllabusEvidence;use App\Domain\Catalog\Entity\Position;use App\Domain\Catalog\Entity\Subject;use App\Domain\Catalog\Repository\PositionRepositoryInterface;use App\Domain\Catalog\Repository\SubjectRepositoryInterface;use App\Domain\Catalog\Repository\SubjectTaxonomyAssignmentRepositoryInterface;use App\Domain\Catalog\Repository\SyllabusDocumentExtractionRepositoryInterface;use App\Domain\Catalog\Repository\SyllabusRepositoryInterface;use App\Domain\Taxonomy\Entity\TaxonomySubject;use App\Domain\Taxonomy\Repository\TaxonomySubjectRepositoryInterface;use App\Domain\Taxonomy\Service\SubjectTaxonomyService;
final class AnalyzeSyllabusCatalogService {
public function __construct(private readonly SyllabusRepositoryInterface $syllabi,private readonly SyllabusDocumentExtractionRepositoryInterface $extractions,private readonly PositionRepositoryInterface $positions,private readonly SubjectRepositoryInterface $subjects,private readonly TaxonomySubjectRepositoryInterface $taxonomy,private readonly SubjectTaxonomyAssignmentRepositoryInterface $assignments,private readonly SubjectTaxonomyService $slugs,private readonly AssistantProviderInterface $ai){}
public function analyze(string $syllabusId):void{$syllabus=$this->syllabi->findById($syllabusId);if($syllabus===null)throw new \DomainException("Edital nao encontrado.");$pages=$this->extractions->listForSyllabus($syllabusId);if($pages===[])throw new \DomainException("Edital sem texto extraido.");$evidence=[];foreach($pages as $page){if(count($evidence)===16)break;if(preg_match("/cargo|conte[uú]do|conhecimento/i",$page->textContent)||count($evidence)<6)$evidence[]=new SyllabusEvidence($page->pageNumber,mb_substr($page->textContent,0,5000));}$answer=$this->ai->answer("Retorne SOMENTE JSON valido: {\"positions\":[\"cargo\"],\"subjects\":[{\"name\":\"assunto\",\"page\":1}]}. Extraia somente cargos e assuntos explicitamente listados no edital; no maximo 30 cargos e 40 assuntos.",$evidence)->content;$data=json_decode(preg_replace("/^```(?:json)?|```$/m","",trim($answer)),true,512,JSON_THROW_ON_ERROR);$knownPositions=array_map(fn($item)=>$this->key($item->name),$this->positions->listForExam($syllabus->examId));foreach($data["positions"]??[] as $name){if(!is_string($name)||!$this->valid($name)||in_array($this->key($name),$knownPositions,true))continue;$name=$this->label($name);$this->positions->save(new Position($this->id(),$syllabus->examId,$name,null));$knownPositions[]=$this->key($name);}$knownSubjects=array_map(fn($item)=>$this->key($item->name),$this->subjects->listForSyllabus($syllabusId));$canonical=$this->taxonomy->list(0,1000);foreach(array_slice($data["subjects"]??[],0,40) as $candidate){if(!is_array($candidate)||!is_string($candidate["name"]??null)||!$this->valid($candidate["name"]))continue;$name=$this->label($candidate["name"]);if(in_array($this->key($name),$knownSubjects,true))continue;$existing=null;foreach($canonical as $item){if($this->key($item->name)===$this->key($name)){$existing=$item;break;}}if($existing===null){$existing=new TaxonomySubject($this->id(),null,$name,$this->slugs->slug($name),null,0,true);$this->taxonomy->save($existing);$canonical[]=$existing;}$page=max(1,(int)($candidate["page"]??1));$subject=new Subject($this->id(),$syllabusId,null,$name,count($knownSubjects),null,$page);$this->subjects->save($subject);$this->assignments->replaceForSubject($subject->id,[$existing->id]);$knownSubjects[]=$this->key($name);}}
private function valid(string $name):bool{$name=trim($name);return mb_strlen($name)>2&&mb_strlen($name)<191;}private function label(string $name):string{return trim(preg_replace("/\\s+/u"," ",$name)??$name);}private function key(string $name):string{return mb_strtolower(iconv("UTF-8","ASCII//TRANSLIT",$this->label($name))?:$this->label($name));}private function id():string{return bin2hex(random_bytes(16));}
}
