<?php
declare(strict_types=1);namespace App\Infrastructure\Persistence\Doctrine\Identity;
use App\Domain\Identity\Entity\{User,UserAvatar};use App\Domain\Identity\Enum\AvatarSource;use App\Domain\Identity\Repository\UserRepositoryInterface;use App\Infrastructure\Persistence\Doctrine\Identity\Entity\{RoleRecord,UserRecord};use Doctrine\ORM\EntityManagerInterface;
final class DoctrineUserRepository implements UserRepositoryInterface
{
 public function __construct(private readonly EntityManagerInterface $entityManager){}
 public function findByEmail(string $email):?User{return $this->map($this->query()->where('user.email=:email')->setParameter('email',$email)->getQuery()->getOneOrNullResult());}
 public function findById(string $id):?User{return $this->map($this->query()->where('user.id=:id')->setParameter('id',$id)->getQuery()->getOneOrNullResult());}
 public function save(User $user):void{$record=$this->entityManager->find(UserRecord::class,$user->id);$new=!$record instanceof UserRecord;$record??=new UserRecord();$record->id=$user->id;$record->email=$user->email;$record->name=$user->name;$record->passwordHash=$user->passwordHash;$record->status=$user->status;$record->avatarStorageKey=$user->avatar?->storageKey;$record->avatarMimeType=$user->avatar?->mimeType;$record->avatarSource=$user->avatar?->source->value;$record->avatarUpdatedAt=$user->avatar?->updatedAt;$now=new \DateTimeImmutable('now');if($new)$record->createdAt=$now;$record->updatedAt=$now;$roles=$this->entityManager->createQueryBuilder()->select('role')->from(RoleRecord::class,'role')->where('role.code IN (:codes)')->setParameter('codes',$user->roles)->getQuery()->getResult();if(count($roles)!==count($user->roles))throw new \InvalidArgumentException('Papel inexistente.');$record->roles->clear();foreach($roles as $role)$record->roles->add($role);$this->entityManager->persist($record);}
 public function list(int $offset,int $limit,?string $query,?string $status):array{$q=$this->filtered($query,$status)->orderBy('user.createdAt','DESC')->setFirstResult($offset)->setMaxResults($limit)->getQuery()->getResult();return array_values(array_filter(array_map(fn(UserRecord $record):?User=>$this->map($record),$q)));}
 public function count(?string $query,?string $status):int{return(int)$this->filtered($query,$status)->select('COUNT(DISTINCT user.id)')->getQuery()->getSingleScalarResult();}
 public function countActiveAdmins():int{return(int)$this->entityManager->createQueryBuilder()->select('COUNT(DISTINCT user.id)')->from(UserRecord::class,'user')->join('user.roles','role')->where('user.status=:status')->andWhere('role.code=:role')->setParameter('status','ACTIVE')->setParameter('role','ADMIN')->getQuery()->getSingleScalarResult();}
 private function filtered(?string $query,?string $status):\Doctrine\ORM\QueryBuilder{$q=$this->query();if($query!==null&&$query!=='')$q->andWhere('LOWER(user.name) LIKE :query OR LOWER(user.email) LIKE :query')->setParameter('query','%'.mb_strtolower($query).'%');if($status!==null)$q->andWhere('user.status=:status')->setParameter('status',$status);return$q;}
 private function query():\Doctrine\ORM\QueryBuilder{return$this->entityManager->createQueryBuilder()->select('user','role')->from(UserRecord::class,'user')->leftJoin('user.roles','role');}
 private function map(?UserRecord $record):?User{if($record===null)return null;return new User($record->id,$record->email,$record->name,$record->passwordHash,$record->status,array_values($record->roles->map(static fn(RoleRecord $role):string=>$role->code)->toArray()),$record->avatarStorageKey===null||$record->avatarMimeType===null||$record->avatarSource===null||$record->avatarUpdatedAt===null?null:new UserAvatar($record->avatarStorageKey,$record->avatarMimeType,AvatarSource::from($record->avatarSource),$record->avatarUpdatedAt));}
}
