<?php
declare(strict_types=1);
namespace Tests\Unit\QuestionBank;
use App\Application\Catalog\Port\PdfTextExtractorInterface;
use App\Application\QuestionBank\DTO\Response\QuestionImportBatchAnalyzerResponseDto;
use App\Application\QuestionBank\Port\QuestionImportAnalyzerInterface;
use App\Application\QuestionBank\Port\QuestionPdfAssetExtractorInterface;
use App\Application\QuestionBank\Port\QuestionPdfQuestionWriterInterface;
use App\Application\QuestionBank\Service\ProcessQuestionPdfImportAnalysisJobService;
use App\Application\QuestionBank\Service\QuestionPdfCandidateSegmenter;
use App\Domain\QuestionBank\Entity\QuestionPdfImportCandidateCheckpoint;
use App\Domain\QuestionBank\Entity\QuestionPdfImportCandidateCheckpointSummary;
use App\Domain\QuestionBank\Entity\QuestionPdfImportJob;
use App\Domain\QuestionBank\Repository\QuestionImportAnalysisRepositoryInterface;
use App\Domain\QuestionBank\Repository\QuestionPdfImportCandidateCheckpointRepositoryInterface;
use App\Domain\QuestionBank\Repository\QuestionPdfImportJobRepositoryInterface;
use App\Domain\QuestionBank\Repository\QuestionQualitySignalRepositoryInterface;
use App\Domain\QuestionBank\ValueObject\QuestionImportTokenUsage;
use App\Domain\Taxonomy\Repository\TaxonomySubjectRepositoryInterface;
use PHPUnit\Framework\TestCase;
final class ProcessQuestionPdfImportBatchTest extends TestCase
{
 public function testMissingItemRetriesOnlyTheAffectedCheckpoints(): void {
  $job=new QuestionPdfImportJob("j",null,"u","/tmp/a",str_repeat("a",64),"a.pdf","PROCESSING",12,1,2,0,0,null,0,0,0,0,0,0,null,new \DateTimeImmutable("now"));
  $jobs=$this->createMock(QuestionPdfImportJobRepositoryInterface::class); $jobs->method("findById")->willReturn($job); $jobs->method("isCancelled")->willReturn(false);
  $analyzer=$this->createMock(QuestionImportAnalyzerInterface::class); $analyzer->method("analyzeBatch")->willReturn(new QuestionImportBatchAnalyzerResponseDto([],"fake",null,QuestionImportTokenUsage::unavailable(),1));
  $checkpoints=$this->createMock(QuestionPdfImportCandidateCheckpointRepositoryInterface::class); $checkpoints->expects(self::exactly(2))->method("retry"); $checkpoints->method("summaryForJob")->willReturn(new QuestionPdfImportCandidateCheckpointSummary(2,2,0,0,0,0,0,0,0,0));
  $service=new ProcessQuestionPdfImportAnalysisJobService($jobs,$this->createMock(PdfTextExtractorInterface::class),$analyzer,$this->createMock(TaxonomySubjectRepositoryInterface::class),$this->createMock(QuestionPdfQuestionWriterInterface::class),$this->createMock(QuestionPdfAssetExtractorInterface::class),new QuestionPdfCandidateSegmenter(),$this->createMock(QuestionImportAnalysisRepositoryInterface::class),$this->createMock(QuestionQualitySignalRepositoryInterface::class),$checkpoints);
  $now=new \DateTimeImmutable("now"); $payload=["schema_version"=>"question-import-analysis-v1","evidence_pages"=>[["page_number"=>1,"content"=>"Questão"]],"images"=>[],"taxonomy_paths"=>["Tecnologia"]]; $items=[new QuestionPdfImportCandidateCheckpoint("1","j",str_repeat("b",64),0,$payload,"PROCESSING",0,null,$now,null,$now,$now),new QuestionPdfImportCandidateCheckpoint("2","j",str_repeat("c",64),1,$payload,"PROCESSING",0,null,$now,null,$now,$now)];
  $method=new \ReflectionMethod(ProcessQuestionPdfImportAnalysisJobService::class,"processCheckpointBatch"); self::assertTrue($method->invoke($service,$items));
 }
 public function testRecognizesFourOptionsWithUpperOrLowercaseLabels(): void { $candidates=(new QuestionPdfCandidateSegmenter())->segment(["Questão 1. Assinale.\na) primeira\nb) segunda\nc) terceira\nd) quarta\nGabarito d", "Questão 2. Assinale.\nA) primeira\nB) segunda\nC) terceira\nD) quarta\nGABARITO LETRA A"], [], []); self::assertCount(2, $candidates); }
 public function testExcludesTrueFalseAndEmbeddedGabaritoMention(): void { $candidates=(new QuestionPdfCandidateSegmenter())->segment(["1- Julgue o item.\nGabarito: Certo.\n2- Questão objetiva.\na) uma  b) duas  c) três  d) quatro\n(Gabarito B) é uma explicação.\nGABARITO: letra d"], [], []); self::assertCount(1, $candidates); }
 public function testDetectsBlankVisualOptionsForImageExtraction(): void { $service=(new \ReflectionClass(ProcessQuestionPdfImportAnalysisJobService::class))->newInstanceWithoutConstructor(); $method=new \ReflectionMethod(ProcessQuestionPdfImportAnalysisJobService::class,"requiresVisualExtraction"); self::assertTrue($method->invoke($service,"18- Enunciado\na)\n\n\nb)\n\n\nc)\n\n\nd)\n\n\ne)\nResolução:")); self::assertFalse($method->invoke($service,"Questão\na) texto\nb) texto\nc) texto\nd) texto\nGabarito: A")); }
 public function testInvalidBatchFailsCheckpointsWithoutRetry(): void { $job=new QuestionPdfImportJob("j",null,"u","/tmp/a",str_repeat("a",64),"a.pdf","PROCESSING",12,1,2,0,0,null,0,0,0,0,0,0,null,new \DateTimeImmutable("now")); $jobs=$this->createMock(QuestionPdfImportJobRepositoryInterface::class); $jobs->method("findById")->willReturn($job); $jobs->method("isCancelled")->willReturn(false); $analyzer=$this->createMock(QuestionImportAnalyzerInterface::class); $analyzer->method("analyzeBatch")->willThrowException(new \DomainException("Resposta inválida.")); $checkpoints=$this->createMock(QuestionPdfImportCandidateCheckpointRepositoryInterface::class); $checkpoints->expects(self::exactly(2))->method("fail"); $checkpoints->expects(self::never())->method("retry"); $checkpoints->method("summaryForJob")->willReturn(new QuestionPdfImportCandidateCheckpointSummary(2,0,0,0,2,0,0,0,0,2)); $service=new ProcessQuestionPdfImportAnalysisJobService($jobs,$this->createMock(PdfTextExtractorInterface::class),$analyzer,$this->createMock(TaxonomySubjectRepositoryInterface::class),$this->createMock(QuestionPdfQuestionWriterInterface::class),$this->createMock(QuestionPdfAssetExtractorInterface::class),new QuestionPdfCandidateSegmenter(),$this->createMock(QuestionImportAnalysisRepositoryInterface::class),$this->createMock(QuestionQualitySignalRepositoryInterface::class),$checkpoints); $now=new \DateTimeImmutable("now"); $payload=["schema_version"=>"question-import-analysis-v1","evidence_pages"=>[["page_number"=>1,"content"=>"Questão"]],"images"=>[],"taxonomy_paths"=>["Tecnologia"]]; $items=[new QuestionPdfImportCandidateCheckpoint("1","j",str_repeat("b",64),0,$payload,"PROCESSING",0,null,$now,null,$now,$now),new QuestionPdfImportCandidateCheckpoint("2","j",str_repeat("c",64),1,$payload,"PROCESSING",0,null,$now,null,$now,$now)]; $method=new \ReflectionMethod(ProcessQuestionPdfImportAnalysisJobService::class,"processCheckpointBatch"); self::assertTrue($method->invoke($service,$items)); }
 public function testConsolidatesProcessedAndRejectedCandidatesFromCheckpointOutcomes(): void { $job=new QuestionPdfImportJob("j",null,"u","/tmp/a",str_repeat("a",64),"a.pdf","PROCESSING",12,1,2,0,0,null,0,0,0,0,0,0,null,new \DateTimeImmutable("now")); $saved=null; $jobs=$this->createMock(QuestionPdfImportJobRepositoryInterface::class); $jobs->method("findById")->willReturn($job); $jobs->method("isCancelled")->willReturn(false); $jobs->method("save")->willReturnCallback(function ($value) use (&$saved): void { $saved=$value; }); $checkpoints=$this->createMock(QuestionPdfImportCandidateCheckpointRepositoryInterface::class); $checkpoints->method("summaryForJob")->willReturn(new QuestionPdfImportCandidateCheckpointSummary(2,0,0,1,1,1,1,0,0,1)); $analyses=$this->createMock(QuestionImportAnalysisRepositoryInterface::class); $analyses->method("listForJob")->willReturn([]); $service=new ProcessQuestionPdfImportAnalysisJobService($jobs,$this->createMock(PdfTextExtractorInterface::class),$this->createMock(QuestionImportAnalyzerInterface::class),$this->createMock(TaxonomySubjectRepositoryInterface::class),$this->createMock(QuestionPdfQuestionWriterInterface::class),$this->createMock(QuestionPdfAssetExtractorInterface::class),new QuestionPdfCandidateSegmenter(),$analyses,$this->createMock(QuestionQualitySignalRepositoryInterface::class),$checkpoints); $method=new \ReflectionMethod(ProcessQuestionPdfImportAnalysisJobService::class,"consolidateJob"); $method->invoke($service,"j"); self::assertSame(2,$saved->extractedQuestions); self::assertSame(1,$saved->createdQuestions); self::assertSame(1,$saved->failedQuestions); self::assertSame("COMPLETED",$saved->status); }
}
