<?php
declare(strict_types=1);
namespace Tests\Unit\Review;
use App\Application\Review\AI\NotebookAnalysisResponseValidator;use App\Domain\Review\Enum\FlashcardType;use App\Domain\Review\Enum\MasteryConfidence;use App\Domain\Review\Enum\ReviewRating;use App\Domain\Review\Service\InitialMasteryEstimator;use App\Domain\Review\Service\InitialSpacedRepetitionStrategy;use App\Domain\Review\ValueObject\FlashcardFingerprint;use App\Domain\Review\ValueObject\FlashcardProgressState;use App\Domain\Review\ValueObject\ReviewAlgorithmConfiguration;use PHPUnit\Framework\TestCase;
final class ReviewAlgorithmsTest extends TestCase {
 public function testAgainSchedulesShortIntervalAndDoesNotIncreaseRepetitions():void{$now=new \DateTimeImmutable('2026-01-01T10:00:00Z');$state=new FlashcardProgressState($now,3,2.5,4,0);$next=(new InitialSpacedRepetitionStrategy(new ReviewAlgorithmConfiguration(10)))->next($state,ReviewRating::AGAIN,$now);self::assertSame(0,$next->repetitions);self::assertSame(1,$next->lapses);self::assertSame('10:10',$next->dueAt->format('H:i'));}
 public function testFingerprintIgnoresWhitespaceAndCase():void{$a=FlashcardFingerprint::fromContent('concept',FlashcardType::BASIC,'  HTTP   status ','Resposta');$b=FlashcardFingerprint::fromContent('concept',FlashcardType::BASIC,'http status',' resposta ');self::assertSame($a->value,$b->value);}
 public function testInvalidProviderPayloadIsRejectedBeforeApplication():void{$this->expectException(\InvalidArgumentException::class);(new NotebookAnalysisResponseValidator())->validate(['actions'=>[['type'=>'CREATE_OR_REUSE_CARD','reason'=>'x','confidence'=>1]]]);}
 public function testValidNoActionIsAccepted():void{$actions=(new NotebookAnalysisResponseValidator())->validate(['actions'=>[['type'=>'NO_ACTION','reason'=>'Sem lacuna conceitual','confidence'=>0.8]]]);self::assertSame('NO_ACTION',$actions[0]['type']);}
 public function testGoodReviewIncreasesIntervalAndKeepsLapses():void{$now=new \DateTimeImmutable('2026-01-01T10:00:00Z');$next=(new InitialSpacedRepetitionStrategy(new ReviewAlgorithmConfiguration()))->next(new FlashcardProgressState($now,2,2.5,1,3),ReviewRating::GOOD,$now);self::assertGreaterThanOrEqual(5,$next->intervalDays);self::assertSame(2,$next->repetitions);self::assertSame(3,$next->lapses);}
 public function testMasteryRemainsUnavailableWithLowEvidence():void{$now=new \DateTimeImmutable('2026-01-01T10:00:00Z');$estimate=(new InitialMasteryEstimator(new ReviewAlgorithmConfiguration(minimumEvidence:3)))->estimate('user','subject',2,.9,.9,$now,$now);self::assertNull($estimate->masteryScore);self::assertSame(MasteryConfidence::INSUFFICIENT,$estimate->confidence);}
 public function testMasteryUsesEvidenceWhenThresholdIsReached():void{$now=new \DateTimeImmutable('2026-01-01T10:00:00Z');$estimate=(new InitialMasteryEstimator(new ReviewAlgorithmConfiguration(minimumEvidence:3)))->estimate('user','subject',3,.8,.6,$now,$now);self::assertNotNull($estimate->masteryScore);self::assertSame(MasteryConfidence::LOW,$estimate->confidence);}
 public function testInvalidAnalysisIsRetriedWithoutApplyingActions():void{$now=new \DateTimeImmutable('2026-01-01T10:00:00Z');$execution=new \App\Domain\Review\Entity\NotebookAnalysisExecution('execution','notebook','v1',\App\Domain\Review\Enum\NotebookAnalysisStatus::PENDING,0,null,null,null,null,null,null,null,$now);$repository=new class($execution) implements \App\Domain\Review\Repository\NotebookAnalysisExecutionRepositoryInterface {public array $saved=[];public function __construct(public $execution){}public function findByNotebookAndVersion(string $notebookId,string $version):?\App\Domain\Review\Entity\NotebookAnalysisExecution{return $this->execution;}public function findForNotebookUser(string $notebookId,string $userId):?\App\Domain\Review\Entity\NotebookAnalysisExecution{return null;}public function claimNextPending(\DateTimeImmutable $now):?\App\Domain\Review\ValueObject\NotebookAnalysisJob{return null;}public function save(\App\Domain\Review\Entity\NotebookAnalysisExecution $execution):void{$this->saved[]=$execution;}};$reader=new class implements \App\Domain\Study\Repository\NotebookProgressReaderInterface {public function completedAnswersForNotebook(string $userId,string $notebookId):array{return [];}};$service=new \App\Application\Review\Service\ProcessNotebookAnalysisService($repository,new \App\Application\Review\Service\BuildNotebookPerformanceSummaryService($reader),new NotebookAnalysisResponseValidator());$applied=false;$result=$service->execute('notebook','user','v1',static fn(array $payload):array=>['invalid'=>true],$now,static function(array $actions)use(&$applied):void{$applied=true;});self::assertSame([],$result);self::assertSame(1,$execution->retryCount);self::assertSame(\App\Domain\Review\Enum\NotebookAnalysisStatus::FAILED,$execution->status);self::assertFalse($applied);self::assertCount(2,$repository->saved);}
 public function testCompletedAnalysisIsNotProcessedTwice():void{$now=new \DateTimeImmutable('2026-01-01T10:00:00Z');$execution=new \App\Domain\Review\Entity\NotebookAnalysisExecution('execution','notebook','v1',\App\Domain\Review\Enum\NotebookAnalysisStatus::COMPLETED,0,null,null,null,null,null,null,null,$now);$repository=new class($execution) implements \App\Domain\Review\Repository\NotebookAnalysisExecutionRepositoryInterface {public function __construct(public $execution){}public function findByNotebookAndVersion(string $notebookId,string $version):?\App\Domain\Review\Entity\NotebookAnalysisExecution{return $this->execution;}public function findForNotebookUser(string $notebookId,string $userId):?\App\Domain\Review\Entity\NotebookAnalysisExecution{return null;}public function claimNextPending(\DateTimeImmutable $now):?\App\Domain\Review\ValueObject\NotebookAnalysisJob{return null;}public function save(\App\Domain\Review\Entity\NotebookAnalysisExecution $execution):void{}};$reader=new class implements \App\Domain\Study\Repository\NotebookProgressReaderInterface {public function completedAnswersForNotebook(string $userId,string $notebookId):array{return [];}};$service=new \App\Application\Review\Service\ProcessNotebookAnalysisService($repository,new \App\Application\Review\Service\BuildNotebookPerformanceSummaryService($reader),new NotebookAnalysisResponseValidator());$called=false;self::assertSame([],$service->execute('notebook','user','v1',static function(array $payload)use(&$called):array{$called=true;return ['actions'=>[]];},$now));self::assertFalse($called);}
 public function testMasteryBecomesHighWithLongHistory():void{$now=new \DateTimeImmutable('2026-01-01T10:00:00Z');$estimate=(new InitialMasteryEstimator(new ReviewAlgorithmConfiguration(minimumEvidence:3)))->estimate('user','subject',50,.9,.9,$now,$now);self::assertSame(MasteryConfidence::HIGH,$estimate->confidence);self::assertGreaterThan(80,$estimate->masteryScore);}
}
