<?php
declare(strict_types=1);
namespace App\Interface\Http\Catalog\Controller;
use App\Application\Catalog\DTO\Request\CreatePositionRequestDto;use App\Application\Catalog\DTO\Request\CreateSyllabusRequestDto;use App\Application\Catalog\Service\CreatePositionService;use App\Application\Catalog\Service\CreateSyllabusService;use App\Application\Catalog\Service\ListPositionsService;use App\Application\Catalog\Service\ListSyllabiService;use App\Application\Identity\DTO\Request\AccessTokenRequestDto;use App\Application\Identity\Service\AuthService;use App\Domain\Identity\Exception\UnavailableUserException;use App\Infrastructure\Http\ApiResponseFactory;use DomainException;use Psr\Http\Message\ResponseInterface;use Psr\Http\Message\ServerRequestInterface;
final class PositionSyllabusController{
 public function __construct(private readonly AuthService $auth,private readonly CreatePositionService $createPosition,private readonly ListPositionsService $listPositions,private readonly CreateSyllabusService $createSyllabus,private readonly ListSyllabiService $listSyllabi,private readonly ApiResponseFactory $responses){}
 public function createPosition(ServerRequestInterface $r,ResponseInterface $p,AccessTokenRequestDto $a,CreatePositionRequestDto $i):ResponseInterface{if(($x=$this->admin($r,$p,$a))!==null)return $x;return $this->responses->success($p,$this->createPosition->create($i),$this->id($r),201);}
 public function listPositions(ServerRequestInterface $r,ResponseInterface $p,AccessTokenRequestDto $a,string $examId):ResponseInterface{if(($x=$this->authenticated($r,$p,$a))!==null)return $x;return $this->responses->success($p,$this->listPositions->list($examId),$this->id($r));}
 public function createSyllabus(ServerRequestInterface $r,ResponseInterface $p,AccessTokenRequestDto $a,CreateSyllabusRequestDto $i):ResponseInterface{if(($x=$this->admin($r,$p,$a))!==null)return $x;return $this->responses->success($p,$this->createSyllabus->create($i),$this->id($r),201);}
 public function listSyllabi(ServerRequestInterface $r,ResponseInterface $p,AccessTokenRequestDto $a,string $positionId):ResponseInterface{if(($x=$this->authenticated($r,$p,$a))!==null)return $x;return $this->responses->success($p,$this->listSyllabi->list($positionId),$this->id($r));}
 private function authenticated(ServerRequestInterface $r,ResponseInterface $p,AccessTokenRequestDto $a):?ResponseInterface{try{$this->auth->currentUser($a);return null;}catch(DomainException|UnavailableUserException){return $this->responses->problem($p,'UNAUTHENTICATED','Credenciais invalidas ou expiradas.',401,$this->id($r));}}
 private function admin(ServerRequestInterface $r,ResponseInterface $p,AccessTokenRequestDto $a):?ResponseInterface{try{$u=$this->auth->currentUser($a);}catch(DomainException|UnavailableUserException){return $this->responses->problem($p,'UNAUTHENTICATED','Credenciais invalidas ou expiradas.',401,$this->id($r));}return in_array('ADMIN',$u->roles,true)?null:$this->responses->problem($p,'FORBIDDEN','Permissao insuficiente.',403,$this->id($r));}
 private function id(ServerRequestInterface $r):string{return(string)$r->getAttribute('request_id');}
}
